//
// CreateListingBulkDelistPreviewResponseMarketplaces.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CreateListingBulkDelistPreviewResponseMarketplaces: Codable, JSONEncodable, Hashable {

    public enum AccountStatus: String, Codable, CaseIterable {
        case active = "active"
        case unknown = "unknown"
        case needsReauth = "needs_reauth"
    }
    public var platform: String
    public var activeCount: Double
    public var accountStatus: AccountStatus

    public init(platform: String, activeCount: Double, accountStatus: AccountStatus) {
        self.platform = platform
        self.activeCount = activeCount
        self.accountStatus = accountStatus
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case platform
        case activeCount
        case accountStatus
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(platform, forKey: .platform)
        try container.encode(activeCount, forKey: .activeCount)
        try container.encode(accountStatus, forKey: .accountStatus)
    }
}

