//
// CreateCbxAdCreditQuoteResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CreateCbxAdCreditQuoteResponse: Codable, JSONEncodable, Hashable {

    public var baseUnits: String
    public var creditCents: Double
    public var centsPerToken: Double

    public init(baseUnits: String, creditCents: Double, centsPerToken: Double) {
        self.baseUnits = baseUnits
        self.creditCents = creditCents
        self.centsPerToken = centsPerToken
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case baseUnits
        case creditCents
        case centsPerToken
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(baseUnits, forKey: .baseUnits)
        try container.encode(creditCents, forKey: .creditCents)
        try container.encode(centsPerToken, forKey: .centsPerToken)
    }
}

