//
// CreateBuyerIdentifyResponseVisualMatches.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CreateBuyerIdentifyResponseVisualMatches: Codable, JSONEncodable, Hashable {

    public var slug: String
    public var title: String
    public var priceCents: Double
    public var imageUrl: String?
    /** Cosine similarity. Higher is closer. */
    public var score: Double

    public init(slug: String, title: String, priceCents: Double, imageUrl: String? = nil, score: Double) {
        self.slug = slug
        self.title = title
        self.priceCents = priceCents
        self.imageUrl = imageUrl
        self.score = score
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case slug
        case title
        case priceCents
        case imageUrl
        case score
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(slug, forKey: .slug)
        try container.encode(title, forKey: .title)
        try container.encode(priceCents, forKey: .priceCents)
        try container.encodeIfPresent(imageUrl, forKey: .imageUrl)
        try container.encode(score, forKey: .score)
    }
}

