//
// CreateAutomationRuleRunNowResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CreateAutomationRuleRunNowResponse: Codable, JSONEncodable, Hashable {

    public var success: Bool
    public var jobId: String?

    public init(success: Bool, jobId: String? = nil) {
        self.success = success
        self.jobId = jobId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case success
        case jobId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(success, forKey: .success)
        try container.encodeIfPresent(jobId, forKey: .jobId)
    }
}

