//
// CreateOrderMessageResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CreateOrderMessageResponse: Codable, JSONEncodable, Hashable {

    public var orderId: String
    public var sent: Bool
    public var platformConversationId: String

    public init(orderId: String, sent: Bool, platformConversationId: String) {
        self.orderId = orderId
        self.sent = sent
        self.platformConversationId = platformConversationId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case orderId
        case sent
        case platformConversationId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(orderId, forKey: .orderId)
        try container.encode(sent, forKey: .sent)
        try container.encode(platformConversationId, forKey: .platformConversationId)
    }
}

