//
// CreateCbxSubjectSpendPlanResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CreateCbxSubjectSpendPlanResponse: Codable, JSONEncodable, Hashable {

    public var legs: [CreateCbxSubjectSpendPlanResponseLegs]
    public var shortfallBaseUnits: String
    public var fullyFunded: Bool

    public init(legs: [CreateCbxSubjectSpendPlanResponseLegs], shortfallBaseUnits: String, fullyFunded: Bool) {
        self.legs = legs
        self.shortfallBaseUnits = shortfallBaseUnits
        self.fullyFunded = fullyFunded
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case legs
        case shortfallBaseUnits
        case fullyFunded
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(legs, forKey: .legs)
        try container.encode(shortfallBaseUnits, forKey: .shortfallBaseUnits)
        try container.encode(fullyFunded, forKey: .fullyFunded)
    }
}

