//
// CreateAutomationRuleValidateRecipeResponseDetails.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CreateAutomationRuleValidateRecipeResponseDetails: Codable, JSONEncodable, Hashable {

    public var formErrors: [String]
    public var fieldErrors: CreateAutomationRuleValidateRecipeResponseDetailsFieldErrors

    public init(formErrors: [String], fieldErrors: CreateAutomationRuleValidateRecipeResponseDetailsFieldErrors) {
        self.formErrors = formErrors
        self.fieldErrors = fieldErrors
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case formErrors
        case fieldErrors
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(formErrors, forKey: .formErrors)
        try container.encode(fieldErrors, forKey: .fieldErrors)
    }
}

