//
// CreateBuyerScanResponseIdentifier.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CreateBuyerScanResponseIdentifier: Codable, JSONEncodable, Hashable {

    public enum Ns: String, Codable, CaseIterable {
        case styleCode = "style_code"
        case gtin = "gtin"
        case legoSet = "lego_set"
        case tcgplayer = "tcgplayer"
        case discogs = "discogs"
        case asin = "asin"
    }
    public var value: String
    public var ns: Ns

    public init(value: String, ns: Ns) {
        self.value = value
        self.ns = ns
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case value
        case ns
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(value, forKey: .value)
        try container.encode(ns, forKey: .ns)
    }
}

