//
// CreateCbxWalletVerifyResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CreateCbxWalletVerifyResponse: Codable, JSONEncodable, Hashable {

    public var verified: Bool

    public init(verified: Bool) {
        self.verified = verified
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case verified
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(verified, forKey: .verified)
    }
}

