//
// CreateSourcingReceiptResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CreateSourcingReceiptResponse: Codable, JSONEncodable, Hashable {

    public var ok: Bool
    public var count: Double

    public init(ok: Bool, count: Double) {
        self.ok = ok
        self.count = count
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case ok
        case count
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(ok, forKey: .ok)
        try container.encode(count, forKey: .count)
    }
}

