//
// CreateCustomerBulkDeleteResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CreateCustomerBulkDeleteResponse: Codable, JSONEncodable, Hashable {

    public var ok: Bool
    public var deleted: Double

    public init(ok: Bool, deleted: Double) {
        self.ok = ok
        self.deleted = deleted
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case ok
        case deleted
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(ok, forKey: .ok)
        try container.encode(deleted, forKey: .deleted)
    }
}

