//
// CreateBuyerScanSessionResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CreateBuyerScanSessionResponse: Codable, JSONEncodable, Hashable {

    public var id: String
    public var device: String
    public var label: String?
    public var startedAt: String
    public var captureCount: Double

    public init(id: String, device: String, label: String? = nil, startedAt: String, captureCount: Double) {
        self.id = id
        self.device = device
        self.label = label
        self.startedAt = startedAt
        self.captureCount = captureCount
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case device
        case label
        case startedAt
        case captureCount
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(device, forKey: .device)
        try container.encodeIfPresent(label, forKey: .label)
        try container.encode(startedAt, forKey: .startedAt)
        try container.encode(captureCount, forKey: .captureCount)
    }
}

