//
// CreateOrderBulkMarkShippedResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CreateOrderBulkMarkShippedResponse: Codable, JSONEncodable, Hashable {

    public var updated: Double
    /** Cancelled/refunded orders in the request that were left untouched — reported so a caller can't mistake a partial success for \"all done\" and miss that a closed order was in the batch. */
    public var skipped: Double

    public init(updated: Double, skipped: Double) {
        self.updated = updated
        self.skipped = skipped
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case updated
        case skipped
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(updated, forKey: .updated)
        try container.encode(skipped, forKey: .skipped)
    }
}

