//
// CreateCbxClaimResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CreateCbxClaimResponse: Codable, JSONEncodable, Hashable {

    public var claimId: String
    public var status: String
    public var requestedBaseUnits: String
    public var serviceFeeBaseUnits: String
    public var networkFeeBaseUnits: String
    public var netBaseUnits: String

    public init(claimId: String, status: String, requestedBaseUnits: String, serviceFeeBaseUnits: String, networkFeeBaseUnits: String, netBaseUnits: String) {
        self.claimId = claimId
        self.status = status
        self.requestedBaseUnits = requestedBaseUnits
        self.serviceFeeBaseUnits = serviceFeeBaseUnits
        self.networkFeeBaseUnits = networkFeeBaseUnits
        self.netBaseUnits = netBaseUnits
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case claimId
        case status
        case requestedBaseUnits
        case serviceFeeBaseUnits
        case networkFeeBaseUnits
        case netBaseUnits
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(claimId, forKey: .claimId)
        try container.encode(status, forKey: .status)
        try container.encode(requestedBaseUnits, forKey: .requestedBaseUnits)
        try container.encode(serviceFeeBaseUnits, forKey: .serviceFeeBaseUnits)
        try container.encode(networkFeeBaseUnits, forKey: .networkFeeBaseUnits)
        try container.encode(netBaseUnits, forKey: .netBaseUnits)
    }
}

