//
// CreatePlatformAccountConnectResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CreatePlatformAccountConnectResponse: Codable, JSONEncodable, Hashable {

    public var status: String
    public var accountId: String
    public var needsFirstSync: Bool

    public init(status: String, accountId: String, needsFirstSync: Bool) {
        self.status = status
        self.accountId = accountId
        self.needsFirstSync = needsFirstSync
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case status
        case accountId
        case needsFirstSync
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(status, forKey: .status)
        try container.encode(accountId, forKey: .accountId)
        try container.encode(needsFirstSync, forKey: .needsFirstSync)
    }
}

