//
// CreateBuyerActivityResponseMatchOffer.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CreateBuyerActivityResponseMatchOffer: Codable, JSONEncodable, Hashable {

    public enum Kind: String, Codable, CaseIterable {
        case listing = "listing"
        case ask = "ask"
    }
    public var kind: Kind
    public var priceCents: Double
    /** Free-text on listings, an order-book grade ('DS') on asks. Never null on asks; frequently null on listings, which is itself informative. */
    public var condition: String?
    public var title: String?
    public var imageUrl: String?
    public var url: String
    /** The public slug, when this offer is a marketplace listing.  Present so Scout can buy it without parsing the URL it was given back. Null on an order-book ask, which is deliberate rather than an omission: an ask is a price in a book, not a thing with a checkout, and a Buy button on one would be a promise the market side cannot keep. */
    public var slug: String?
    /** How many the seller has. Caps the quantity stepper honestly. */
    public var available: Double?

    public init(kind: Kind, priceCents: Double, condition: String? = nil, title: String? = nil, imageUrl: String? = nil, url: String, slug: String? = nil, available: Double? = nil) {
        self.kind = kind
        self.priceCents = priceCents
        self.condition = condition
        self.title = title
        self.imageUrl = imageUrl
        self.url = url
        self.slug = slug
        self.available = available
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case kind
        case priceCents
        case condition
        case title
        case imageUrl
        case url
        case slug
        case available
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(kind, forKey: .kind)
        try container.encode(priceCents, forKey: .priceCents)
        try container.encodeIfPresent(condition, forKey: .condition)
        try container.encodeIfPresent(title, forKey: .title)
        try container.encodeIfPresent(imageUrl, forKey: .imageUrl)
        try container.encode(url, forKey: .url)
        try container.encodeIfPresent(slug, forKey: .slug)
        try container.encodeIfPresent(available, forKey: .available)
    }
}

