//
// CreateBuyerIdentifyResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CreateBuyerIdentifyResponse: Codable, JSONEncodable, Hashable {

    public enum Tier: String, Codable, CaseIterable {
        case _none = "none"
        case visual = "visual"
        case identifier = "identifier"
        case vision = "vision"
    }
    public enum Verdict: String, Codable, CaseIterable {
        case crosslyBest = "crossly_best"
        case offsiteCheaper = "offsite_cheaper"
        case offsiteOnly = "offsite_only"
        case noMatch = "no_match"
    }
    public var tier: Tier
    public var confidence: Double
    public var identifier: CreateBuyerIdentifyResponseIdentifier?
    public var visionLabel: String?
    /** Surfaced rather than hidden: \"we could not look harder\" and \"we looked and found nothing\" are different answers, and a client that cannot tell them apart shows the wrong message on both. */
    public var visionQuotaExhausted: Bool
    public var visualMatches: [CreateBuyerIdentifyResponseVisualMatches]
    public var verdict: Verdict
    public var crossly: GetBuyerAnywhereResponseCrossly?
    public var offsite: GetBuyerAnywhereResponseOffsite?
    public var alternates: [GetBuyerAnywhereResponseAlternates]
    public var savingCents: Double?
    public var shippingUnknown: Bool
    public var hud: CreateBuyerIdentifyResponseHud

    public init(tier: Tier, confidence: Double, identifier: CreateBuyerIdentifyResponseIdentifier? = nil, visionLabel: String? = nil, visionQuotaExhausted: Bool, visualMatches: [CreateBuyerIdentifyResponseVisualMatches], verdict: Verdict, crossly: GetBuyerAnywhereResponseCrossly? = nil, offsite: GetBuyerAnywhereResponseOffsite? = nil, alternates: [GetBuyerAnywhereResponseAlternates], savingCents: Double? = nil, shippingUnknown: Bool, hud: CreateBuyerIdentifyResponseHud) {
        self.tier = tier
        self.confidence = confidence
        self.identifier = identifier
        self.visionLabel = visionLabel
        self.visionQuotaExhausted = visionQuotaExhausted
        self.visualMatches = visualMatches
        self.verdict = verdict
        self.crossly = crossly
        self.offsite = offsite
        self.alternates = alternates
        self.savingCents = savingCents
        self.shippingUnknown = shippingUnknown
        self.hud = hud
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case tier
        case confidence
        case identifier
        case visionLabel
        case visionQuotaExhausted
        case visualMatches
        case verdict
        case crossly
        case offsite
        case alternates
        case savingCents
        case shippingUnknown
        case hud
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(tier, forKey: .tier)
        try container.encode(confidence, forKey: .confidence)
        try container.encodeIfPresent(identifier, forKey: .identifier)
        try container.encodeIfPresent(visionLabel, forKey: .visionLabel)
        try container.encode(visionQuotaExhausted, forKey: .visionQuotaExhausted)
        try container.encode(visualMatches, forKey: .visualMatches)
        try container.encode(verdict, forKey: .verdict)
        try container.encodeIfPresent(crossly, forKey: .crossly)
        try container.encodeIfPresent(offsite, forKey: .offsite)
        try container.encode(alternates, forKey: .alternates)
        try container.encodeIfPresent(savingCents, forKey: .savingCents)
        try container.encode(shippingUnknown, forKey: .shippingUnknown)
        try container.encode(hud, forKey: .hud)
    }
}

