//
// CreateListingBulkCrosspostResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CreateListingBulkCrosspostResponse: Codable, JSONEncodable, Hashable {

    public var message: String
    public var bulkJobId: Null

    public init(message: String, bulkJobId: Null) {
        self.message = message
        self.bulkJobId = bulkJobId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case message
        case bulkJobId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(message, forKey: .message)
        try container.encode(bulkJobId, forKey: .bulkJobId)
    }
}

