//
// CreateOrderPullPlatformLabelResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CreateOrderPullPlatformLabelResponse: Codable, JSONEncodable, Hashable {

    public enum Provenance: String, Codable, CaseIterable {
        case verified = "verified"
        case provisional = "provisional"
    }
    public var url: String
    public var persisted: Bool
    public var expiresInSeconds: Double
    public var provenance: Provenance

    public init(url: String, persisted: Bool, expiresInSeconds: Double, provenance: Provenance) {
        self.url = url
        self.persisted = persisted
        self.expiresInSeconds = expiresInSeconds
        self.provenance = provenance
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case url
        case persisted
        case expiresInSeconds
        case provenance
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(url, forKey: .url)
        try container.encode(persisted, forKey: .persisted)
        try container.encode(expiresInSeconds, forKey: .expiresInSeconds)
        try container.encode(provenance, forKey: .provenance)
    }
}

