//
// CreateInboxAiSuggestResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CreateInboxAiSuggestResponse: Codable, JSONEncodable, Hashable {

    public var suggestion: String

    public init(suggestion: String) {
        self.suggestion = suggestion
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case suggestion
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(suggestion, forKey: .suggestion)
    }
}

