//
// CreateMagicScanResponseTopHits.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CreateMagicScanResponseTopHits: Codable, JSONEncodable, Hashable {

    public enum State: String, Codable, CaseIterable {
        case active = "active"
        case sold = "sold"
    }
    public var platform: String
    public var title: String
    public var priceCents: Double
    public var imageUrl: String?
    public var listingUrl: String?
    /** Origin marker for the UI badge. */
    public var origin: String
    /** CLIP cosine [0,1]; populated after the visual-rank pass. */
    public var visualSim: Double?
    /** 'active' = currently for sale; 'sold' = historical comp. UI  renders distinct badges so the seller can see both at a glance. */
    public var state: State

    public init(platform: String, title: String, priceCents: Double, imageUrl: String? = nil, listingUrl: String? = nil, origin: String, visualSim: Double? = nil, state: State) {
        self.platform = platform
        self.title = title
        self.priceCents = priceCents
        self.imageUrl = imageUrl
        self.listingUrl = listingUrl
        self.origin = origin
        self.visualSim = visualSim
        self.state = state
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case platform
        case title
        case priceCents
        case imageUrl
        case listingUrl
        case origin
        case visualSim
        case state
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(platform, forKey: .platform)
        try container.encode(title, forKey: .title)
        try container.encode(priceCents, forKey: .priceCents)
        try container.encodeIfPresent(imageUrl, forKey: .imageUrl)
        try container.encodeIfPresent(listingUrl, forKey: .listingUrl)
        try container.encode(origin, forKey: .origin)
        try container.encodeIfPresent(visualSim, forKey: .visualSim)
        try container.encode(state, forKey: .state)
    }
}

