//
// CreateListingByIdResponseItems.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CreateListingByIdResponseItems: Codable, JSONEncodable, Hashable {

    public var effectiveTitle: String
    public var effectivePrice: String?
    public var effectiveDescription: String?
    public var effectiveImages: [String]
    public var effectiveBrand: String?
    public var effectiveCondition: String?
    public var effectiveSize: String?
    public var effectiveSku: String?
    public var effectiveColor: [String]
    public var effectiveTags: [String]
    public var platformListings: [AnyCodable]
    public var inventoryItemId: String?
    public var id: String
    public var userId: String
    public var name: String?
    public var title: String?
    public var description: String?
    public var descriptionHtml: String?
    public var price: String?
    public var images: [String]?
    /** Optional single product video (R2/CDN URL). Shown on the Crossly buyer page. */
    public var videoUrl: String?
    public var status: String
    public var condition: String?
    /** Third-party grading, when the item is slabbed. Migration 0277.    Separate from `condition` on purpose and never derived from it: a grade  is a claim about what a GRADING COMPANY certified, and inferring \"PSA 10\"  from a coarse condition would be a false authenticity claim. It is also  never filled from our own AI estimate (`bulk_market_items.grade`), which  carries an explicit \"not a professional grade\" disclaimer.    `gradeKey` is the canonical form from `gradeKey()` in  shared/constants/graders.ts; `grading` holds the full GradingInfo  including the cert number and whether a cert lookup verified it. */
    public var gradeKey: String?
    public var grading: ListListingsItemGrading?
    public var brand: String?
    public var size: String?
    /** Migration 0179 — see the matching fields on inventory_items above. */
    public var material: String?
    public var style: String?
    public var pattern: String?
    public var department: String?
    public var gender: String?
    public var itemType: String?
    public var sizeSystem: String?
    public var color: [String]
    public var tags: [String]
    public var sku: String?
    public var quantity: Double
    public var quantityAvailable: Double
    public var weightLb: String?
    public var weightOz: String?
    public var dimensionLIn: String?
    public var dimensionWIn: String?
    public var dimensionHIn: String?
    /** Scheduled go-live time. When set on a draft, the listing-scheduler  worker waits until this passes then dispatches the crosspost to  scheduledPlatforms and flips status from 'draft' to 'active'. */
    public var publishAt: Date?
    /** Which platforms to publish to when publishAt fires. JSON array of  platform ids. Null/empty = scheduler skips (listing won't auto-  publish, even after publishAt — gives the seller an escape hatch). */
    public var scheduledPlatforms: [String]?
    /** Parent listing when this row is a CHILD in a listing chain. Null =  standalone. What being a child means depends on the parent's  `groupKind` — see it. */
    public var parentListingId: String?
    public var isBundle: Bool
    /** Per-listing automation overrides. See migration 0098.     automationAssignedRuleIds  — force-include for these rules   automationBlockedRuleIds   — exempt from these rules   automationAssignedChainIds — force-include for these workflow chains   automationBlockedChainIds  — exempt from these workflow chains */
    public var automationAssignedRuleIds: [String]
    public var automationBlockedRuleIds: [String]
    public var automationAssignedChainIds: [String]
    public var automationBlockedChainIds: [String]
    /** Harmonised System customs code — international shipping declarations. */
    public var hsCode: String?
    /** Customs country of origin. Distinct from the seller's location. */
    public var countryOfOrigin: String?
    /** Never let a repricing rule go below this. On the ITEM because it is a  fact about the thing owned, not about any one rule — \"this jacket never  goes below $45\" should apply to every rule, and before this it was  expressible only as one rule per jacket. Listings inherit when null. */
    public var priceFloorCents: Double?
    /** When true the floor is a TAKE-HOME target, converted to a per-platform  gross at reprice time. A gross floor is four different promises across  four platforms; this is the one number a seller actually cares about. */
    public var floorIsNet: Bool
    public var delistedAt: Date?
    public var soldAt: Date?
    /** Mirrors inventory_items.source. 'manual' for every seller-created  listing; external-stub.ts sets 'external_sale' on the synthetic  listing it fabricates for a sale detected on a platform id Crossly  never listed — those rows have no real photos/description of their  own (everything is lifted from the platform's sale payload) and are  otherwise indistinguishable from a real listing in the UI. */
    public var source: String
    /** Set when import's bin-packing (see _import-one.ts) created THIS  listing to hold a same-platform straggler it couldn't fit onto an  existing candidate listing for the same physical item — points at  the primary/first candidate. Purely informational: this listing  is a real, independently listable/delistable row, not a shadow.  Null for every ordinarily-created listing. */
    public var duplicateOfListingId: String?
    /** UUID minted on a seller's machine for a draft written offline.    The idempotency key for desktop sync. The failure it guards is a POST  that succeeds server-side whose reply is lost — the client cannot tell  that from a failure, retries, and one item becomes two live listings  against one piece of stock. Unique per user (partial index, migration  0268); null for every listing that did not come from an offline draft. */
    public var clientDraftId: String?
    public var createdAt: Date
    public var updatedAt: Date

    public init(effectiveTitle: String, effectivePrice: String? = nil, effectiveDescription: String? = nil, effectiveImages: [String], effectiveBrand: String? = nil, effectiveCondition: String? = nil, effectiveSize: String? = nil, effectiveSku: String? = nil, effectiveColor: [String], effectiveTags: [String], platformListings: [AnyCodable], inventoryItemId: String? = nil, id: String, userId: String, name: String? = nil, title: String? = nil, description: String? = nil, descriptionHtml: String? = nil, price: String? = nil, images: [String]? = nil, videoUrl: String? = nil, status: String, condition: String? = nil, gradeKey: String? = nil, grading: ListListingsItemGrading? = nil, brand: String? = nil, size: String? = nil, material: String? = nil, style: String? = nil, pattern: String? = nil, department: String? = nil, gender: String? = nil, itemType: String? = nil, sizeSystem: String? = nil, color: [String], tags: [String], sku: String? = nil, quantity: Double, quantityAvailable: Double, weightLb: String? = nil, weightOz: String? = nil, dimensionLIn: String? = nil, dimensionWIn: String? = nil, dimensionHIn: String? = nil, publishAt: Date? = nil, scheduledPlatforms: [String]? = nil, parentListingId: String? = nil, isBundle: Bool, automationAssignedRuleIds: [String], automationBlockedRuleIds: [String], automationAssignedChainIds: [String], automationBlockedChainIds: [String], hsCode: String? = nil, countryOfOrigin: String? = nil, priceFloorCents: Double? = nil, floorIsNet: Bool, delistedAt: Date? = nil, soldAt: Date? = nil, source: String, duplicateOfListingId: String? = nil, clientDraftId: String? = nil, createdAt: Date, updatedAt: Date) {
        self.effectiveTitle = effectiveTitle
        self.effectivePrice = effectivePrice
        self.effectiveDescription = effectiveDescription
        self.effectiveImages = effectiveImages
        self.effectiveBrand = effectiveBrand
        self.effectiveCondition = effectiveCondition
        self.effectiveSize = effectiveSize
        self.effectiveSku = effectiveSku
        self.effectiveColor = effectiveColor
        self.effectiveTags = effectiveTags
        self.platformListings = platformListings
        self.inventoryItemId = inventoryItemId
        self.id = id
        self.userId = userId
        self.name = name
        self.title = title
        self.description = description
        self.descriptionHtml = descriptionHtml
        self.price = price
        self.images = images
        self.videoUrl = videoUrl
        self.status = status
        self.condition = condition
        self.gradeKey = gradeKey
        self.grading = grading
        self.brand = brand
        self.size = size
        self.material = material
        self.style = style
        self.pattern = pattern
        self.department = department
        self.gender = gender
        self.itemType = itemType
        self.sizeSystem = sizeSystem
        self.color = color
        self.tags = tags
        self.sku = sku
        self.quantity = quantity
        self.quantityAvailable = quantityAvailable
        self.weightLb = weightLb
        self.weightOz = weightOz
        self.dimensionLIn = dimensionLIn
        self.dimensionWIn = dimensionWIn
        self.dimensionHIn = dimensionHIn
        self.publishAt = publishAt
        self.scheduledPlatforms = scheduledPlatforms
        self.parentListingId = parentListingId
        self.isBundle = isBundle
        self.automationAssignedRuleIds = automationAssignedRuleIds
        self.automationBlockedRuleIds = automationBlockedRuleIds
        self.automationAssignedChainIds = automationAssignedChainIds
        self.automationBlockedChainIds = automationBlockedChainIds
        self.hsCode = hsCode
        self.countryOfOrigin = countryOfOrigin
        self.priceFloorCents = priceFloorCents
        self.floorIsNet = floorIsNet
        self.delistedAt = delistedAt
        self.soldAt = soldAt
        self.source = source
        self.duplicateOfListingId = duplicateOfListingId
        self.clientDraftId = clientDraftId
        self.createdAt = createdAt
        self.updatedAt = updatedAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case effectiveTitle
        case effectivePrice
        case effectiveDescription
        case effectiveImages
        case effectiveBrand
        case effectiveCondition
        case effectiveSize
        case effectiveSku
        case effectiveColor
        case effectiveTags
        case platformListings
        case inventoryItemId
        case id
        case userId
        case name
        case title
        case description
        case descriptionHtml
        case price
        case images
        case videoUrl
        case status
        case condition
        case gradeKey
        case grading
        case brand
        case size
        case material
        case style
        case pattern
        case department
        case gender
        case itemType
        case sizeSystem
        case color
        case tags
        case sku
        case quantity
        case quantityAvailable
        case weightLb
        case weightOz
        case dimensionLIn
        case dimensionWIn
        case dimensionHIn
        case publishAt
        case scheduledPlatforms
        case parentListingId
        case isBundle
        case automationAssignedRuleIds
        case automationBlockedRuleIds
        case automationAssignedChainIds
        case automationBlockedChainIds
        case hsCode
        case countryOfOrigin
        case priceFloorCents
        case floorIsNet
        case delistedAt
        case soldAt
        case source
        case duplicateOfListingId
        case clientDraftId
        case createdAt
        case updatedAt
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(effectiveTitle, forKey: .effectiveTitle)
        try container.encodeIfPresent(effectivePrice, forKey: .effectivePrice)
        try container.encodeIfPresent(effectiveDescription, forKey: .effectiveDescription)
        try container.encode(effectiveImages, forKey: .effectiveImages)
        try container.encodeIfPresent(effectiveBrand, forKey: .effectiveBrand)
        try container.encodeIfPresent(effectiveCondition, forKey: .effectiveCondition)
        try container.encodeIfPresent(effectiveSize, forKey: .effectiveSize)
        try container.encodeIfPresent(effectiveSku, forKey: .effectiveSku)
        try container.encode(effectiveColor, forKey: .effectiveColor)
        try container.encode(effectiveTags, forKey: .effectiveTags)
        try container.encode(platformListings, forKey: .platformListings)
        try container.encodeIfPresent(inventoryItemId, forKey: .inventoryItemId)
        try container.encode(id, forKey: .id)
        try container.encode(userId, forKey: .userId)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(title, forKey: .title)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encodeIfPresent(descriptionHtml, forKey: .descriptionHtml)
        try container.encodeIfPresent(price, forKey: .price)
        try container.encodeIfPresent(images, forKey: .images)
        try container.encodeIfPresent(videoUrl, forKey: .videoUrl)
        try container.encode(status, forKey: .status)
        try container.encodeIfPresent(condition, forKey: .condition)
        try container.encodeIfPresent(gradeKey, forKey: .gradeKey)
        try container.encodeIfPresent(grading, forKey: .grading)
        try container.encodeIfPresent(brand, forKey: .brand)
        try container.encodeIfPresent(size, forKey: .size)
        try container.encodeIfPresent(material, forKey: .material)
        try container.encodeIfPresent(style, forKey: .style)
        try container.encodeIfPresent(pattern, forKey: .pattern)
        try container.encodeIfPresent(department, forKey: .department)
        try container.encodeIfPresent(gender, forKey: .gender)
        try container.encodeIfPresent(itemType, forKey: .itemType)
        try container.encodeIfPresent(sizeSystem, forKey: .sizeSystem)
        try container.encode(color, forKey: .color)
        try container.encode(tags, forKey: .tags)
        try container.encodeIfPresent(sku, forKey: .sku)
        try container.encode(quantity, forKey: .quantity)
        try container.encode(quantityAvailable, forKey: .quantityAvailable)
        try container.encodeIfPresent(weightLb, forKey: .weightLb)
        try container.encodeIfPresent(weightOz, forKey: .weightOz)
        try container.encodeIfPresent(dimensionLIn, forKey: .dimensionLIn)
        try container.encodeIfPresent(dimensionWIn, forKey: .dimensionWIn)
        try container.encodeIfPresent(dimensionHIn, forKey: .dimensionHIn)
        try container.encodeIfPresent(publishAt, forKey: .publishAt)
        try container.encodeIfPresent(scheduledPlatforms, forKey: .scheduledPlatforms)
        try container.encodeIfPresent(parentListingId, forKey: .parentListingId)
        try container.encode(isBundle, forKey: .isBundle)
        try container.encode(automationAssignedRuleIds, forKey: .automationAssignedRuleIds)
        try container.encode(automationBlockedRuleIds, forKey: .automationBlockedRuleIds)
        try container.encode(automationAssignedChainIds, forKey: .automationAssignedChainIds)
        try container.encode(automationBlockedChainIds, forKey: .automationBlockedChainIds)
        try container.encodeIfPresent(hsCode, forKey: .hsCode)
        try container.encodeIfPresent(countryOfOrigin, forKey: .countryOfOrigin)
        try container.encodeIfPresent(priceFloorCents, forKey: .priceFloorCents)
        try container.encode(floorIsNet, forKey: .floorIsNet)
        try container.encodeIfPresent(delistedAt, forKey: .delistedAt)
        try container.encodeIfPresent(soldAt, forKey: .soldAt)
        try container.encode(source, forKey: .source)
        try container.encodeIfPresent(duplicateOfListingId, forKey: .duplicateOfListingId)
        try container.encodeIfPresent(clientDraftId, forKey: .clientDraftId)
        try container.encode(createdAt, forKey: .createdAt)
        try container.encode(updatedAt, forKey: .updatedAt)
    }
}

