//
// CreateAutomationRuleValidateRecipeResponseDetailsFieldErrors.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CreateAutomationRuleValidateRecipeResponseDetailsFieldErrors: Codable, JSONEncodable, Hashable {

    public var name: [String]?
    public var condition: [String]?
    public var action: [String]?
    public var metadata: [String]?
    public var description: [String]?
    public var platforms: [String]?
    public var trigger: [String]?
    public var schema: [String]?
    public var schemaVersion: [String]?
    public var exportedAt: [String]?
    public var recipes: [String]?

    public init(name: [String]? = nil, condition: [String]? = nil, action: [String]? = nil, metadata: [String]? = nil, description: [String]? = nil, platforms: [String]? = nil, trigger: [String]? = nil, schema: [String]? = nil, schemaVersion: [String]? = nil, exportedAt: [String]? = nil, recipes: [String]? = nil) {
        self.name = name
        self.condition = condition
        self.action = action
        self.metadata = metadata
        self.description = description
        self.platforms = platforms
        self.trigger = trigger
        self.schema = schema
        self.schemaVersion = schemaVersion
        self.exportedAt = exportedAt
        self.recipes = recipes
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case condition
        case action
        case metadata
        case description
        case platforms
        case trigger
        case schema = "$schema"
        case schemaVersion
        case exportedAt
        case recipes
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(condition, forKey: .condition)
        try container.encodeIfPresent(action, forKey: .action)
        try container.encodeIfPresent(metadata, forKey: .metadata)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encodeIfPresent(platforms, forKey: .platforms)
        try container.encodeIfPresent(trigger, forKey: .trigger)
        try container.encodeIfPresent(schema, forKey: .schema)
        try container.encodeIfPresent(schemaVersion, forKey: .schemaVersion)
        try container.encodeIfPresent(exportedAt, forKey: .exportedAt)
        try container.encodeIfPresent(recipes, forKey: .recipes)
    }
}

