//
// CreateListingImportByUrlResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CreateListingImportByUrlResponse: Codable, JSONEncodable, Hashable {

    public var outcome: String
    public var listing: CreateListingImportByUrlResponseListing?

    public init(outcome: String, listing: CreateListingImportByUrlResponseListing? = nil) {
        self.outcome = outcome
        self.listing = listing
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case outcome
        case listing
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(outcome, forKey: .outcome)
        try container.encodeIfPresent(listing, forKey: .listing)
    }
}

