//
// CreateCbxSubjectSpendPlanResponseLegs.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CreateCbxSubjectSpendPlanResponseLegs: Codable, JSONEncodable, Hashable {

    public enum Source: String, Codable, CaseIterable {
        case connected = "connected"
        case granted = "granted"
        case earned = "earned"
    }
    public var source: Source
    public var baseUnits: String

    public init(source: Source, baseUnits: String) {
        self.source = source
        self.baseUnits = baseUnits
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case source
        case baseUnits
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(source, forKey: .source)
        try container.encode(baseUnits, forKey: .baseUnits)
    }
}

