//
// CreateMagicScanResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CreateMagicScanResponse: Codable, JSONEncodable, Hashable {

    public var runId: String
    public var ebayMatch: CreateMagicScanResponseEbayMatch?
    /** Unified top-10-globally list, ranked by CLIP visual similarity to  the seller's source photo. Each hit carries its origin platform. */
    public var topHits: [CreateMagicScanResponseTopHits]
    /** Legacy compat — UI's existing render. ebayHits now == visually-  validated eBay subset; otherMatches is re-grouped from topHits. */
    public var ebayHits: [CreateMagicScanResponseEbayHits]
    public var otherMatches: AnyCodable
    /** Every photo the seller uploaded for this scan, primary first. */
    public var imageUrls: [String]
    /** Vision-LLM aspects extracted across all photos. Populated only  when the seller has magic-list-vision-aspects enabled + a vision  provider configured. Empty otherwise. */
    public var visionAspects: AnyCodable
    /** The seller's OWN listings/inventory that this scan probably duplicates  (image + fuzzy-title self-dedup). Empty when nothing matched. Drives the  \"you may already have this\" prompt. */
    public var possibleDuplicates: [CreateMagicScanResponsePossibleDuplicates]
    public var cached: Bool

    public init(runId: String, ebayMatch: CreateMagicScanResponseEbayMatch? = nil, topHits: [CreateMagicScanResponseTopHits], ebayHits: [CreateMagicScanResponseEbayHits], otherMatches: AnyCodable, imageUrls: [String], visionAspects: AnyCodable, possibleDuplicates: [CreateMagicScanResponsePossibleDuplicates], cached: Bool) {
        self.runId = runId
        self.ebayMatch = ebayMatch
        self.topHits = topHits
        self.ebayHits = ebayHits
        self.otherMatches = otherMatches
        self.imageUrls = imageUrls
        self.visionAspects = visionAspects
        self.possibleDuplicates = possibleDuplicates
        self.cached = cached
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case runId
        case ebayMatch
        case topHits
        case ebayHits
        case otherMatches
        case imageUrls
        case visionAspects
        case possibleDuplicates
        case cached
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(runId, forKey: .runId)
        try container.encodeIfPresent(ebayMatch, forKey: .ebayMatch)
        try container.encode(topHits, forKey: .topHits)
        try container.encode(ebayHits, forKey: .ebayHits)
        try container.encode(otherMatches, forKey: .otherMatches)
        try container.encode(imageUrls, forKey: .imageUrls)
        try container.encode(visionAspects, forKey: .visionAspects)
        try container.encode(possibleDuplicates, forKey: .possibleDuplicates)
        try container.encode(cached, forKey: .cached)
    }
}

