//
// CreateMeTemplateImportResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CreateMeTemplateImportResponse: Codable, JSONEncodable, Hashable {

    public var imported: Double
    public var skipped: Double
    public var ids: [String]

    public init(imported: Double, skipped: Double, ids: [String]) {
        self.imported = imported
        self.skipped = skipped
        self.ids = ids
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case imported
        case skipped
        case ids
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(imported, forKey: .imported)
        try container.encode(skipped, forKey: .skipped)
        try container.encode(ids, forKey: .ids)
    }
}

