//
// CreateAiGenerateListingResponsePriceRange.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CreateAiGenerateListingResponsePriceRange: Codable, JSONEncodable, Hashable {

    public var value: CreateAiGenerateListingResponsePriceRangeValue
    public var confidence: Double

    public init(value: CreateAiGenerateListingResponsePriceRangeValue, confidence: Double) {
        self.value = value
        self.confidence = confidence
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case value
        case confidence
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(value, forKey: .value)
        try container.encode(confidence, forKey: .confidence)
    }
}

