//
// CreateCbxSubjectResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CreateCbxSubjectResponse: Codable, JSONEncodable, Hashable {

    public var subjectId: String
    public var externalUserId: String
    public var createdAt: Date

    public init(subjectId: String, externalUserId: String, createdAt: Date) {
        self.subjectId = subjectId
        self.externalUserId = externalUserId
        self.createdAt = createdAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case subjectId
        case externalUserId
        case createdAt
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(subjectId, forKey: .subjectId)
        try container.encode(externalUserId, forKey: .externalUserId)
        try container.encode(createdAt, forKey: .createdAt)
    }
}

