//
// CreateBuyerCheckoutResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CreateBuyerCheckoutResponse: Codable, JSONEncodable, Hashable {

    public var listingSlug: String
    public var quantity: Double
    public var totalCents: Double
    public var currency: String
    public var paymentStatus: String
    public var paymentIntentId: String?
    public var orderId: String?

    public init(listingSlug: String, quantity: Double, totalCents: Double, currency: String, paymentStatus: String, paymentIntentId: String? = nil, orderId: String? = nil) {
        self.listingSlug = listingSlug
        self.quantity = quantity
        self.totalCents = totalCents
        self.currency = currency
        self.paymentStatus = paymentStatus
        self.paymentIntentId = paymentIntentId
        self.orderId = orderId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case listingSlug
        case quantity
        case totalCents
        case currency
        case paymentStatus
        case paymentIntentId
        case orderId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(listingSlug, forKey: .listingSlug)
        try container.encode(quantity, forKey: .quantity)
        try container.encode(totalCents, forKey: .totalCents)
        try container.encode(currency, forKey: .currency)
        try container.encode(paymentStatus, forKey: .paymentStatus)
        try container.encodeIfPresent(paymentIntentId, forKey: .paymentIntentId)
        try container.encodeIfPresent(orderId, forKey: .orderId)
    }
}

