//
// CreateOrderLabelResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CreateOrderLabelResponse: Codable, JSONEncodable, Hashable {

    public var trackingNumber: String?
    public var labelUrl: String?
    public var carrier: String?
    public var service: String?

    public init(trackingNumber: String? = nil, labelUrl: String? = nil, carrier: String? = nil, service: String? = nil) {
        self.trackingNumber = trackingNumber
        self.labelUrl = labelUrl
        self.carrier = carrier
        self.service = service
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case trackingNumber
        case labelUrl
        case carrier
        case service
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(trackingNumber, forKey: .trackingNumber)
        try container.encodeIfPresent(labelUrl, forKey: .labelUrl)
        try container.encodeIfPresent(carrier, forKey: .carrier)
        try container.encodeIfPresent(service, forKey: .service)
    }
}

