//
// CreateInventoryBulkDeleteResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CreateInventoryBulkDeleteResponse: Codable, JSONEncodable, Hashable {

    public var success: Bool
    public var deleted: Double
    public var bulkJobId: String

    public init(success: Bool, deleted: Double, bulkJobId: String) {
        self.success = success
        self.deleted = deleted
        self.bulkJobId = bulkJobId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case success
        case deleted
        case bulkJobId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(success, forKey: .success)
        try container.encode(deleted, forKey: .deleted)
        try container.encode(bulkJobId, forKey: .bulkJobId)
    }
}

