//
// CreatePatResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CreatePatResponse: Codable, JSONEncodable, Hashable {

    public enum Environment: String, Codable, CaseIterable {
        case live = "live"
        case test = "test"
    }
    public var id: String
    public var _prefix: String
    public var token: String
    public var name: String
    public var scopes: [String]
    public var environment: Environment

    public init(id: String, _prefix: String, token: String, name: String, scopes: [String], environment: Environment) {
        self.id = id
        self._prefix = _prefix
        self.token = token
        self.name = name
        self.scopes = scopes
        self.environment = environment
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case _prefix = "prefix"
        case token
        case name
        case scopes
        case environment
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(_prefix, forKey: ._prefix)
        try container.encode(token, forKey: .token)
        try container.encode(name, forKey: .name)
        try container.encode(scopes, forKey: .scopes)
        try container.encode(environment, forKey: .environment)
    }
}

