//
// CreateTeamInviteResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CreateTeamInviteResponse: Codable, JSONEncodable, Hashable {

    public enum Role: String, Codable, CaseIterable {
        case va = "va"
        case admin = "admin"
    }
    public var id: String
    public var inviteeEmail: String
    public var role: Role
    public var scopes: [String]
    public var expiresAt: String
    public var acceptUrl: String

    public init(id: String, inviteeEmail: String, role: Role, scopes: [String], expiresAt: String, acceptUrl: String) {
        self.id = id
        self.inviteeEmail = inviteeEmail
        self.role = role
        self.scopes = scopes
        self.expiresAt = expiresAt
        self.acceptUrl = acceptUrl
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case inviteeEmail
        case role
        case scopes
        case expiresAt
        case acceptUrl
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(inviteeEmail, forKey: .inviteeEmail)
        try container.encode(role, forKey: .role)
        try container.encode(scopes, forKey: .scopes)
        try container.encode(expiresAt, forKey: .expiresAt)
        try container.encode(acceptUrl, forKey: .acceptUrl)
    }
}

