//
// DeleteMobilePushTokenResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct DeleteMobilePushTokenResponse: Codable, JSONEncodable, Hashable {

    public var ok: Bool
    public var removed: Double

    public init(ok: Bool, removed: Double) {
        self.ok = ok
        self.removed = removed
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case ok
        case removed
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(ok, forKey: .ok)
        try container.encode(removed, forKey: .removed)
    }
}

