//
// GetAnalyticTimeseryResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GetAnalyticTimeseryResponse: Codable, JSONEncodable, Hashable {

    public var days: Double
    public var series: [GetAnalyticTimeseryResponseSeries]

    public init(days: Double, series: [GetAnalyticTimeseryResponseSeries]) {
        self.days = days
        self.series = series
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case days
        case series
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(days, forKey: .days)
        try container.encode(series, forKey: .series)
    }
}

