//
// GetAnalyticDashboardResponseSellThrough.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** The context the bare rate can&#39;t carry. &#x60;tooYoungToJudge&#x60; is the  important one: a cohort measured the day its window closed has had no  time to sell, and a low number there means \&quot;wait\&quot;, not \&quot;bad buys\&quot; — a  seller acting on it would stop sourcing for no reason. */
public struct GetAnalyticDashboardResponseSellThrough: Codable, JSONEncodable, Hashable {

    public var rate: Double?
    public var cohortSize: Double
    public var cohortSold: Double
    public var maturityDays: Double
    public var tooYoungToJudge: Bool

    public init(rate: Double? = nil, cohortSize: Double, cohortSold: Double, maturityDays: Double, tooYoungToJudge: Bool) {
        self.rate = rate
        self.cohortSize = cohortSize
        self.cohortSold = cohortSold
        self.maturityDays = maturityDays
        self.tooYoungToJudge = tooYoungToJudge
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case rate
        case cohortSize
        case cohortSold
        case maturityDays
        case tooYoungToJudge
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(rate, forKey: .rate)
        try container.encode(cohortSize, forKey: .cohortSize)
        try container.encode(cohortSold, forKey: .cohortSold)
        try container.encode(maturityDays, forKey: .maturityDays)
        try container.encode(tooYoungToJudge, forKey: .tooYoungToJudge)
    }
}

