//
// GetAutomationCatalogResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GetAutomationCatalogResponse: Codable, JSONEncodable, Hashable {

    public var triggerTypes: [GetAutomationCatalogResponseTriggerTypes]
    public var actionTypes: [GetAutomationCatalogResponseTriggerTypes]
    public var conditionTypes: [GetAutomationCatalogResponseTriggerTypes]

    public init(triggerTypes: [GetAutomationCatalogResponseTriggerTypes], actionTypes: [GetAutomationCatalogResponseTriggerTypes], conditionTypes: [GetAutomationCatalogResponseTriggerTypes]) {
        self.triggerTypes = triggerTypes
        self.actionTypes = actionTypes
        self.conditionTypes = conditionTypes
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case triggerTypes
        case actionTypes
        case conditionTypes
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(triggerTypes, forKey: .triggerTypes)
        try container.encode(actionTypes, forKey: .actionTypes)
        try container.encode(conditionTypes, forKey: .conditionTypes)
    }
}

