//
// GetAdOffsiteReportResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GetAdOffsiteReportResponse: Codable, JSONEncodable, Hashable {

    public var spendCents: Double
    public var mediaCostCents: Double
    public var managementFeeCents: Double
    public var impressions: Double
    public var clicks: Double
    public var conversions: Double
    public var attributedRevenueCents: Double
    public var spilloverConversions: Double
    public var spilloverRevenueCents: Double
    public var returnBps: Double
    public var enabled: Bool
    public var autoPausedAt: String?
    public var autoPausedReason: String?

    public init(spendCents: Double, mediaCostCents: Double, managementFeeCents: Double, impressions: Double, clicks: Double, conversions: Double, attributedRevenueCents: Double, spilloverConversions: Double, spilloverRevenueCents: Double, returnBps: Double, enabled: Bool, autoPausedAt: String? = nil, autoPausedReason: String? = nil) {
        self.spendCents = spendCents
        self.mediaCostCents = mediaCostCents
        self.managementFeeCents = managementFeeCents
        self.impressions = impressions
        self.clicks = clicks
        self.conversions = conversions
        self.attributedRevenueCents = attributedRevenueCents
        self.spilloverConversions = spilloverConversions
        self.spilloverRevenueCents = spilloverRevenueCents
        self.returnBps = returnBps
        self.enabled = enabled
        self.autoPausedAt = autoPausedAt
        self.autoPausedReason = autoPausedReason
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case spendCents
        case mediaCostCents
        case managementFeeCents
        case impressions
        case clicks
        case conversions
        case attributedRevenueCents
        case spilloverConversions
        case spilloverRevenueCents
        case returnBps
        case enabled
        case autoPausedAt
        case autoPausedReason
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(spendCents, forKey: .spendCents)
        try container.encode(mediaCostCents, forKey: .mediaCostCents)
        try container.encode(managementFeeCents, forKey: .managementFeeCents)
        try container.encode(impressions, forKey: .impressions)
        try container.encode(clicks, forKey: .clicks)
        try container.encode(conversions, forKey: .conversions)
        try container.encode(attributedRevenueCents, forKey: .attributedRevenueCents)
        try container.encode(spilloverConversions, forKey: .spilloverConversions)
        try container.encode(spilloverRevenueCents, forKey: .spilloverRevenueCents)
        try container.encode(returnBps, forKey: .returnBps)
        try container.encode(enabled, forKey: .enabled)
        try container.encodeIfPresent(autoPausedAt, forKey: .autoPausedAt)
        try container.encodeIfPresent(autoPausedReason, forKey: .autoPausedReason)
    }
}

