//
// GetActionLogFacetResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GetActionLogFacetResponse: Codable, JSONEncodable, Hashable {

    public var platforms: [String]
    public var actions: [String]
    public var categories: [String]

    public init(platforms: [String], actions: [String], categories: [String]) {
        self.platforms = platforms
        self.actions = actions
        self.categories = categories
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case platforms
        case actions
        case categories
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(platforms, forKey: .platforms)
        try container.encode(actions, forKey: .actions)
        try container.encode(categories, forKey: .categories)
    }
}

