//
// GetAnalyticSummaryResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GetAnalyticSummaryResponse: Codable, JSONEncodable, Hashable {

    public var sales: Double
    public var revenue: Double
    public var fees: Double
    public var days: Double

    public init(sales: Double, revenue: Double, fees: Double, days: Double) {
        self.sales = sales
        self.revenue = revenue
        self.fees = fees
        self.days = days
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case sales
        case revenue
        case fees
        case days
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(sales, forKey: .sales)
        try container.encode(revenue, forKey: .revenue)
        try container.encode(fees, forKey: .fees)
        try container.encode(days, forKey: .days)
    }
}

