//
// GetAnalyticItemResponseItems.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GetAnalyticItemResponseItems: Codable, JSONEncodable, Hashable {

    public var saleId: String
    public var platform: String
    public var platformOrderId: String?
    public var itemTitle: String?
    public var itemBrand: String?
    public var itemSku: String?
    public var salePrice: Double?
    public var platformFee: Double?
    public var shippingCost: Double?
    public var costOfGoods: Double?
    public var netProfit: Double?
    public var marginPct: Double
    public var daysToSell: Double?
    public var detectedAt: Date

    public init(saleId: String, platform: String, platformOrderId: String? = nil, itemTitle: String? = nil, itemBrand: String? = nil, itemSku: String? = nil, salePrice: Double? = nil, platformFee: Double? = nil, shippingCost: Double? = nil, costOfGoods: Double? = nil, netProfit: Double? = nil, marginPct: Double, daysToSell: Double? = nil, detectedAt: Date) {
        self.saleId = saleId
        self.platform = platform
        self.platformOrderId = platformOrderId
        self.itemTitle = itemTitle
        self.itemBrand = itemBrand
        self.itemSku = itemSku
        self.salePrice = salePrice
        self.platformFee = platformFee
        self.shippingCost = shippingCost
        self.costOfGoods = costOfGoods
        self.netProfit = netProfit
        self.marginPct = marginPct
        self.daysToSell = daysToSell
        self.detectedAt = detectedAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case saleId
        case platform
        case platformOrderId
        case itemTitle
        case itemBrand
        case itemSku
        case salePrice
        case platformFee
        case shippingCost
        case costOfGoods
        case netProfit
        case marginPct
        case daysToSell
        case detectedAt
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(saleId, forKey: .saleId)
        try container.encode(platform, forKey: .platform)
        try container.encodeIfPresent(platformOrderId, forKey: .platformOrderId)
        try container.encodeIfPresent(itemTitle, forKey: .itemTitle)
        try container.encodeIfPresent(itemBrand, forKey: .itemBrand)
        try container.encodeIfPresent(itemSku, forKey: .itemSku)
        try container.encodeIfPresent(salePrice, forKey: .salePrice)
        try container.encodeIfPresent(platformFee, forKey: .platformFee)
        try container.encodeIfPresent(shippingCost, forKey: .shippingCost)
        try container.encodeIfPresent(costOfGoods, forKey: .costOfGoods)
        try container.encodeIfPresent(netProfit, forKey: .netProfit)
        try container.encode(marginPct, forKey: .marginPct)
        try container.encodeIfPresent(daysToSell, forKey: .daysToSell)
        try container.encode(detectedAt, forKey: .detectedAt)
    }
}

