//
// GetBuyerPreferenceResponsePriceBand.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** The band they actually shop in, from retail prices they were looking at. */
public struct GetBuyerPreferenceResponsePriceBand: Codable, JSONEncodable, Hashable {

    public var p25Cents: Double
    public var medianCents: Double
    public var p75Cents: Double

    public init(p25Cents: Double, medianCents: Double, p75Cents: Double) {
        self.p25Cents = p25Cents
        self.medianCents = medianCents
        self.p75Cents = p75Cents
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case p25Cents
        case medianCents
        case p75Cents
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(p25Cents, forKey: .p25Cents)
        try container.encode(medianCents, forKey: .medianCents)
        try container.encode(p75Cents, forKey: .p75Cents)
    }
}

