//
// GetBuyerAnywhereResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GetBuyerAnywhereResponse: Codable, JSONEncodable, Hashable {

    public enum Verdict: String, Codable, CaseIterable {
        case crosslyBest = "crossly_best"
        case offsiteCheaper = "offsite_cheaper"
        case offsiteOnly = "offsite_only"
        case noMatch = "no_match"
    }
    public var verdict: Verdict
    public var savingCents: Double?
    public var shippingUnknown: Bool
    public var crossly: GetBuyerAnywhereResponseCrossly?
    public var offsite: GetBuyerAnywhereResponseOffsite?
    public var alternates: [GetBuyerAnywhereResponseAlternates]

    public init(verdict: Verdict, savingCents: Double? = nil, shippingUnknown: Bool, crossly: GetBuyerAnywhereResponseCrossly? = nil, offsite: GetBuyerAnywhereResponseOffsite? = nil, alternates: [GetBuyerAnywhereResponseAlternates]) {
        self.verdict = verdict
        self.savingCents = savingCents
        self.shippingUnknown = shippingUnknown
        self.crossly = crossly
        self.offsite = offsite
        self.alternates = alternates
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case verdict
        case savingCents
        case shippingUnknown
        case crossly
        case offsite
        case alternates
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(verdict, forKey: .verdict)
        try container.encodeIfPresent(savingCents, forKey: .savingCents)
        try container.encode(shippingUnknown, forKey: .shippingUnknown)
        try container.encodeIfPresent(crossly, forKey: .crossly)
        try container.encodeIfPresent(offsite, forKey: .offsite)
        try container.encode(alternates, forKey: .alternates)
    }
}

