//
// GetBuyerPreferenceResponseBrands.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GetBuyerPreferenceResponseBrands: Codable, JSONEncodable, Hashable {

    public var brand: String
    public var looks: Double

    public init(brand: String, looks: Double) {
        self.brand = brand
        self.looks = looks
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case brand
        case looks
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(brand, forKey: .brand)
        try container.encode(looks, forKey: .looks)
    }
}

