//
// GetCustomerResponseContactAddress.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GetCustomerResponseContactAddress: Codable, JSONEncodable, Hashable {

    public var line1: String?
    public var line2: String?
    public var city: String?
    public var state: String?
    public var zip: String?
    public var country: String?

    public init(line1: String? = nil, line2: String? = nil, city: String? = nil, state: String? = nil, zip: String? = nil, country: String? = nil) {
        self.line1 = line1
        self.line2 = line2
        self.city = city
        self.state = state
        self.zip = zip
        self.country = country
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case line1
        case line2
        case city
        case state
        case zip
        case country
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(line1, forKey: .line1)
        try container.encodeIfPresent(line2, forKey: .line2)
        try container.encodeIfPresent(city, forKey: .city)
        try container.encodeIfPresent(state, forKey: .state)
        try container.encodeIfPresent(zip, forKey: .zip)
        try container.encodeIfPresent(country, forKey: .country)
    }
}

