//
// GetCbxRevenueResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GetCbxRevenueResponse: Codable, JSONEncodable, Hashable {

    public var accruedBaseUnits: String

    public init(accruedBaseUnits: String) {
        self.accruedBaseUnits = accruedBaseUnits
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case accruedBaseUnits
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(accruedBaseUnits, forKey: .accruedBaseUnits)
    }
}

