//
// GetConnectionHealthResponseAccounts.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GetConnectionHealthResponseAccounts: Codable, JSONEncodable, Hashable {

    public enum State: String, Codable, CaseIterable {
        case unknown = "unknown"
        case unmonitored = "unmonitored"
        case disconnected = "disconnected"
        case healthy = "healthy"
        case stale = "stale"
        case partialBlank = "partial_blank"
        case blankCredential = "blank_credential"
        case signedOut = "signed_out"
        case anchorDrift = "anchor_drift"
        case noCookies = "no_cookies"
    }
    public enum Severity: String, Codable, CaseIterable {
        case error = "error"
        case ok = "ok"
        case unknown = "unknown"
        case info = "info"
        case warn = "warn"
    }
    public enum Audience: String, Codable, CaseIterable {
        case seller = "seller"
        case crossly = "crossly"
        case nobody = "nobody"
    }
    public var platformName: String
    public var accountId: String?
    public var accountSlot: Double?
    public var label: String?
    public var platformUsername: String?
    /** Plain-English \"what is true\" + \"what to do\". Never empty. */
    public var summary: String
    public var action: String
    public var liveness: GetConnectionHealthResponseLiveness
    public var browser: GetConnectionHealthResponseBrowser?
    public var platform: String
    public var state: State
    public var severity: Severity
    public var audience: Audience
    public var anchors: GetConnectionHealthResponseAnchors?
    /** Secondary observations that do not change the verdict but change the debugging. Always safe to show; never the only thing shown. */
    public var notes: [String]

    public init(platformName: String, accountId: String? = nil, accountSlot: Double? = nil, label: String? = nil, platformUsername: String? = nil, summary: String, action: String, liveness: GetConnectionHealthResponseLiveness, browser: GetConnectionHealthResponseBrowser? = nil, platform: String, state: State, severity: Severity, audience: Audience, anchors: GetConnectionHealthResponseAnchors? = nil, notes: [String]) {
        self.platformName = platformName
        self.accountId = accountId
        self.accountSlot = accountSlot
        self.label = label
        self.platformUsername = platformUsername
        self.summary = summary
        self.action = action
        self.liveness = liveness
        self.browser = browser
        self.platform = platform
        self.state = state
        self.severity = severity
        self.audience = audience
        self.anchors = anchors
        self.notes = notes
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case platformName
        case accountId
        case accountSlot
        case label
        case platformUsername
        case summary
        case action
        case liveness
        case browser
        case platform
        case state
        case severity
        case audience
        case anchors
        case notes
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(platformName, forKey: .platformName)
        try container.encodeIfPresent(accountId, forKey: .accountId)
        try container.encodeIfPresent(accountSlot, forKey: .accountSlot)
        try container.encodeIfPresent(label, forKey: .label)
        try container.encodeIfPresent(platformUsername, forKey: .platformUsername)
        try container.encode(summary, forKey: .summary)
        try container.encode(action, forKey: .action)
        try container.encode(liveness, forKey: .liveness)
        try container.encodeIfPresent(browser, forKey: .browser)
        try container.encode(platform, forKey: .platform)
        try container.encode(state, forKey: .state)
        try container.encode(severity, forKey: .severity)
        try container.encode(audience, forKey: .audience)
        try container.encodeIfPresent(anchors, forKey: .anchors)
        try container.encode(notes, forKey: .notes)
    }
}

