//
// GetCustomerResponseOrders.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GetCustomerResponseOrders: Codable, JSONEncodable, Hashable {

    public var id: String
    public var platform: String
    public var platformOrderId: String?
    public var buyerUsername: String?
    public var status: String
    public var salePrice: String?
    public var createdAt: Date

    public init(id: String, platform: String, platformOrderId: String? = nil, buyerUsername: String? = nil, status: String, salePrice: String? = nil, createdAt: Date) {
        self.id = id
        self.platform = platform
        self.platformOrderId = platformOrderId
        self.buyerUsername = buyerUsername
        self.status = status
        self.salePrice = salePrice
        self.createdAt = createdAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case platform
        case platformOrderId
        case buyerUsername
        case status
        case salePrice
        case createdAt
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(platform, forKey: .platform)
        try container.encodeIfPresent(platformOrderId, forKey: .platformOrderId)
        try container.encodeIfPresent(buyerUsername, forKey: .buyerUsername)
        try container.encode(status, forKey: .status)
        try container.encodeIfPresent(salePrice, forKey: .salePrice)
        try container.encode(createdAt, forKey: .createdAt)
    }
}

