//
// GetConnectionHealthResponseBrowser.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** What the browser itself last reported, when it has reported at all. */
public struct GetConnectionHealthResponseBrowser: Codable, JSONEncodable, Hashable {

    public var observations: [AnyCodable]
    public var cookieCount: Double
    public var extensionVersion: String?
    public var observedAt: String
    public var observedAgo: String

    public init(observations: [AnyCodable], cookieCount: Double, extensionVersion: String? = nil, observedAt: String, observedAgo: String) {
        self.observations = observations
        self.cookieCount = cookieCount
        self.extensionVersion = extensionVersion
        self.observedAt = observedAt
        self.observedAgo = observedAgo
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case observations
        case cookieCount
        case extensionVersion
        case observedAt
        case observedAgo
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(observations, forKey: .observations)
        try container.encode(cookieCount, forKey: .cookieCount)
        try container.encodeIfPresent(extensionVersion, forKey: .extensionVersion)
        try container.encode(observedAt, forKey: .observedAt)
        try container.encode(observedAgo, forKey: .observedAgo)
    }
}

