//
// GetCategoryResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GetCategoryResponse: Codable, JSONEncodable, Hashable {

    public var main: GetCategoryResponseMain
    public var sub: AnyCodable

    public init(main: GetCategoryResponseMain, sub: AnyCodable) {
        self.main = main
        self.sub = sub
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case main
        case sub
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(main, forKey: .main)
        try container.encode(sub, forKey: .sub)
    }
}

