//
// GetNetworkPoolSizeResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GetNetworkPoolSizeResponse: Codable, JSONEncodable, Hashable {

    public var size: Double

    public init(size: Double) {
        self.size = size
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case size
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(size, forKey: .size)
    }
}

