//
// GetOfferResponseOffers.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GetOfferResponseOffers: Codable, JSONEncodable, Hashable {

    public var id: String
    public var status: String
    public var amountCents: Double
    /** Asking total when the offer was made — what the buyer responded to. */
    public var listedTotalCents: Double?
    public var isBundle: Bool
    public var items: [AnyCodable]
    public var message: String?
    public var parentOfferId: String?
    public var expiresAt: Date
    public var decidedAt: Date?
    /** Set once an accepted offer has actually been paid for. */
    public var consumedAt: Date?
    public var createdAt: Date

    public init(id: String, status: String, amountCents: Double, listedTotalCents: Double? = nil, isBundle: Bool, items: [AnyCodable], message: String? = nil, parentOfferId: String? = nil, expiresAt: Date, decidedAt: Date? = nil, consumedAt: Date? = nil, createdAt: Date) {
        self.id = id
        self.status = status
        self.amountCents = amountCents
        self.listedTotalCents = listedTotalCents
        self.isBundle = isBundle
        self.items = items
        self.message = message
        self.parentOfferId = parentOfferId
        self.expiresAt = expiresAt
        self.decidedAt = decidedAt
        self.consumedAt = consumedAt
        self.createdAt = createdAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case status
        case amountCents
        case listedTotalCents
        case isBundle
        case items
        case message
        case parentOfferId
        case expiresAt
        case decidedAt
        case consumedAt
        case createdAt
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(status, forKey: .status)
        try container.encode(amountCents, forKey: .amountCents)
        try container.encodeIfPresent(listedTotalCents, forKey: .listedTotalCents)
        try container.encode(isBundle, forKey: .isBundle)
        try container.encode(items, forKey: .items)
        try container.encodeIfPresent(message, forKey: .message)
        try container.encodeIfPresent(parentOfferId, forKey: .parentOfferId)
        try container.encode(expiresAt, forKey: .expiresAt)
        try container.encodeIfPresent(decidedAt, forKey: .decidedAt)
        try container.encodeIfPresent(consumedAt, forKey: .consumedAt)
        try container.encode(createdAt, forKey: .createdAt)
    }
}

