//
// GetOrderEvidenceResponseSealAssessment.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GetOrderEvidenceResponseSealAssessment: Codable, JSONEncodable, Hashable {

    public enum Verdict: String, Codable, CaseIterable {
        case opened = "opened"
        case intact = "intact"
        case suspect = "suspect"
        case unknown = "unknown"
    }
    public var verdict: Verdict
    public var reasons: [AnyCodable]
    /** One sentence for a human who will read nothing else. */
    public var headline: String

    public init(verdict: Verdict, reasons: [AnyCodable], headline: String) {
        self.verdict = verdict
        self.reasons = reasons
        self.headline = headline
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case verdict
        case reasons
        case headline
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(verdict, forKey: .verdict)
        try container.encode(reasons, forKey: .reasons)
        try container.encode(headline, forKey: .headline)
    }
}

