//
// GetOfferResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GetOfferResponse: Codable, JSONEncodable, Hashable {

    public var offers: [GetOfferResponseOffers]

    public init(offers: [GetOfferResponseOffers]) {
        self.offers = offers
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case offers
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(offers, forKey: .offers)
    }
}

