//
// GetPatScopeResponseScopes.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GetPatScopeResponseScopes: Codable, JSONEncodable, Hashable {

    public var id: String
    public var label: String
    public var description: String

    public init(id: String, label: String, description: String) {
        self.id = id
        self.label = label
        self.description = description
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case label
        case description
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(label, forKey: .label)
        try container.encode(description, forKey: .description)
    }
}

