//
// GetSpatialSceneResponseStats.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Totals the UI shows without recomputing over the payload. */
public struct GetSpatialSceneResponseStats: Codable, JSONEncodable, Hashable {

    public var itemCount: Double
    public var capitalCents: Double
    public var staleCount: Double
    public var unplaced: Double

    public init(itemCount: Double, capitalCents: Double, staleCount: Double, unplaced: Double) {
        self.itemCount = itemCount
        self.capitalCents = capitalCents
        self.staleCount = staleCount
        self.unplaced = unplaced
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case itemCount
        case capitalCents
        case staleCount
        case unplaced
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(itemCount, forKey: .itemCount)
        try container.encode(capitalCents, forKey: .capitalCents)
        try container.encode(staleCount, forKey: .staleCount)
        try container.encode(unplaced, forKey: .unplaced)
    }
}

