//
// GetSpatialPublicResponseSolvedPlacements.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GetSpatialPublicResponseSolvedPlacements: Codable, JSONEncodable, Hashable {

    public var itemId: String
    public var unitId: String?
    public var containerKey: String
    public var containerIndex: Double
    public var slotIndex: Double
    /** Local position inside the container, metres. */
    public var position: AnyCodable
    public var groupPath: [String]
    public var pinned: Bool

    public init(itemId: String, unitId: String? = nil, containerKey: String, containerIndex: Double, slotIndex: Double, position: AnyCodable, groupPath: [String], pinned: Bool) {
        self.itemId = itemId
        self.unitId = unitId
        self.containerKey = containerKey
        self.containerIndex = containerIndex
        self.slotIndex = slotIndex
        self.position = position
        self.groupPath = groupPath
        self.pinned = pinned
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case itemId
        case unitId
        case containerKey
        case containerIndex
        case slotIndex
        case position
        case groupPath
        case pinned
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(itemId, forKey: .itemId)
        try container.encodeIfPresent(unitId, forKey: .unitId)
        try container.encode(containerKey, forKey: .containerKey)
        try container.encode(containerIndex, forKey: .containerIndex)
        try container.encode(slotIndex, forKey: .slotIndex)
        try container.encode(position, forKey: .position)
        try container.encode(groupPath, forKey: .groupPath)
        try container.encode(pinned, forKey: .pinned)
    }
}

