//
// GetSpatialPublicResponseItems.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GetSpatialPublicResponseItems: Codable, JSONEncodable, Hashable {

    public var id: String
    public var title: String
    public var imageUrl: String?
    public var marketTagged: Bool

    public init(id: String, title: String, imageUrl: String? = nil, marketTagged: Bool) {
        self.id = id
        self.title = title
        self.imageUrl = imageUrl
        self.marketTagged = marketTagged
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case title
        case imageUrl
        case marketTagged
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(title, forKey: .title)
        try container.encodeIfPresent(imageUrl, forKey: .imageUrl)
        try container.encode(marketTagged, forKey: .marketTagged)
    }
}

