//
// GetSpatialPublicResponseScene.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GetSpatialPublicResponseScene: Codable, JSONEncodable, Hashable {

    public var name: String
    public var kind: String
    public var categorySlug: String?

    public init(name: String, kind: String, categorySlug: String? = nil) {
        self.name = name
        self.kind = kind
        self.categorySlug = categorySlug
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case kind
        case categorySlug
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(name, forKey: .name)
        try container.encode(kind, forKey: .kind)
        try container.encodeIfPresent(categorySlug, forKey: .categorySlug)
    }
}

