//
// GetTypeResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GetTypeResponse: Codable, JSONEncodable, Hashable {

    public var types: [String]

    public init(types: [String]) {
        self.types = types
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case types
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(types, forKey: .types)
    }
}

