//
// GetTaxonomyCategoryAspectResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GetTaxonomyCategoryAspectResponse: Codable, JSONEncodable, Hashable {

    public var aspects: [GetTaxonomyCategoryAspectResponseAspects]

    public init(aspects: [GetTaxonomyCategoryAspectResponseAspects]) {
        self.aspects = aspects
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case aspects
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(aspects, forKey: .aspects)
    }
}

