//
// GetTaxonomyCategoryResponseCategories.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GetTaxonomyCategoryResponseCategories: Codable, JSONEncodable, Hashable {

    public var id: String
    public var label: String
    public var leaf: Bool
    public var parentId: String?
    /** Root-first ancestor path including the leaf, when the caller supplied  it. Suggestions carry it; the tree walk does not. */
    public var path: String?

    public init(id: String, label: String, leaf: Bool, parentId: String? = nil, path: String? = nil) {
        self.id = id
        self.label = label
        self.leaf = leaf
        self.parentId = parentId
        self.path = path
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case label
        case leaf
        case parentId
        case path
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(label, forKey: .label)
        try container.encode(leaf, forKey: .leaf)
        try container.encodeIfPresent(parentId, forKey: .parentId)
        try container.encodeIfPresent(path, forKey: .path)
    }
}

