//
// GetTaxonomyCategoryChildrenResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GetTaxonomyCategoryChildrenResponse: Codable, JSONEncodable, Hashable {

    public var children: [GetTaxonomyCategoryResponseCategories]

    public init(children: [GetTaxonomyCategoryResponseCategories]) {
        self.children = children
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case children
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(children, forKey: .children)
    }
}

