//
// ListPolicyPresetsItem.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ListPolicyPresetsItem: Codable, JSONEncodable, Hashable {

    public var id: String
    public var name: String
    public var createdAt: Date
    public var updatedAt: Date
    public var userId: String
    public var isDefault: Bool
    public var kind: String

    public init(id: String, name: String, createdAt: Date, updatedAt: Date, userId: String, isDefault: Bool, kind: String) {
        self.id = id
        self.name = name
        self.createdAt = createdAt
        self.updatedAt = updatedAt
        self.userId = userId
        self.isDefault = isDefault
        self.kind = kind
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case name
        case createdAt
        case updatedAt
        case userId
        case isDefault
        case kind
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(name, forKey: .name)
        try container.encode(createdAt, forKey: .createdAt)
        try container.encode(updatedAt, forKey: .updatedAt)
        try container.encode(userId, forKey: .userId)
        try container.encode(isDefault, forKey: .isDefault)
        try container.encode(kind, forKey: .kind)
    }
}

