//
// ListInventoryItem.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ListInventoryItem: Codable, JSONEncodable, Hashable {

    public var id: String
    public var brand: String?
    public var createdAt: Date
    public var updatedAt: Date
    public var userId: String
    public var sku: String?
    public var quantity: Double
    public var quantityAvailable: Double
    public var quantityReserved: Double
    public var quantitySold: Double
    public var originalPrice: String?
    public var condition: String?
    public var size: String?
    public var material: String?
    public var style: String?
    public var pattern: String?
    public var department: String?
    public var gender: String?
    public var itemType: String?
    public var sizeSystem: String?
    public var color: [String]
    public var defaultTitle: String
    public var images: [String]
    public var videoUrl: String?
    public var tags: [String]
    public var labels: [String]
    public var notes: String?
    public var customLabel: String?
    public var warehouseLocation: String?
    public var storageBin: String?
    public var storageNote: String?
    public var marketSkuId: String?
    public var marketVariantId: String?
    public var firstListedAt: Date?
    public var includeTaxInLanded: Bool
    public var costBasisCents: Double?
    public var priceFloorCents: Double?
    public var floorIsNet: Bool
    public var acquiredAt: Date?
    public var acquiredSource: String?
    public var weightLb: String?
    public var weightOz: String?
    public var dimensionLIn: String?
    public var dimensionWIn: String?
    public var dimensionHIn: String?
    public var status: String
    public var source: String
    public var category: ListInventoryItemCategory?

    public init(id: String, brand: String? = nil, createdAt: Date, updatedAt: Date, userId: String, sku: String? = nil, quantity: Double, quantityAvailable: Double, quantityReserved: Double, quantitySold: Double, originalPrice: String? = nil, condition: String? = nil, size: String? = nil, material: String? = nil, style: String? = nil, pattern: String? = nil, department: String? = nil, gender: String? = nil, itemType: String? = nil, sizeSystem: String? = nil, color: [String], defaultTitle: String, images: [String], videoUrl: String? = nil, tags: [String], labels: [String], notes: String? = nil, customLabel: String? = nil, warehouseLocation: String? = nil, storageBin: String? = nil, storageNote: String? = nil, marketSkuId: String? = nil, marketVariantId: String? = nil, firstListedAt: Date? = nil, includeTaxInLanded: Bool, costBasisCents: Double? = nil, priceFloorCents: Double? = nil, floorIsNet: Bool, acquiredAt: Date? = nil, acquiredSource: String? = nil, weightLb: String? = nil, weightOz: String? = nil, dimensionLIn: String? = nil, dimensionWIn: String? = nil, dimensionHIn: String? = nil, status: String, source: String, category: ListInventoryItemCategory? = nil) {
        self.id = id
        self.brand = brand
        self.createdAt = createdAt
        self.updatedAt = updatedAt
        self.userId = userId
        self.sku = sku
        self.quantity = quantity
        self.quantityAvailable = quantityAvailable
        self.quantityReserved = quantityReserved
        self.quantitySold = quantitySold
        self.originalPrice = originalPrice
        self.condition = condition
        self.size = size
        self.material = material
        self.style = style
        self.pattern = pattern
        self.department = department
        self.gender = gender
        self.itemType = itemType
        self.sizeSystem = sizeSystem
        self.color = color
        self.defaultTitle = defaultTitle
        self.images = images
        self.videoUrl = videoUrl
        self.tags = tags
        self.labels = labels
        self.notes = notes
        self.customLabel = customLabel
        self.warehouseLocation = warehouseLocation
        self.storageBin = storageBin
        self.storageNote = storageNote
        self.marketSkuId = marketSkuId
        self.marketVariantId = marketVariantId
        self.firstListedAt = firstListedAt
        self.includeTaxInLanded = includeTaxInLanded
        self.costBasisCents = costBasisCents
        self.priceFloorCents = priceFloorCents
        self.floorIsNet = floorIsNet
        self.acquiredAt = acquiredAt
        self.acquiredSource = acquiredSource
        self.weightLb = weightLb
        self.weightOz = weightOz
        self.dimensionLIn = dimensionLIn
        self.dimensionWIn = dimensionWIn
        self.dimensionHIn = dimensionHIn
        self.status = status
        self.source = source
        self.category = category
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case brand
        case createdAt
        case updatedAt
        case userId
        case sku
        case quantity
        case quantityAvailable
        case quantityReserved
        case quantitySold
        case originalPrice
        case condition
        case size
        case material
        case style
        case pattern
        case department
        case gender
        case itemType
        case sizeSystem
        case color
        case defaultTitle
        case images
        case videoUrl
        case tags
        case labels
        case notes
        case customLabel
        case warehouseLocation
        case storageBin
        case storageNote
        case marketSkuId
        case marketVariantId
        case firstListedAt
        case includeTaxInLanded
        case costBasisCents
        case priceFloorCents
        case floorIsNet
        case acquiredAt
        case acquiredSource
        case weightLb
        case weightOz
        case dimensionLIn
        case dimensionWIn
        case dimensionHIn
        case status
        case source
        case category
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encodeIfPresent(brand, forKey: .brand)
        try container.encode(createdAt, forKey: .createdAt)
        try container.encode(updatedAt, forKey: .updatedAt)
        try container.encode(userId, forKey: .userId)
        try container.encodeIfPresent(sku, forKey: .sku)
        try container.encode(quantity, forKey: .quantity)
        try container.encode(quantityAvailable, forKey: .quantityAvailable)
        try container.encode(quantityReserved, forKey: .quantityReserved)
        try container.encode(quantitySold, forKey: .quantitySold)
        try container.encodeIfPresent(originalPrice, forKey: .originalPrice)
        try container.encodeIfPresent(condition, forKey: .condition)
        try container.encodeIfPresent(size, forKey: .size)
        try container.encodeIfPresent(material, forKey: .material)
        try container.encodeIfPresent(style, forKey: .style)
        try container.encodeIfPresent(pattern, forKey: .pattern)
        try container.encodeIfPresent(department, forKey: .department)
        try container.encodeIfPresent(gender, forKey: .gender)
        try container.encodeIfPresent(itemType, forKey: .itemType)
        try container.encodeIfPresent(sizeSystem, forKey: .sizeSystem)
        try container.encode(color, forKey: .color)
        try container.encode(defaultTitle, forKey: .defaultTitle)
        try container.encode(images, forKey: .images)
        try container.encodeIfPresent(videoUrl, forKey: .videoUrl)
        try container.encode(tags, forKey: .tags)
        try container.encode(labels, forKey: .labels)
        try container.encodeIfPresent(notes, forKey: .notes)
        try container.encodeIfPresent(customLabel, forKey: .customLabel)
        try container.encodeIfPresent(warehouseLocation, forKey: .warehouseLocation)
        try container.encodeIfPresent(storageBin, forKey: .storageBin)
        try container.encodeIfPresent(storageNote, forKey: .storageNote)
        try container.encodeIfPresent(marketSkuId, forKey: .marketSkuId)
        try container.encodeIfPresent(marketVariantId, forKey: .marketVariantId)
        try container.encodeIfPresent(firstListedAt, forKey: .firstListedAt)
        try container.encode(includeTaxInLanded, forKey: .includeTaxInLanded)
        try container.encodeIfPresent(costBasisCents, forKey: .costBasisCents)
        try container.encodeIfPresent(priceFloorCents, forKey: .priceFloorCents)
        try container.encode(floorIsNet, forKey: .floorIsNet)
        try container.encodeIfPresent(acquiredAt, forKey: .acquiredAt)
        try container.encodeIfPresent(acquiredSource, forKey: .acquiredSource)
        try container.encodeIfPresent(weightLb, forKey: .weightLb)
        try container.encodeIfPresent(weightOz, forKey: .weightOz)
        try container.encodeIfPresent(dimensionLIn, forKey: .dimensionLIn)
        try container.encodeIfPresent(dimensionWIn, forKey: .dimensionWIn)
        try container.encodeIfPresent(dimensionHIn, forKey: .dimensionHIn)
        try container.encode(status, forKey: .status)
        try container.encode(source, forKey: .source)
        try container.encodeIfPresent(category, forKey: .category)
    }
}

