//
// ListMarketVariantTiersItem.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ListMarketVariantTiersItem: Codable, JSONEncodable, Hashable {

    public var label: String
    public var condition: String
    /** null = ungraded, which is the tier every pre-grading order sits in. */
    public var gradeKey: String?
    public var lowestAskCents: Double?
    public var highestBidCents: Double?
    public var openAsks: Double
    public var openBids: Double
    public var lastSaleCents: Double?
    public var lastSaleAt: Date?
    public var tradesCount: Double

    public init(label: String, condition: String, gradeKey: String? = nil, lowestAskCents: Double? = nil, highestBidCents: Double? = nil, openAsks: Double, openBids: Double, lastSaleCents: Double? = nil, lastSaleAt: Date? = nil, tradesCount: Double) {
        self.label = label
        self.condition = condition
        self.gradeKey = gradeKey
        self.lowestAskCents = lowestAskCents
        self.highestBidCents = highestBidCents
        self.openAsks = openAsks
        self.openBids = openBids
        self.lastSaleCents = lastSaleCents
        self.lastSaleAt = lastSaleAt
        self.tradesCount = tradesCount
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case label
        case condition
        case gradeKey
        case lowestAskCents
        case highestBidCents
        case openAsks
        case openBids
        case lastSaleCents
        case lastSaleAt
        case tradesCount
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(label, forKey: .label)
        try container.encode(condition, forKey: .condition)
        try container.encodeIfPresent(gradeKey, forKey: .gradeKey)
        try container.encodeIfPresent(lowestAskCents, forKey: .lowestAskCents)
        try container.encodeIfPresent(highestBidCents, forKey: .highestBidCents)
        try container.encode(openAsks, forKey: .openAsks)
        try container.encode(openBids, forKey: .openBids)
        try container.encodeIfPresent(lastSaleCents, forKey: .lastSaleCents)
        try container.encodeIfPresent(lastSaleAt, forKey: .lastSaleAt)
        try container.encode(tradesCount, forKey: .tradesCount)
    }
}

