//
// ListCbxRedemptionServicesItem.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ListCbxRedemptionServicesItem: Codable, JSONEncodable, Hashable {

    public enum Label: String, Codable, CaseIterable {
        case cardSlashComicGradingSubmission = "Card / comic grading submission"
        case itemAuthentication = "Item authentication"
        case evidenceSealConditionProof = "Evidence seal (condition proof)"
        case crosslySubscription = "Crossly subscription"
    }
    public var serviceKind: String
    public var label: Label

    public init(serviceKind: String, label: Label) {
        self.serviceKind = serviceKind
        self.label = label
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case serviceKind
        case label
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(serviceKind, forKey: .serviceKind)
        try container.encode(label, forKey: .label)
    }
}

