//
// ListActionLogCallsItem.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ListActionLogCallsItem: Codable, JSONEncodable, Hashable {

    public var id: String
    public var createdAt: Date
    public var userId: String?
    public var platform: String
    public var action: String
    public var step: Double?
    public var url: String
    public var method: String
    public var statusCode: Double?
    public var latencyMs: Double?
    public var errorClass: String?
    public var errorMessage: String?
    public var requestBodyExcerpt: String?
    public var responseBodyExcerpt: String?
    public var recipeId: String?
    public var docIdOrHash: String?
    public var proxyId: String?
    public var correlationId: String
    public var actionEventId: String?
    public var ok: Bool

    public init(id: String, createdAt: Date, userId: String? = nil, platform: String, action: String, step: Double? = nil, url: String, method: String, statusCode: Double? = nil, latencyMs: Double? = nil, errorClass: String? = nil, errorMessage: String? = nil, requestBodyExcerpt: String? = nil, responseBodyExcerpt: String? = nil, recipeId: String? = nil, docIdOrHash: String? = nil, proxyId: String? = nil, correlationId: String, actionEventId: String? = nil, ok: Bool) {
        self.id = id
        self.createdAt = createdAt
        self.userId = userId
        self.platform = platform
        self.action = action
        self.step = step
        self.url = url
        self.method = method
        self.statusCode = statusCode
        self.latencyMs = latencyMs
        self.errorClass = errorClass
        self.errorMessage = errorMessage
        self.requestBodyExcerpt = requestBodyExcerpt
        self.responseBodyExcerpt = responseBodyExcerpt
        self.recipeId = recipeId
        self.docIdOrHash = docIdOrHash
        self.proxyId = proxyId
        self.correlationId = correlationId
        self.actionEventId = actionEventId
        self.ok = ok
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case createdAt
        case userId
        case platform
        case action
        case step
        case url
        case method
        case statusCode
        case latencyMs
        case errorClass
        case errorMessage
        case requestBodyExcerpt
        case responseBodyExcerpt
        case recipeId
        case docIdOrHash
        case proxyId
        case correlationId
        case actionEventId
        case ok
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(createdAt, forKey: .createdAt)
        try container.encodeIfPresent(userId, forKey: .userId)
        try container.encode(platform, forKey: .platform)
        try container.encode(action, forKey: .action)
        try container.encodeIfPresent(step, forKey: .step)
        try container.encode(url, forKey: .url)
        try container.encode(method, forKey: .method)
        try container.encodeIfPresent(statusCode, forKey: .statusCode)
        try container.encodeIfPresent(latencyMs, forKey: .latencyMs)
        try container.encodeIfPresent(errorClass, forKey: .errorClass)
        try container.encodeIfPresent(errorMessage, forKey: .errorMessage)
        try container.encodeIfPresent(requestBodyExcerpt, forKey: .requestBodyExcerpt)
        try container.encodeIfPresent(responseBodyExcerpt, forKey: .responseBodyExcerpt)
        try container.encodeIfPresent(recipeId, forKey: .recipeId)
        try container.encodeIfPresent(docIdOrHash, forKey: .docIdOrHash)
        try container.encodeIfPresent(proxyId, forKey: .proxyId)
        try container.encode(correlationId, forKey: .correlationId)
        try container.encodeIfPresent(actionEventId, forKey: .actionEventId)
        try container.encode(ok, forKey: .ok)
    }
}

