//
// ListMagicRecentItem.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ListMagicRecentItem: Codable, JSONEncodable, Hashable {

    public var id: String
    public var imageUrl: String
    public var createdAt: Date
    public var topMatchTitle: String
    public var matchCount: Double

    public init(id: String, imageUrl: String, createdAt: Date, topMatchTitle: String, matchCount: Double) {
        self.id = id
        self.imageUrl = imageUrl
        self.createdAt = createdAt
        self.topMatchTitle = topMatchTitle
        self.matchCount = matchCount
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case imageUrl
        case createdAt
        case topMatchTitle
        case matchCount
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(imageUrl, forKey: .imageUrl)
        try container.encode(createdAt, forKey: .createdAt)
        try container.encode(topMatchTitle, forKey: .topMatchTitle)
        try container.encode(matchCount, forKey: .matchCount)
    }
}

