//
// ListSpatialScenesItem.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ListSpatialScenesItem: Codable, JSONEncodable, Hashable {

    public var id: String
    public var kind: String
    public var name: String
    public var categorySlug: String?
    public var visibility: String
    public var publicSlug: String?
    public var updatedAt: Date

    public init(id: String, kind: String, name: String, categorySlug: String? = nil, visibility: String, publicSlug: String? = nil, updatedAt: Date) {
        self.id = id
        self.kind = kind
        self.name = name
        self.categorySlug = categorySlug
        self.visibility = visibility
        self.publicSlug = publicSlug
        self.updatedAt = updatedAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case kind
        case name
        case categorySlug
        case visibility
        case publicSlug
        case updatedAt
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(kind, forKey: .kind)
        try container.encode(name, forKey: .name)
        try container.encodeIfPresent(categorySlug, forKey: .categorySlug)
        try container.encode(visibility, forKey: .visibility)
        try container.encodeIfPresent(publicSlug, forKey: .publicSlug)
        try container.encode(updatedAt, forKey: .updatedAt)
    }
}

