//
// ListInventoryItemCategory.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ListInventoryItemCategory: Codable, JSONEncodable, Hashable {

    public var main: String?
    public var sub: String?

    public init(main: String? = nil, sub: String? = nil) {
        self.main = main
        self.sub = sub
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case main
        case sub
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(main, forKey: .main)
        try container.encodeIfPresent(sub, forKey: .sub)
    }
}

