//
// ListTaxonomySuggestItemCatalog.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ListTaxonomySuggestItemCatalog: Codable, JSONEncodable, Hashable {

    public var department: String
    public var category: String
    public var categoryFeatures: [String]

    public init(department: String, category: String, categoryFeatures: [String]) {
        self.department = department
        self.category = category
        self.categoryFeatures = categoryFeatures
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case department
        case category
        case categoryFeatures = "category_features"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(department, forKey: .department)
        try container.encode(category, forKey: .category)
        try container.encode(categoryFeatures, forKey: .categoryFeatures)
    }
}

