//
// ListCbxCampaignPayoutsItem.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ListCbxCampaignPayoutsItem: Codable, JSONEncodable, Hashable {

    public var subjectId: String
    public var weight: String
    public var baseUnits: String
    public var createdAt: Date

    public init(subjectId: String, weight: String, baseUnits: String, createdAt: Date) {
        self.subjectId = subjectId
        self.weight = weight
        self.baseUnits = baseUnits
        self.createdAt = createdAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case subjectId
        case weight
        case baseUnits
        case createdAt
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(subjectId, forKey: .subjectId)
        try container.encode(weight, forKey: .weight)
        try container.encode(baseUnits, forKey: .baseUnits)
        try container.encode(createdAt, forKey: .createdAt)
    }
}

