//
// ListCbxStakeTiersItem.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ListCbxStakeTiersItem: Codable, JSONEncodable, Hashable {

    public var slug: String
    public var label: String
    public var minBaseUnits: String
    public var feeDiscountBps: Double
    public var earnBoostBps: Double
    public var cooldownDays: Double

    public init(slug: String, label: String, minBaseUnits: String, feeDiscountBps: Double, earnBoostBps: Double, cooldownDays: Double) {
        self.slug = slug
        self.label = label
        self.minBaseUnits = minBaseUnits
        self.feeDiscountBps = feeDiscountBps
        self.earnBoostBps = earnBoostBps
        self.cooldownDays = cooldownDays
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case slug
        case label
        case minBaseUnits
        case feeDiscountBps
        case earnBoostBps
        case cooldownDays
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(slug, forKey: .slug)
        try container.encode(label, forKey: .label)
        try container.encode(minBaseUnits, forKey: .minBaseUnits)
        try container.encode(feeDiscountBps, forKey: .feeDiscountBps)
        try container.encode(earnBoostBps, forKey: .earnBoostBps)
        try container.encode(cooldownDays, forKey: .cooldownDays)
    }
}

