//
// ListConnectedAppsItem.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ListConnectedAppsItem: Codable, JSONEncodable, Hashable {

    public var grantId: String
    public var scopes: [String]
    public var connectedAt: Date
    public var lastUsedAt: Date?
    public var appId: String
    public var appName: String
    public var appDescription: String?
    public var homepageUrl: String?
    public var developerName: String?
    public var developerEmail: String

    public init(grantId: String, scopes: [String], connectedAt: Date, lastUsedAt: Date? = nil, appId: String, appName: String, appDescription: String? = nil, homepageUrl: String? = nil, developerName: String? = nil, developerEmail: String) {
        self.grantId = grantId
        self.scopes = scopes
        self.connectedAt = connectedAt
        self.lastUsedAt = lastUsedAt
        self.appId = appId
        self.appName = appName
        self.appDescription = appDescription
        self.homepageUrl = homepageUrl
        self.developerName = developerName
        self.developerEmail = developerEmail
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case grantId
        case scopes
        case connectedAt
        case lastUsedAt
        case appId
        case appName
        case appDescription
        case homepageUrl
        case developerName
        case developerEmail
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(grantId, forKey: .grantId)
        try container.encode(scopes, forKey: .scopes)
        try container.encode(connectedAt, forKey: .connectedAt)
        try container.encodeIfPresent(lastUsedAt, forKey: .lastUsedAt)
        try container.encode(appId, forKey: .appId)
        try container.encode(appName, forKey: .appName)
        try container.encodeIfPresent(appDescription, forKey: .appDescription)
        try container.encodeIfPresent(homepageUrl, forKey: .homepageUrl)
        try container.encodeIfPresent(developerName, forKey: .developerName)
        try container.encode(developerEmail, forKey: .developerEmail)
    }
}

