//
// ListBuyerWishlistItemsItem.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ListBuyerWishlistItemsItem: Codable, JSONEncodable, Hashable {

    public var id: String
    public var platformListingId: String
    public var addedAt: Date
    public var slug: String?
    public var title: String?

    public init(id: String, platformListingId: String, addedAt: Date, slug: String? = nil, title: String? = nil) {
        self.id = id
        self.platformListingId = platformListingId
        self.addedAt = addedAt
        self.slug = slug
        self.title = title
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case platformListingId
        case addedAt
        case slug
        case title
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(platformListingId, forKey: .platformListingId)
        try container.encode(addedAt, forKey: .addedAt)
        try container.encodeIfPresent(slug, forKey: .slug)
        try container.encodeIfPresent(title, forKey: .title)
    }
}

