//
// ListPatItem.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ListPatItem: Codable, JSONEncodable, Hashable {

    public var id: String
    public var name: String
    public var _prefix: String
    public var scopes: [String]
    public var environment: String
    public var lastUsedAt: Date?
    public var expiresAt: Date?
    public var revokedAt: Date?
    public var createdAt: Date

    public init(id: String, name: String, _prefix: String, scopes: [String], environment: String, lastUsedAt: Date? = nil, expiresAt: Date? = nil, revokedAt: Date? = nil, createdAt: Date) {
        self.id = id
        self.name = name
        self._prefix = _prefix
        self.scopes = scopes
        self.environment = environment
        self.lastUsedAt = lastUsedAt
        self.expiresAt = expiresAt
        self.revokedAt = revokedAt
        self.createdAt = createdAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case name
        case _prefix = "prefix"
        case scopes
        case environment
        case lastUsedAt
        case expiresAt
        case revokedAt
        case createdAt
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(name, forKey: .name)
        try container.encode(_prefix, forKey: ._prefix)
        try container.encode(scopes, forKey: .scopes)
        try container.encode(environment, forKey: .environment)
        try container.encodeIfPresent(lastUsedAt, forKey: .lastUsedAt)
        try container.encodeIfPresent(expiresAt, forKey: .expiresAt)
        try container.encodeIfPresent(revokedAt, forKey: .revokedAt)
        try container.encode(createdAt, forKey: .createdAt)
    }
}

