//
// ListImportsItemFilters.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ListImportsItemFilters: Codable, JSONEncodable, Hashable {

    public var listedAfter: String?
    public var listedBefore: String?
    public var minPrice: Double?
    public var maxPrice: Double?
    public var conditionIncludes: [String]?
    public var maxImport: Double?

    public init(listedAfter: String? = nil, listedBefore: String? = nil, minPrice: Double? = nil, maxPrice: Double? = nil, conditionIncludes: [String]? = nil, maxImport: Double? = nil) {
        self.listedAfter = listedAfter
        self.listedBefore = listedBefore
        self.minPrice = minPrice
        self.maxPrice = maxPrice
        self.conditionIncludes = conditionIncludes
        self.maxImport = maxImport
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case listedAfter
        case listedBefore
        case minPrice
        case maxPrice
        case conditionIncludes
        case maxImport
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(listedAfter, forKey: .listedAfter)
        try container.encodeIfPresent(listedBefore, forKey: .listedBefore)
        try container.encodeIfPresent(minPrice, forKey: .minPrice)
        try container.encodeIfPresent(maxPrice, forKey: .maxPrice)
        try container.encodeIfPresent(conditionIncludes, forKey: .conditionIncludes)
        try container.encodeIfPresent(maxImport, forKey: .maxImport)
    }
}

