//
// ListTaxonomySuggestItemDisplays.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Per-level human labels for &#x60;catalog&#x60; — lets a caller persist the FLAT department/category/subcategory override keys (matching the web form&#39;s picker) with real labels instead of a bare id. */
public struct ListTaxonomySuggestItemDisplays: Codable, JSONEncodable, Hashable {

    public var department: String?
    public var category: String?
    public var feature: String?

    public init(department: String? = nil, category: String? = nil, feature: String? = nil) {
        self.department = department
        self.category = category
        self.feature = feature
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case department
        case category
        case feature
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(department, forKey: .department)
        try container.encodeIfPresent(category, forKey: .category)
        try container.encodeIfPresent(feature, forKey: .feature)
    }
}

