//
// ListBuyerCashbackItem.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ListBuyerCashbackItem: Codable, JSONEncodable, Hashable {

    public var id: String
    public var status: String
    public var storeName: String
    public var storeHost: String
    public var orderCents: Double?
    /** What WE will pay. Never the commission — that is our revenue and is not the shopper's business. */
    public var cashbackCents: Double?
    public var activatedAt: Date
    public var confirmedAt: Date?
    public var paidAt: Date?
    public var expiredAt: Date?
    public var rejectedReason: String?

    public init(id: String, status: String, storeName: String, storeHost: String, orderCents: Double? = nil, cashbackCents: Double? = nil, activatedAt: Date, confirmedAt: Date? = nil, paidAt: Date? = nil, expiredAt: Date? = nil, rejectedReason: String? = nil) {
        self.id = id
        self.status = status
        self.storeName = storeName
        self.storeHost = storeHost
        self.orderCents = orderCents
        self.cashbackCents = cashbackCents
        self.activatedAt = activatedAt
        self.confirmedAt = confirmedAt
        self.paidAt = paidAt
        self.expiredAt = expiredAt
        self.rejectedReason = rejectedReason
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case status
        case storeName
        case storeHost
        case orderCents
        case cashbackCents
        case activatedAt
        case confirmedAt
        case paidAt
        case expiredAt
        case rejectedReason
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(status, forKey: .status)
        try container.encode(storeName, forKey: .storeName)
        try container.encode(storeHost, forKey: .storeHost)
        try container.encodeIfPresent(orderCents, forKey: .orderCents)
        try container.encodeIfPresent(cashbackCents, forKey: .cashbackCents)
        try container.encode(activatedAt, forKey: .activatedAt)
        try container.encodeIfPresent(confirmedAt, forKey: .confirmedAt)
        try container.encodeIfPresent(paidAt, forKey: .paidAt)
        try container.encodeIfPresent(expiredAt, forKey: .expiredAt)
        try container.encodeIfPresent(rejectedReason, forKey: .rejectedReason)
    }
}

