//
// UpdatePolicyPresetResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct UpdatePolicyPresetResponse: Codable, JSONEncodable, Hashable {

    public var id: String
    public var userId: String
    /** 'return' | 'shipping' | 'payment' — validated at the route layer. */
    public var kind: String
    public var name: String
    /** Auto-selected on new listings. At most one true per (user, kind). */
    public var isDefault: Bool
    public var createdAt: Date
    public var updatedAt: Date

    public init(id: String, userId: String, kind: String, name: String, isDefault: Bool, createdAt: Date, updatedAt: Date) {
        self.id = id
        self.userId = userId
        self.kind = kind
        self.name = name
        self.isDefault = isDefault
        self.createdAt = createdAt
        self.updatedAt = updatedAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case userId
        case kind
        case name
        case isDefault
        case createdAt
        case updatedAt
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(userId, forKey: .userId)
        try container.encode(kind, forKey: .kind)
        try container.encode(name, forKey: .name)
        try container.encode(isDefault, forKey: .isDefault)
        try container.encode(createdAt, forKey: .createdAt)
        try container.encode(updatedAt, forKey: .updatedAt)
    }
}

