//
// CreateWebhookTestResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CreateWebhookTestResponse: Codable, JSONEncodable, Hashable {

    public var ok: Bool
    public var deliveryId: String

    public init(ok: Bool, deliveryId: String) {
        self.ok = ok
        self.deliveryId = deliveryId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case ok
        case deliveryId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(ok, forKey: .ok)
        try container.encode(deliveryId, forKey: .deliveryId)
    }
}

