//
// CreateWorkflowChainToggleResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CreateWorkflowChainToggleResponse: Codable, JSONEncodable, Hashable {

    public var chain: CreateWorkflowChainToggleResponseChain

    public init(chain: CreateWorkflowChainToggleResponseChain) {
        self.chain = chain
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case chain
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(chain, forKey: .chain)
    }
}

