//
// CreateAiCategorizeResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CreateAiCategorizeResponse: Codable, JSONEncodable, Hashable {

    public var category: CreateAiGenerateListingResponseDescription?
    public var subCategory: CreateAiGenerateListingResponseDescription?
    public var brand: CreateAiGenerateListingResponseDescription?
    public var condition: CreateAiGenerateListingResponseDescription?
    public var colors: CreateAiGenerateListingResponseColors?
    public var size: CreateAiGenerateListingResponseDescription?
    public var tags: CreateAiGenerateListingResponseColors?
    public var suggestedTitle: CreateAiGenerateListingResponseDescription?
    public var material: CreateAiGenerateListingResponseDescription?
    public var style: CreateAiGenerateListingResponseDescription?
    public var pattern: CreateAiGenerateListingResponseDescription?
    public var department: CreateAiGenerateListingResponseDescription?
    public var gender: CreateAiGenerateListingResponseDescription?
    public var itemType: CreateAiGenerateListingResponseDescription?
    public var sizeSystem: CreateAiGenerateListingResponseDescription?

    public init(category: CreateAiGenerateListingResponseDescription? = nil, subCategory: CreateAiGenerateListingResponseDescription? = nil, brand: CreateAiGenerateListingResponseDescription? = nil, condition: CreateAiGenerateListingResponseDescription? = nil, colors: CreateAiGenerateListingResponseColors? = nil, size: CreateAiGenerateListingResponseDescription? = nil, tags: CreateAiGenerateListingResponseColors? = nil, suggestedTitle: CreateAiGenerateListingResponseDescription? = nil, material: CreateAiGenerateListingResponseDescription? = nil, style: CreateAiGenerateListingResponseDescription? = nil, pattern: CreateAiGenerateListingResponseDescription? = nil, department: CreateAiGenerateListingResponseDescription? = nil, gender: CreateAiGenerateListingResponseDescription? = nil, itemType: CreateAiGenerateListingResponseDescription? = nil, sizeSystem: CreateAiGenerateListingResponseDescription? = nil) {
        self.category = category
        self.subCategory = subCategory
        self.brand = brand
        self.condition = condition
        self.colors = colors
        self.size = size
        self.tags = tags
        self.suggestedTitle = suggestedTitle
        self.material = material
        self.style = style
        self.pattern = pattern
        self.department = department
        self.gender = gender
        self.itemType = itemType
        self.sizeSystem = sizeSystem
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case category
        case subCategory
        case brand
        case condition
        case colors
        case size
        case tags
        case suggestedTitle
        case material
        case style
        case pattern
        case department
        case gender
        case itemType
        case sizeSystem
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(category, forKey: .category)
        try container.encodeIfPresent(subCategory, forKey: .subCategory)
        try container.encodeIfPresent(brand, forKey: .brand)
        try container.encodeIfPresent(condition, forKey: .condition)
        try container.encodeIfPresent(colors, forKey: .colors)
        try container.encodeIfPresent(size, forKey: .size)
        try container.encodeIfPresent(tags, forKey: .tags)
        try container.encodeIfPresent(suggestedTitle, forKey: .suggestedTitle)
        try container.encodeIfPresent(material, forKey: .material)
        try container.encodeIfPresent(style, forKey: .style)
        try container.encodeIfPresent(pattern, forKey: .pattern)
        try container.encodeIfPresent(department, forKey: .department)
        try container.encodeIfPresent(gender, forKey: .gender)
        try container.encodeIfPresent(itemType, forKey: .itemType)
        try container.encodeIfPresent(sizeSystem, forKey: .sizeSystem)
    }
}

