//
// CreateInventoryCsvImportResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CreateInventoryCsvImportResponse: Codable, JSONEncodable, Hashable {

    public var problems: [CreateInventoryCsvImportResponseProblems]
    public var problemCount: Double
    public var maxRows: Double
    public var created: Double
    public var updated: Double
    /** Rows that mapped cleanly. `created + updated` when not a dry run. */
    public var usable: Double
    public var totalRows: Double
    public var listingsCreated: Double
    /** True when nothing was written — a preview pass. */
    public var dryRun: Bool

    public init(problems: [CreateInventoryCsvImportResponseProblems], problemCount: Double, maxRows: Double, created: Double, updated: Double, usable: Double, totalRows: Double, listingsCreated: Double, dryRun: Bool) {
        self.problems = problems
        self.problemCount = problemCount
        self.maxRows = maxRows
        self.created = created
        self.updated = updated
        self.usable = usable
        self.totalRows = totalRows
        self.listingsCreated = listingsCreated
        self.dryRun = dryRun
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case problems
        case problemCount
        case maxRows
        case created
        case updated
        case usable
        case totalRows
        case listingsCreated
        case dryRun
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(problems, forKey: .problems)
        try container.encode(problemCount, forKey: .problemCount)
        try container.encode(maxRows, forKey: .maxRows)
        try container.encode(created, forKey: .created)
        try container.encode(updated, forKey: .updated)
        try container.encode(usable, forKey: .usable)
        try container.encode(totalRows, forKey: .totalRows)
        try container.encode(listingsCreated, forKey: .listingsCreated)
        try container.encode(dryRun, forKey: .dryRun)
    }
}

