//
// CreateOrderCancelResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CreateOrderCancelResponse: Codable, JSONEncodable, Hashable {

    public var orderId: String
    public var platform: String
    public var cancelledInCrossly: Bool
    public var platformCancel: String

    public init(orderId: String, platform: String, cancelledInCrossly: Bool, platformCancel: String) {
        self.orderId = orderId
        self.platform = platform
        self.cancelledInCrossly = cancelledInCrossly
        self.platformCancel = platformCancel
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case orderId
        case platform
        case cancelledInCrossly
        case platformCancel
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(orderId, forKey: .orderId)
        try container.encode(platform, forKey: .platform)
        try container.encode(cancelledInCrossly, forKey: .cancelledInCrossly)
        try container.encode(platformCancel, forKey: .platformCancel)
    }
}

