//
// CreateOrderTrackingResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CreateOrderTrackingResponse: Codable, JSONEncodable, Hashable {

    public var jobId: String

    public init(jobId: String) {
        self.jobId = jobId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case jobId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(jobId, forKey: .jobId)
    }
}

