//
// CreateAutomationRuleValidateRecipeResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CreateAutomationRuleValidateRecipeResponse: Codable, JSONEncodable, Hashable {

    public var valid: Bool
    public var error: String
    public var details: CreateAutomationRuleValidateRecipeResponseDetails

    public init(valid: Bool, error: String, details: CreateAutomationRuleValidateRecipeResponseDetails) {
        self.valid = valid
        self.error = error
        self.details = details
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case valid
        case error
        case details
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(valid, forKey: .valid)
        try container.encode(error, forKey: .error)
        try container.encode(details, forKey: .details)
    }
}

