//
// CreateCbxCreditRefreshResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CreateCbxCreditRefreshResponse: Codable, JSONEncodable, Hashable {

    public var creditLineId: String
    public var earnedLimitCents: Double
    public var stakeBonusCents: Double
    public var totalLimitCents: Double
    public var rateBps: Double
    public var termDays: Double
    public var status: String

    public init(creditLineId: String, earnedLimitCents: Double, stakeBonusCents: Double, totalLimitCents: Double, rateBps: Double, termDays: Double, status: String) {
        self.creditLineId = creditLineId
        self.earnedLimitCents = earnedLimitCents
        self.stakeBonusCents = stakeBonusCents
        self.totalLimitCents = totalLimitCents
        self.rateBps = rateBps
        self.termDays = termDays
        self.status = status
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case creditLineId
        case earnedLimitCents
        case stakeBonusCents
        case totalLimitCents
        case rateBps
        case termDays
        case status
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(creditLineId, forKey: .creditLineId)
        try container.encode(earnedLimitCents, forKey: .earnedLimitCents)
        try container.encode(stakeBonusCents, forKey: .stakeBonusCents)
        try container.encode(totalLimitCents, forKey: .totalLimitCents)
        try container.encode(rateBps, forKey: .rateBps)
        try container.encode(termDays, forKey: .termDays)
        try container.encode(status, forKey: .status)
    }
}

