//
// CreateCbxClaimSendResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CreateCbxClaimSendResponse: Codable, JSONEncodable, Hashable {

    public enum Status: String, Codable, CaseIterable {
        case confirmed = "confirmed"
        case failed = "failed"
        case unconfirmed = "unconfirmed"
    }
    public var status: Status
    public var txSig: String?
    public var reason: String?

    public init(status: Status, txSig: String? = nil, reason: String? = nil) {
        self.status = status
        self.txSig = txSig
        self.reason = reason
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case status
        case txSig
        case reason
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(status, forKey: .status)
        try container.encodeIfPresent(txSig, forKey: .txSig)
        try container.encodeIfPresent(reason, forKey: .reason)
    }
}

