//
// CreateCbxRevenueSweepResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CreateCbxRevenueSweepResponse: Codable, JSONEncodable, Hashable {

    public var swept: Bool
    public var baseUnits: String
    public var txSig: String?
    public var reason: String?
    public var breakdown: CreateCbxRevenueSweepResponseBreakdown?

    public init(swept: Bool, baseUnits: String, txSig: String? = nil, reason: String? = nil, breakdown: CreateCbxRevenueSweepResponseBreakdown? = nil) {
        self.swept = swept
        self.baseUnits = baseUnits
        self.txSig = txSig
        self.reason = reason
        self.breakdown = breakdown
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case swept
        case baseUnits
        case txSig
        case reason
        case breakdown
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(swept, forKey: .swept)
        try container.encode(baseUnits, forKey: .baseUnits)
        try container.encodeIfPresent(txSig, forKey: .txSig)
        try container.encodeIfPresent(reason, forKey: .reason)
        try container.encodeIfPresent(breakdown, forKey: .breakdown)
    }
}

