//
// CreateBuyerIdentifyResponseIdentifier.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CreateBuyerIdentifyResponseIdentifier: Codable, JSONEncodable, Hashable {

    public enum Ns: String, Codable, CaseIterable {
        case styleCode = "style_code"
        case gtin = "gtin"
        case legoSet = "lego_set"
        case tcgplayer = "tcgplayer"
        case discogs = "discogs"
        case asin = "asin"
    }
    public var ns: Ns
    public var value: String

    public init(ns: Ns, value: String) {
        self.ns = ns
        self.value = value
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case ns
        case value
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(ns, forKey: .ns)
        try container.encode(value, forKey: .value)
    }
}

