//
// CreateBillingUpgradeResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CreateBillingUpgradeResponse: Codable, JSONEncodable, Hashable {

    public enum Tier: String, Codable, CaseIterable {
        case starter = "starter"
        case pro = "pro"
        case unlimited = "unlimited"
    }
    public enum Interval: String, Codable, CaseIterable {
        case monthly = "monthly"
        case yearly = "yearly"
    }
    public var checkoutUrl: String?
    public var tier: Tier
    public var interval: Interval
    public var charged: Bool

    public init(checkoutUrl: String? = nil, tier: Tier, interval: Interval, charged: Bool) {
        self.checkoutUrl = checkoutUrl
        self.tier = tier
        self.interval = interval
        self.charged = charged
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case checkoutUrl
        case tier
        case interval
        case charged
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(checkoutUrl, forKey: .checkoutUrl)
        try container.encode(tier, forKey: .tier)
        try container.encode(interval, forKey: .interval)
        try container.encode(charged, forKey: .charged)
    }
}

