//
// CreateAccountCancelDeletionResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CreateAccountCancelDeletionResponse: Codable, JSONEncodable, Hashable {

    public var cancelled: Bool

    public init(cancelled: Bool) {
        self.cancelled = cancelled
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case cancelled
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(cancelled, forKey: .cancelled)
    }
}

