//
// CreateAiEnhanceTitleResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CreateAiEnhanceTitleResponse: Codable, JSONEncodable, Hashable {

    public var enhancedTitle: String

    public init(enhancedTitle: String) {
        self.enhancedTitle = enhancedTitle
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case enhancedTitle
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(enhancedTitle, forKey: .enhancedTitle)
    }
}

