//
// CreateBuyerIdentifyResponseHud.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CreateBuyerIdentifyResponseHud: Codable, JSONEncodable, Hashable {

    public enum Tone: String, Codable, CaseIterable {
        case _none = "none"
        case info = "info"
        case win = "win"
    }
    public var headline: String
    public var subline: String?
    public var facts: [CreateBuyerIdentifyResponseHudFacts]
    public var action: CreateBuyerIdentifyResponseHudAction
    /** `win` earned a saving, `info` found something, `none` found nothing. */
    public var tone: Tone
    /** Image for the lens card, when there is a match worth showing. */
    public var imageUrl: String?

    public init(headline: String, subline: String? = nil, facts: [CreateBuyerIdentifyResponseHudFacts], action: CreateBuyerIdentifyResponseHudAction, tone: Tone, imageUrl: String? = nil) {
        self.headline = headline
        self.subline = subline
        self.facts = facts
        self.action = action
        self.tone = tone
        self.imageUrl = imageUrl
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case headline
        case subline
        case facts
        case action
        case tone
        case imageUrl
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(headline, forKey: .headline)
        try container.encodeIfPresent(subline, forKey: .subline)
        try container.encode(facts, forKey: .facts)
        try container.encode(action, forKey: .action)
        try container.encode(tone, forKey: .tone)
        try container.encodeIfPresent(imageUrl, forKey: .imageUrl)
    }
}

