//
// CreateListingResponseSkipped.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CreateListingResponseSkipped: Codable, JSONEncodable, Hashable {

    public var platform: String
    public var reason: String

    public init(platform: String, reason: String) {
        self.platform = platform
        self.reason = reason
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case platform
        case reason
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(platform, forKey: .platform)
        try container.encode(reason, forKey: .reason)
    }
}

