//
// CreateAutomationRuleImportResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CreateAutomationRuleImportResponse: Codable, JSONEncodable, Hashable {

    public var created: [CreateAutomationRuleImportResponseCreated]
    public var errors: [CreateAutomationRuleImportResponseErrors]

    public init(created: [CreateAutomationRuleImportResponseCreated], errors: [CreateAutomationRuleImportResponseErrors]) {
        self.created = created
        self.errors = errors
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case created
        case errors
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(created, forKey: .created)
        try container.encode(errors, forKey: .errors)
    }
}

