//
// CreateCbxDisbursementRuleCheckResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CreateCbxDisbursementRuleCheckResponse: Codable, JSONEncodable, Hashable {

    public enum Outcome: String, Codable, CaseIterable {
        case fired = "fired"
        case belowThreshold = "below_threshold"
        case cadence = "cadence"
        case coverage = "coverage"
        case noPrice = "no_price"
        case noRecipients = "no_recipients"
        case inactive = "inactive"
    }
    public var outcome: Outcome
    public var fired: Bool
    public var poolBaseUnits: String
    public var thresholdBaseUnits: String
    public var distributeBaseUnits: String
    public var coverageBps: Double?
    public var campaignId: String?

    public init(outcome: Outcome, fired: Bool, poolBaseUnits: String, thresholdBaseUnits: String, distributeBaseUnits: String, coverageBps: Double? = nil, campaignId: String? = nil) {
        self.outcome = outcome
        self.fired = fired
        self.poolBaseUnits = poolBaseUnits
        self.thresholdBaseUnits = thresholdBaseUnits
        self.distributeBaseUnits = distributeBaseUnits
        self.coverageBps = coverageBps
        self.campaignId = campaignId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case outcome
        case fired
        case poolBaseUnits
        case thresholdBaseUnits
        case distributeBaseUnits
        case coverageBps
        case campaignId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(outcome, forKey: .outcome)
        try container.encode(fired, forKey: .fired)
        try container.encode(poolBaseUnits, forKey: .poolBaseUnits)
        try container.encode(thresholdBaseUnits, forKey: .thresholdBaseUnits)
        try container.encode(distributeBaseUnits, forKey: .distributeBaseUnits)
        try container.encodeIfPresent(coverageBps, forKey: .coverageBps)
        try container.encodeIfPresent(campaignId, forKey: .campaignId)
    }
}

