//
// CreateCbxBoostResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CreateCbxBoostResponse: Codable, JSONEncodable, Hashable {

    public var boostId: String
    public var status: String

    public init(boostId: String, status: String) {
        self.boostId = boostId
        self.status = status
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case boostId
        case status
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(boostId, forKey: .boostId)
        try container.encode(status, forKey: .status)
    }
}

