//
// CreateCbxCampaignPreviewResponseAllocations.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CreateCbxCampaignPreviewResponseAllocations: Codable, JSONEncodable, Hashable {

    public var subjectId: String
    public var weight: String
    public var baseUnits: String

    public init(subjectId: String, weight: String, baseUnits: String) {
        self.subjectId = subjectId
        self.weight = weight
        self.baseUnits = baseUnits
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case subjectId
        case weight
        case baseUnits
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(subjectId, forKey: .subjectId)
        try container.encode(weight, forKey: .weight)
        try container.encode(baseUnits, forKey: .baseUnits)
    }
}

