//
// CreateAccountResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CreateAccountResponse: Codable, JSONEncodable, Hashable {

    public var id: String
    public var platform: String
    public var accountSlot: Double
    public var proxyAssigned: Bool

    public init(id: String, platform: String, accountSlot: Double, proxyAssigned: Bool) {
        self.id = id
        self.platform = platform
        self.accountSlot = accountSlot
        self.proxyAssigned = proxyAssigned
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case platform
        case accountSlot
        case proxyAssigned
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(platform, forKey: .platform)
        try container.encode(accountSlot, forKey: .accountSlot)
        try container.encode(proxyAssigned, forKey: .proxyAssigned)
    }
}

