//
// CreateCbxAccrualResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CreateCbxAccrualResponse: Codable, JSONEncodable, Hashable {

    public var duplicate: Bool
    public var sourceExternalId: String?

    public init(duplicate: Bool, sourceExternalId: String? = nil) {
        self.duplicate = duplicate
        self.sourceExternalId = sourceExternalId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case duplicate
        case sourceExternalId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(duplicate, forKey: .duplicate)
        try container.encodeIfPresent(sourceExternalId, forKey: .sourceExternalId)
    }
}

