//
// CreateOrderBulkDeleteResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CreateOrderBulkDeleteResponse: Codable, JSONEncodable, Hashable {

    public var deleted: Double
    public var hardDelete: Bool

    public init(deleted: Double, hardDelete: Bool) {
        self.deleted = deleted
        self.hardDelete = hardDelete
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case deleted
        case hardDelete
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(deleted, forKey: .deleted)
        try container.encode(hardDelete, forKey: .hardDelete)
    }
}

