//
// CreateAiTestKeyResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CreateAiTestKeyResponse: Codable, JSONEncodable, Hashable {

    public var valid: Bool

    public init(valid: Bool) {
        self.valid = valid
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case valid
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(valid, forKey: .valid)
    }
}

