//
// CreateAccountLogoutAllResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CreateAccountLogoutAllResponse: Codable, JSONEncodable, Hashable {

    public var ok: Bool
    public var revokedCount: Double

    public init(ok: Bool, revokedCount: Double) {
        self.ok = ok
        self.revokedCount = revokedCount
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case ok
        case revokedCount
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(ok, forKey: .ok)
        try container.encode(revokedCount, forKey: .revokedCount)
    }
}

