//
// GetAccountDeletionStatusResponsePending.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GetAccountDeletionStatusResponsePending: Codable, JSONEncodable, Hashable {

    public var id: String
    public var requestedAt: Date
    public var scheduledFor: Date

    public init(id: String, requestedAt: Date, scheduledFor: Date) {
        self.id = id
        self.requestedAt = requestedAt
        self.scheduledFor = scheduledFor
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case requestedAt
        case scheduledFor
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(requestedAt, forKey: .requestedAt)
        try container.encode(scheduledFor, forKey: .scheduledFor)
    }
}

