//
// GetAdOffsiteResponseTermsNetworks.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GetAdOffsiteResponseTermsNetworks: Codable, JSONEncodable, Hashable {

    public var _0: String
    public var _1: String
    public var _2: String
    public var _3: String
    public var _4: String
    public var length: Double
    /** Returns a string representation of an array. */
    public var toString: AnyCodable
    /** Returns a string representation of an array. The elements are converted to string using their toLocaleString methods. */
    public var toLocaleString: AnyCodable
    /** Combines two or more arrays. */
    public var concat: AnyCodable
    /** Adds all the elements of an array separated by the specified separator string. */
    public var join: AnyCodable
    /** Returns a section of an array. */
    public var slice: AnyCodable
    /** Returns the index of the first occurrence of a value in an array. */
    public var indexOf: AnyCodable
    /** Returns the index of the last occurrence of a specified value in an array. */
    public var lastIndexOf: AnyCodable
    /** Determines whether all the members of an array satisfy the specified test. */
    public var every: AnyCodable
    /** Determines whether the specified callback function returns true for any element of an array. */
    public var some: AnyCodable
    /** Performs the specified action for each element in an array. */
    public var forEach: AnyCodable
    /** Calls a defined callback function on each element of an array, and returns an array that contains the results. */
    public var map: AnyCodable
    /** Returns the elements of an array that meet the condition specified in a callback function. */
    public var filter: AnyCodable
    /** Calls the specified callback function for all the elements in an array. The return value of the callback function is the accumulated result, and is provided as an argument in the next call to the callback function. */
    public var reduce: AnyCodable
    /** Calls the specified callback function for all the elements in an array, in descending order. The return value of the callback function is the accumulated result, and is provided as an argument in the next call to the callback function. */
    public var reduceRight: AnyCodable
    /** Returns the value of the first element in the array where predicate is true, and undefined otherwise. */
    public var find: AnyCodable
    /** Returns the index of the first element in the array where predicate is true, and -1 otherwise. */
    public var findIndex: AnyCodable
    /** Returns an iterable of key, value pairs for every entry in the array */
    public var entries: AnyCodable
    /** Returns an iterable of keys in the array */
    public var keys: AnyCodable
    /** Returns an iterable of values in the array */
    public var values: AnyCodable
    /** Determines whether an array includes a certain element, returning true or false as appropriate. */
    public var includes: AnyCodable
    /** Calls a defined callback function on each element of an array. Then, flattens the result into a new array. This is identical to a map followed by flat with depth 1. */
    public var flatMap: AnyCodable
    /** Returns a new array with all sub-array elements concatenated into it recursively up to the specified depth. */
    public var flat: AnyCodable
    /** Returns the item located at the specified index. */
    public var at: AnyCodable
    /** Iterator of values in the array. */
    public var iterator446: AnyCodable
    /** Is an object whose properties have the value 'true' when they will be absent when used in a 'with' statement. */
    public var unscopables448: AnyCodable

    public init(_0: String, _1: String, _2: String, _3: String, _4: String, length: Double, toString: AnyCodable, toLocaleString: AnyCodable, concat: AnyCodable, join: AnyCodable, slice: AnyCodable, indexOf: AnyCodable, lastIndexOf: AnyCodable, every: AnyCodable, some: AnyCodable, forEach: AnyCodable, map: AnyCodable, filter: AnyCodable, reduce: AnyCodable, reduceRight: AnyCodable, find: AnyCodable, findIndex: AnyCodable, entries: AnyCodable, keys: AnyCodable, values: AnyCodable, includes: AnyCodable, flatMap: AnyCodable, flat: AnyCodable, at: AnyCodable, iterator446: AnyCodable, unscopables448: AnyCodable) {
        self._0 = _0
        self._1 = _1
        self._2 = _2
        self._3 = _3
        self._4 = _4
        self.length = length
        self.toString = toString
        self.toLocaleString = toLocaleString
        self.concat = concat
        self.join = join
        self.slice = slice
        self.indexOf = indexOf
        self.lastIndexOf = lastIndexOf
        self.every = every
        self.some = some
        self.forEach = forEach
        self.map = map
        self.filter = filter
        self.reduce = reduce
        self.reduceRight = reduceRight
        self.find = find
        self.findIndex = findIndex
        self.entries = entries
        self.keys = keys
        self.values = values
        self.includes = includes
        self.flatMap = flatMap
        self.flat = flat
        self.at = at
        self.iterator446 = iterator446
        self.unscopables448 = unscopables448
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case _0 = "0"
        case _1 = "1"
        case _2 = "2"
        case _3 = "3"
        case _4 = "4"
        case length
        case toString
        case toLocaleString
        case concat
        case join
        case slice
        case indexOf
        case lastIndexOf
        case every
        case some
        case forEach
        case map
        case filter
        case reduce
        case reduceRight
        case find
        case findIndex
        case entries
        case keys
        case values
        case includes
        case flatMap
        case flat
        case at
        case iterator446 = "__@iterator@446"
        case unscopables448 = "__@unscopables@448"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(_0, forKey: ._0)
        try container.encode(_1, forKey: ._1)
        try container.encode(_2, forKey: ._2)
        try container.encode(_3, forKey: ._3)
        try container.encode(_4, forKey: ._4)
        try container.encode(length, forKey: .length)
        try container.encode(toString, forKey: .toString)
        try container.encode(toLocaleString, forKey: .toLocaleString)
        try container.encode(concat, forKey: .concat)
        try container.encode(join, forKey: .join)
        try container.encode(slice, forKey: .slice)
        try container.encode(indexOf, forKey: .indexOf)
        try container.encode(lastIndexOf, forKey: .lastIndexOf)
        try container.encode(every, forKey: .every)
        try container.encode(some, forKey: .some)
        try container.encode(forEach, forKey: .forEach)
        try container.encode(map, forKey: .map)
        try container.encode(filter, forKey: .filter)
        try container.encode(reduce, forKey: .reduce)
        try container.encode(reduceRight, forKey: .reduceRight)
        try container.encode(find, forKey: .find)
        try container.encode(findIndex, forKey: .findIndex)
        try container.encode(entries, forKey: .entries)
        try container.encode(keys, forKey: .keys)
        try container.encode(values, forKey: .values)
        try container.encode(includes, forKey: .includes)
        try container.encode(flatMap, forKey: .flatMap)
        try container.encode(flat, forKey: .flat)
        try container.encode(at, forKey: .at)
        try container.encode(iterator446, forKey: .iterator446)
        try container.encode(unscopables448, forKey: .unscopables448)
    }
}

