//
// GetAutomationRuleResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GetAutomationRuleResponse: Codable, JSONEncodable, Hashable {

    public var rule: GetAutomationRuleResponseRule

    public init(rule: GetAutomationRuleResponseRule) {
        self.rule = rule
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case rule
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(rule, forKey: .rule)
    }
}

