//
// GetAiStatusResponseCapabilities.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GetAiStatusResponseCapabilities: Codable, JSONEncodable, Hashable {

    public var vision: Bool
    public var jsonMode: Bool

    public init(vision: Bool, jsonMode: Bool) {
        self.vision = vision
        self.jsonMode = jsonMode
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case vision
        case jsonMode
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(vision, forKey: .vision)
        try container.encode(jsonMode, forKey: .jsonMode)
    }
}

