//
// GetAnalyticDashboardResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GetAnalyticDashboardResponse: Codable, JSONEncodable, Hashable {

    public var revenue: GetAnalyticDashboardResponseRevenue
    public var profit: GetAnalyticDashboardResponseRevenue
    public var soldItemsCount: GetAnalyticDashboardResponseRevenue
    public var cancelledCount: GetAnalyticDashboardResponseRevenue
    public var cancelRate: GetAnalyticDashboardResponseCancelRate
    public var refundedAmount: GetAnalyticDashboardResponseRevenue
    public var refundedCount: GetAnalyticDashboardResponseRevenue
    public var listedItemsCount: GetAnalyticDashboardResponseRevenue
    public var avgSalePrice: GetAnalyticDashboardResponseRevenue
    public var sellThroughRate: Double?
    public var sellThrough: GetAnalyticDashboardResponseSellThrough
    public var avgDaysToSell: Double?
    public var salesByPlatform: [GetAnalyticDashboardResponseSalesByPlatform]
    public var avgSalePriceByPlatform: [GetAnalyticDashboardResponseAvgSalePriceByPlatform]
    public var revenueByDay: [GetAnalyticDashboardResponseRevenueByDay]
    public var topCategories: [GetAnalyticDashboardResponseTopCategories]
    public var topSubcategories: [GetAnalyticDashboardResponseTopCategories]
    public var topBrands: [GetAnalyticDashboardResponseTopCategories]
    public var top5ItemsByRevenue: [GetAnalyticDashboardResponseTop5ItemsByRevenue]
    public var recentSales: [GetAnalyticDashboardResponseRecentSales]
    public var availableLabels: [String]

    public init(revenue: GetAnalyticDashboardResponseRevenue, profit: GetAnalyticDashboardResponseRevenue, soldItemsCount: GetAnalyticDashboardResponseRevenue, cancelledCount: GetAnalyticDashboardResponseRevenue, cancelRate: GetAnalyticDashboardResponseCancelRate, refundedAmount: GetAnalyticDashboardResponseRevenue, refundedCount: GetAnalyticDashboardResponseRevenue, listedItemsCount: GetAnalyticDashboardResponseRevenue, avgSalePrice: GetAnalyticDashboardResponseRevenue, sellThroughRate: Double? = nil, sellThrough: GetAnalyticDashboardResponseSellThrough, avgDaysToSell: Double? = nil, salesByPlatform: [GetAnalyticDashboardResponseSalesByPlatform], avgSalePriceByPlatform: [GetAnalyticDashboardResponseAvgSalePriceByPlatform], revenueByDay: [GetAnalyticDashboardResponseRevenueByDay], topCategories: [GetAnalyticDashboardResponseTopCategories], topSubcategories: [GetAnalyticDashboardResponseTopCategories], topBrands: [GetAnalyticDashboardResponseTopCategories], top5ItemsByRevenue: [GetAnalyticDashboardResponseTop5ItemsByRevenue], recentSales: [GetAnalyticDashboardResponseRecentSales], availableLabels: [String]) {
        self.revenue = revenue
        self.profit = profit
        self.soldItemsCount = soldItemsCount
        self.cancelledCount = cancelledCount
        self.cancelRate = cancelRate
        self.refundedAmount = refundedAmount
        self.refundedCount = refundedCount
        self.listedItemsCount = listedItemsCount
        self.avgSalePrice = avgSalePrice
        self.sellThroughRate = sellThroughRate
        self.sellThrough = sellThrough
        self.avgDaysToSell = avgDaysToSell
        self.salesByPlatform = salesByPlatform
        self.avgSalePriceByPlatform = avgSalePriceByPlatform
        self.revenueByDay = revenueByDay
        self.topCategories = topCategories
        self.topSubcategories = topSubcategories
        self.topBrands = topBrands
        self.top5ItemsByRevenue = top5ItemsByRevenue
        self.recentSales = recentSales
        self.availableLabels = availableLabels
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case revenue
        case profit
        case soldItemsCount
        case cancelledCount
        case cancelRate
        case refundedAmount
        case refundedCount
        case listedItemsCount
        case avgSalePrice
        case sellThroughRate
        case sellThrough
        case avgDaysToSell
        case salesByPlatform
        case avgSalePriceByPlatform
        case revenueByDay
        case topCategories
        case topSubcategories
        case topBrands
        case top5ItemsByRevenue
        case recentSales
        case availableLabels
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(revenue, forKey: .revenue)
        try container.encode(profit, forKey: .profit)
        try container.encode(soldItemsCount, forKey: .soldItemsCount)
        try container.encode(cancelledCount, forKey: .cancelledCount)
        try container.encode(cancelRate, forKey: .cancelRate)
        try container.encode(refundedAmount, forKey: .refundedAmount)
        try container.encode(refundedCount, forKey: .refundedCount)
        try container.encode(listedItemsCount, forKey: .listedItemsCount)
        try container.encode(avgSalePrice, forKey: .avgSalePrice)
        try container.encodeIfPresent(sellThroughRate, forKey: .sellThroughRate)
        try container.encode(sellThrough, forKey: .sellThrough)
        try container.encodeIfPresent(avgDaysToSell, forKey: .avgDaysToSell)
        try container.encode(salesByPlatform, forKey: .salesByPlatform)
        try container.encode(avgSalePriceByPlatform, forKey: .avgSalePriceByPlatform)
        try container.encode(revenueByDay, forKey: .revenueByDay)
        try container.encode(topCategories, forKey: .topCategories)
        try container.encode(topSubcategories, forKey: .topSubcategories)
        try container.encode(topBrands, forKey: .topBrands)
        try container.encode(top5ItemsByRevenue, forKey: .top5ItemsByRevenue)
        try container.encode(recentSales, forKey: .recentSales)
        try container.encode(availableLabels, forKey: .availableLabels)
    }
}

