//
// GetBuyerCatalogFacetResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GetBuyerCatalogFacetResponse: Codable, JSONEncodable, Hashable {

    public var brands: [GetBuyerCatalogFacetResponseBrands]
    public var conditions: [GetBuyerCatalogFacetResponseBrands]
    public var categories: [GetBuyerCatalogFacetResponseBrands]

    public init(brands: [GetBuyerCatalogFacetResponseBrands], conditions: [GetBuyerCatalogFacetResponseBrands], categories: [GetBuyerCatalogFacetResponseBrands]) {
        self.brands = brands
        self.conditions = conditions
        self.categories = categories
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case brands
        case conditions
        case categories
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(brands, forKey: .brands)
        try container.encode(conditions, forKey: .conditions)
        try container.encode(categories, forKey: .categories)
    }
}

