//
// GetBuyerCheckoutControlResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GetBuyerCheckoutControlResponse: Codable, JSONEncodable, Hashable {

    public var patId: String
    public var enabled: Bool
    public var dailyLimitCents: Double
    public var perOrderLimitCents: Double
    public var maxUnitsPerListingPerDay: Double

    public init(patId: String, enabled: Bool, dailyLimitCents: Double, perOrderLimitCents: Double, maxUnitsPerListingPerDay: Double) {
        self.patId = patId
        self.enabled = enabled
        self.dailyLimitCents = dailyLimitCents
        self.perOrderLimitCents = perOrderLimitCents
        self.maxUnitsPerListingPerDay = maxUnitsPerListingPerDay
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case patId
        case enabled
        case dailyLimitCents
        case perOrderLimitCents
        case maxUnitsPerListingPerDay
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(patId, forKey: .patId)
        try container.encode(enabled, forKey: .enabled)
        try container.encode(dailyLimitCents, forKey: .dailyLimitCents)
        try container.encode(perOrderLimitCents, forKey: .perOrderLimitCents)
        try container.encode(maxUnitsPerListingPerDay, forKey: .maxUnitsPerListingPerDay)
    }
}

