//
// GetConnectionEmailResponseData.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GetConnectionEmailResponseData: Codable, JSONEncodable, Hashable {

    public var id: String
    public var type: String
    public var isConnected: Bool
    public var email: String
    public var host: String?
    public var port: Double?
    public var lastSyncedAt: Date?

    public init(id: String, type: String, isConnected: Bool, email: String, host: String? = nil, port: Double? = nil, lastSyncedAt: Date? = nil) {
        self.id = id
        self.type = type
        self.isConnected = isConnected
        self.email = email
        self.host = host
        self.port = port
        self.lastSyncedAt = lastSyncedAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case type
        case isConnected
        case email
        case host
        case port
        case lastSyncedAt
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(type, forKey: .type)
        try container.encode(isConnected, forKey: .isConnected)
        try container.encode(email, forKey: .email)
        try container.encodeIfPresent(host, forKey: .host)
        try container.encodeIfPresent(port, forKey: .port)
        try container.encodeIfPresent(lastSyncedAt, forKey: .lastSyncedAt)
    }
}

