//
// GetCbxAdCreditResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GetCbxAdCreditResponse: Codable, JSONEncodable, Hashable {

    public var balanceCents: Double
    public var poolShareBps: Double

    public init(balanceCents: Double, poolShareBps: Double) {
        self.balanceCents = balanceCents
        self.poolShareBps = poolShareBps
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case balanceCents
        case poolShareBps
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(balanceCents, forKey: .balanceCents)
        try container.encode(poolShareBps, forKey: .poolShareBps)
    }
}

