//
// GetCbxCreditResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GetCbxCreditResponse: Codable, JSONEncodable, Hashable {

    public var totalLimitCents: Double
    public var drawnCents: Double
    public var availableCents: Double
    public var rateBps: Double
    public var termDays: Double
    public var status: String

    public init(totalLimitCents: Double, drawnCents: Double, availableCents: Double, rateBps: Double, termDays: Double, status: String) {
        self.totalLimitCents = totalLimitCents
        self.drawnCents = drawnCents
        self.availableCents = availableCents
        self.rateBps = rateBps
        self.termDays = termDays
        self.status = status
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case totalLimitCents
        case drawnCents
        case availableCents
        case rateBps
        case termDays
        case status
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(totalLimitCents, forKey: .totalLimitCents)
        try container.encode(drawnCents, forKey: .drawnCents)
        try container.encode(availableCents, forKey: .availableCents)
        try container.encode(rateBps, forKey: .rateBps)
        try container.encode(termDays, forKey: .termDays)
        try container.encode(status, forKey: .status)
    }
}

