//
// GetCbxMeResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GetCbxMeResponse: Codable, JSONEncodable, Hashable {

    public enum Scopes: String, Codable, CaseIterable {
        case campaign = "campaign"
        case read = "read"
        case accrue = "accrue"
        case spend = "spend"
        case treasury = "treasury"
    }
    public var merchantId: String
    public var slug: String?
    public var name: String?
    public var status: String?
    public var scopes: [Scopes]
    public var terms: GetCbxMeResponseTerms

    public init(merchantId: String, slug: String? = nil, name: String? = nil, status: String? = nil, scopes: [Scopes], terms: GetCbxMeResponseTerms) {
        self.merchantId = merchantId
        self.slug = slug
        self.name = name
        self.status = status
        self.scopes = scopes
        self.terms = terms
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case merchantId
        case slug
        case name
        case status
        case scopes
        case terms
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(merchantId, forKey: .merchantId)
        try container.encodeIfPresent(slug, forKey: .slug)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(status, forKey: .status)
        try container.encode(scopes, forKey: .scopes)
        try container.encode(terms, forKey: .terms)
    }
}

