//
// GetConnectionEmailResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GetConnectionEmailResponse: Codable, JSONEncodable, Hashable {

    public var data: [GetConnectionEmailResponseData]
    public var imap: [GetConnectionEmailResponseData]
    public var oauth: [GetConnectionEmailResponseOauth]

    public init(data: [GetConnectionEmailResponseData], imap: [GetConnectionEmailResponseData], oauth: [GetConnectionEmailResponseOauth]) {
        self.data = data
        self.imap = imap
        self.oauth = oauth
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case data
        case imap
        case oauth
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(data, forKey: .data)
        try container.encode(imap, forKey: .imap)
        try container.encode(oauth, forKey: .oauth)
    }
}

