//
// GetCustomerResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GetCustomerResponse: Codable, JSONEncodable, Hashable {

    public var normalizedHandle: String
    public var platforms: [String]
    public var totalOrders: Double
    public var totalSpent: Double
    public var orders: [GetCustomerResponseOrders]
    public var contact: GetCustomerResponseContact

    public init(normalizedHandle: String, platforms: [String], totalOrders: Double, totalSpent: Double, orders: [GetCustomerResponseOrders], contact: GetCustomerResponseContact) {
        self.normalizedHandle = normalizedHandle
        self.platforms = platforms
        self.totalOrders = totalOrders
        self.totalSpent = totalSpent
        self.orders = orders
        self.contact = contact
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case normalizedHandle
        case platforms
        case totalOrders
        case totalSpent
        case orders
        case contact
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(normalizedHandle, forKey: .normalizedHandle)
        try container.encode(platforms, forKey: .platforms)
        try container.encode(totalOrders, forKey: .totalOrders)
        try container.encode(totalSpent, forKey: .totalSpent)
        try container.encode(orders, forKey: .orders)
        try container.encode(contact, forKey: .contact)
    }
}

