//
// GetCbxPoolResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GetCbxPoolResponse: Codable, JSONEncodable, Hashable {

    public var poolBaseUnits: String

    public init(poolBaseUnits: String) {
        self.poolBaseUnits = poolBaseUnits
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case poolBaseUnits
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(poolBaseUnits, forKey: .poolBaseUnits)
    }
}

