//
// GetCbxSubjectSpentResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GetCbxSubjectSpentResponse: Codable, JSONEncodable, Hashable {

    public var spentBaseUnits: String

    public init(spentBaseUnits: String) {
        self.spentBaseUnits = spentBaseUnits
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case spentBaseUnits
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(spentBaseUnits, forKey: .spentBaseUnits)
    }
}

