//
// GetInventoryResponsePlatformListings.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GetInventoryResponsePlatformListings: Codable, JSONEncodable, Hashable {

    public var id: String
    public var userId: String
    public var quantity: Double
    public var status: String
    public var platform: String
    public var errorMessage: String?
    public var listingId: String
    public var accountSlot: Double
    public var delistedAt: Date?
    public var soldAt: Date?
    public var inventoryItemId: String?
    public var platformListingId: String
    public var platformListingUrl: String?
    public var stockLocation: String
    public var listedAt: Date?
    public var sharedAt: Date?
    public var delistReason: String?
    public var lastCheckedAt: Date?
    public var views: Double
    public var favorites: Double
    public var commentsCount: Double
    public var lastStatsSyncedAt: Date?
    public var hashtags: [String]?
    public var isDraft: Bool
    public var scheduledPublishAt: Date?
    public var isDutchAuction: Bool
    public var dutchStartCents: Double?
    public var dutchFloorCents: Double?
    public var dutchEndsAt: Date?
    public var isPreOrder: Bool
    public var expectedShipBy: String?
    public var preorderDepositPercentBps: Double?
    public var boostedAt: Date?
    public var imageCaption: String?
    public var durationDays: Double?
    public var endsAt: Date?
    public var bestOfferEnabled: Bool
    public var bestOfferAutoAcceptCents: Double?
    public var bestOfferAutoDeclineCents: Double?
    public var aestheticTags: [String]?
    public var allowsLocalPickup: Bool
    public var pickupRadiusMiles: Double?
    public var pickupLat: String?
    public var pickupLng: String?
    public var refurbishedTier: String?
    public var charitySlug: String?
    public var charityPercentBps: Double?
    public var crosslyReturnPolicyId: String?
    public var crosslyShippingPolicyId: String?
    public var crosslyPaymentPolicyId: String?
    public var retailPriceCents: Double?
    public var restrictedCountries: [String]?
    public var auctionExtendSeconds: Double?
    public var authenticationProviderSlug: String?
    public var authenticationRequired: Bool
    public var hasVariants: Bool
    public var charityId: String?
    public var minOrderQuantity: Double
    public var wholesaleUnitPriceCents: Double?
    public var wholesaleMinQuantity: Double?
    public var auctionReserveCents: Double?
    public var isGtc: Bool
    public var handlingTimeDays: Double
    public var itemLocation: String?
    public var itemLocationZip: String?
    public var itemLocationCountry: String?
    public var declaredShippingCost: String?
    public var returnPolicyText: String?
    public var lastDriftCheckedAt: Date?

    public init(id: String, userId: String, quantity: Double, status: String, platform: String, errorMessage: String? = nil, listingId: String, accountSlot: Double, delistedAt: Date? = nil, soldAt: Date? = nil, inventoryItemId: String? = nil, platformListingId: String, platformListingUrl: String? = nil, stockLocation: String, listedAt: Date? = nil, sharedAt: Date? = nil, delistReason: String? = nil, lastCheckedAt: Date? = nil, views: Double, favorites: Double, commentsCount: Double, lastStatsSyncedAt: Date? = nil, hashtags: [String]? = nil, isDraft: Bool, scheduledPublishAt: Date? = nil, isDutchAuction: Bool, dutchStartCents: Double? = nil, dutchFloorCents: Double? = nil, dutchEndsAt: Date? = nil, isPreOrder: Bool, expectedShipBy: String? = nil, preorderDepositPercentBps: Double? = nil, boostedAt: Date? = nil, imageCaption: String? = nil, durationDays: Double? = nil, endsAt: Date? = nil, bestOfferEnabled: Bool, bestOfferAutoAcceptCents: Double? = nil, bestOfferAutoDeclineCents: Double? = nil, aestheticTags: [String]? = nil, allowsLocalPickup: Bool, pickupRadiusMiles: Double? = nil, pickupLat: String? = nil, pickupLng: String? = nil, refurbishedTier: String? = nil, charitySlug: String? = nil, charityPercentBps: Double? = nil, crosslyReturnPolicyId: String? = nil, crosslyShippingPolicyId: String? = nil, crosslyPaymentPolicyId: String? = nil, retailPriceCents: Double? = nil, restrictedCountries: [String]? = nil, auctionExtendSeconds: Double? = nil, authenticationProviderSlug: String? = nil, authenticationRequired: Bool, hasVariants: Bool, charityId: String? = nil, minOrderQuantity: Double, wholesaleUnitPriceCents: Double? = nil, wholesaleMinQuantity: Double? = nil, auctionReserveCents: Double? = nil, isGtc: Bool, handlingTimeDays: Double, itemLocation: String? = nil, itemLocationZip: String? = nil, itemLocationCountry: String? = nil, declaredShippingCost: String? = nil, returnPolicyText: String? = nil, lastDriftCheckedAt: Date? = nil) {
        self.id = id
        self.userId = userId
        self.quantity = quantity
        self.status = status
        self.platform = platform
        self.errorMessage = errorMessage
        self.listingId = listingId
        self.accountSlot = accountSlot
        self.delistedAt = delistedAt
        self.soldAt = soldAt
        self.inventoryItemId = inventoryItemId
        self.platformListingId = platformListingId
        self.platformListingUrl = platformListingUrl
        self.stockLocation = stockLocation
        self.listedAt = listedAt
        self.sharedAt = sharedAt
        self.delistReason = delistReason
        self.lastCheckedAt = lastCheckedAt
        self.views = views
        self.favorites = favorites
        self.commentsCount = commentsCount
        self.lastStatsSyncedAt = lastStatsSyncedAt
        self.hashtags = hashtags
        self.isDraft = isDraft
        self.scheduledPublishAt = scheduledPublishAt
        self.isDutchAuction = isDutchAuction
        self.dutchStartCents = dutchStartCents
        self.dutchFloorCents = dutchFloorCents
        self.dutchEndsAt = dutchEndsAt
        self.isPreOrder = isPreOrder
        self.expectedShipBy = expectedShipBy
        self.preorderDepositPercentBps = preorderDepositPercentBps
        self.boostedAt = boostedAt
        self.imageCaption = imageCaption
        self.durationDays = durationDays
        self.endsAt = endsAt
        self.bestOfferEnabled = bestOfferEnabled
        self.bestOfferAutoAcceptCents = bestOfferAutoAcceptCents
        self.bestOfferAutoDeclineCents = bestOfferAutoDeclineCents
        self.aestheticTags = aestheticTags
        self.allowsLocalPickup = allowsLocalPickup
        self.pickupRadiusMiles = pickupRadiusMiles
        self.pickupLat = pickupLat
        self.pickupLng = pickupLng
        self.refurbishedTier = refurbishedTier
        self.charitySlug = charitySlug
        self.charityPercentBps = charityPercentBps
        self.crosslyReturnPolicyId = crosslyReturnPolicyId
        self.crosslyShippingPolicyId = crosslyShippingPolicyId
        self.crosslyPaymentPolicyId = crosslyPaymentPolicyId
        self.retailPriceCents = retailPriceCents
        self.restrictedCountries = restrictedCountries
        self.auctionExtendSeconds = auctionExtendSeconds
        self.authenticationProviderSlug = authenticationProviderSlug
        self.authenticationRequired = authenticationRequired
        self.hasVariants = hasVariants
        self.charityId = charityId
        self.minOrderQuantity = minOrderQuantity
        self.wholesaleUnitPriceCents = wholesaleUnitPriceCents
        self.wholesaleMinQuantity = wholesaleMinQuantity
        self.auctionReserveCents = auctionReserveCents
        self.isGtc = isGtc
        self.handlingTimeDays = handlingTimeDays
        self.itemLocation = itemLocation
        self.itemLocationZip = itemLocationZip
        self.itemLocationCountry = itemLocationCountry
        self.declaredShippingCost = declaredShippingCost
        self.returnPolicyText = returnPolicyText
        self.lastDriftCheckedAt = lastDriftCheckedAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case userId
        case quantity
        case status
        case platform
        case errorMessage
        case listingId
        case accountSlot
        case delistedAt
        case soldAt
        case inventoryItemId
        case platformListingId
        case platformListingUrl
        case stockLocation
        case listedAt
        case sharedAt
        case delistReason
        case lastCheckedAt
        case views
        case favorites
        case commentsCount
        case lastStatsSyncedAt
        case hashtags
        case isDraft
        case scheduledPublishAt
        case isDutchAuction
        case dutchStartCents
        case dutchFloorCents
        case dutchEndsAt
        case isPreOrder
        case expectedShipBy
        case preorderDepositPercentBps
        case boostedAt
        case imageCaption
        case durationDays
        case endsAt
        case bestOfferEnabled
        case bestOfferAutoAcceptCents
        case bestOfferAutoDeclineCents
        case aestheticTags
        case allowsLocalPickup
        case pickupRadiusMiles
        case pickupLat
        case pickupLng
        case refurbishedTier
        case charitySlug
        case charityPercentBps
        case crosslyReturnPolicyId
        case crosslyShippingPolicyId
        case crosslyPaymentPolicyId
        case retailPriceCents
        case restrictedCountries
        case auctionExtendSeconds
        case authenticationProviderSlug
        case authenticationRequired
        case hasVariants
        case charityId
        case minOrderQuantity
        case wholesaleUnitPriceCents
        case wholesaleMinQuantity
        case auctionReserveCents
        case isGtc
        case handlingTimeDays
        case itemLocation
        case itemLocationZip
        case itemLocationCountry
        case declaredShippingCost
        case returnPolicyText
        case lastDriftCheckedAt
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(userId, forKey: .userId)
        try container.encode(quantity, forKey: .quantity)
        try container.encode(status, forKey: .status)
        try container.encode(platform, forKey: .platform)
        try container.encodeIfPresent(errorMessage, forKey: .errorMessage)
        try container.encode(listingId, forKey: .listingId)
        try container.encode(accountSlot, forKey: .accountSlot)
        try container.encodeIfPresent(delistedAt, forKey: .delistedAt)
        try container.encodeIfPresent(soldAt, forKey: .soldAt)
        try container.encodeIfPresent(inventoryItemId, forKey: .inventoryItemId)
        try container.encode(platformListingId, forKey: .platformListingId)
        try container.encodeIfPresent(platformListingUrl, forKey: .platformListingUrl)
        try container.encode(stockLocation, forKey: .stockLocation)
        try container.encodeIfPresent(listedAt, forKey: .listedAt)
        try container.encodeIfPresent(sharedAt, forKey: .sharedAt)
        try container.encodeIfPresent(delistReason, forKey: .delistReason)
        try container.encodeIfPresent(lastCheckedAt, forKey: .lastCheckedAt)
        try container.encode(views, forKey: .views)
        try container.encode(favorites, forKey: .favorites)
        try container.encode(commentsCount, forKey: .commentsCount)
        try container.encodeIfPresent(lastStatsSyncedAt, forKey: .lastStatsSyncedAt)
        try container.encodeIfPresent(hashtags, forKey: .hashtags)
        try container.encode(isDraft, forKey: .isDraft)
        try container.encodeIfPresent(scheduledPublishAt, forKey: .scheduledPublishAt)
        try container.encode(isDutchAuction, forKey: .isDutchAuction)
        try container.encodeIfPresent(dutchStartCents, forKey: .dutchStartCents)
        try container.encodeIfPresent(dutchFloorCents, forKey: .dutchFloorCents)
        try container.encodeIfPresent(dutchEndsAt, forKey: .dutchEndsAt)
        try container.encode(isPreOrder, forKey: .isPreOrder)
        try container.encodeIfPresent(expectedShipBy, forKey: .expectedShipBy)
        try container.encodeIfPresent(preorderDepositPercentBps, forKey: .preorderDepositPercentBps)
        try container.encodeIfPresent(boostedAt, forKey: .boostedAt)
        try container.encodeIfPresent(imageCaption, forKey: .imageCaption)
        try container.encodeIfPresent(durationDays, forKey: .durationDays)
        try container.encodeIfPresent(endsAt, forKey: .endsAt)
        try container.encode(bestOfferEnabled, forKey: .bestOfferEnabled)
        try container.encodeIfPresent(bestOfferAutoAcceptCents, forKey: .bestOfferAutoAcceptCents)
        try container.encodeIfPresent(bestOfferAutoDeclineCents, forKey: .bestOfferAutoDeclineCents)
        try container.encodeIfPresent(aestheticTags, forKey: .aestheticTags)
        try container.encode(allowsLocalPickup, forKey: .allowsLocalPickup)
        try container.encodeIfPresent(pickupRadiusMiles, forKey: .pickupRadiusMiles)
        try container.encodeIfPresent(pickupLat, forKey: .pickupLat)
        try container.encodeIfPresent(pickupLng, forKey: .pickupLng)
        try container.encodeIfPresent(refurbishedTier, forKey: .refurbishedTier)
        try container.encodeIfPresent(charitySlug, forKey: .charitySlug)
        try container.encodeIfPresent(charityPercentBps, forKey: .charityPercentBps)
        try container.encodeIfPresent(crosslyReturnPolicyId, forKey: .crosslyReturnPolicyId)
        try container.encodeIfPresent(crosslyShippingPolicyId, forKey: .crosslyShippingPolicyId)
        try container.encodeIfPresent(crosslyPaymentPolicyId, forKey: .crosslyPaymentPolicyId)
        try container.encodeIfPresent(retailPriceCents, forKey: .retailPriceCents)
        try container.encodeIfPresent(restrictedCountries, forKey: .restrictedCountries)
        try container.encodeIfPresent(auctionExtendSeconds, forKey: .auctionExtendSeconds)
        try container.encodeIfPresent(authenticationProviderSlug, forKey: .authenticationProviderSlug)
        try container.encode(authenticationRequired, forKey: .authenticationRequired)
        try container.encode(hasVariants, forKey: .hasVariants)
        try container.encodeIfPresent(charityId, forKey: .charityId)
        try container.encode(minOrderQuantity, forKey: .minOrderQuantity)
        try container.encodeIfPresent(wholesaleUnitPriceCents, forKey: .wholesaleUnitPriceCents)
        try container.encodeIfPresent(wholesaleMinQuantity, forKey: .wholesaleMinQuantity)
        try container.encodeIfPresent(auctionReserveCents, forKey: .auctionReserveCents)
        try container.encode(isGtc, forKey: .isGtc)
        try container.encode(handlingTimeDays, forKey: .handlingTimeDays)
        try container.encodeIfPresent(itemLocation, forKey: .itemLocation)
        try container.encodeIfPresent(itemLocationZip, forKey: .itemLocationZip)
        try container.encodeIfPresent(itemLocationCountry, forKey: .itemLocationCountry)
        try container.encodeIfPresent(declaredShippingCost, forKey: .declaredShippingCost)
        try container.encodeIfPresent(returnPolicyText, forKey: .returnPolicyText)
        try container.encodeIfPresent(lastDriftCheckedAt, forKey: .lastDriftCheckedAt)
    }
}

