//
// GetMarketProductResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GetMarketProductResponse: Codable, JSONEncodable, Hashable {

    public var product: GetMarketProductResponseProduct
    public var variants: [GetMarketProductResponseVariants]

    public init(product: GetMarketProductResponseProduct, variants: [GetMarketProductResponseVariants]) {
        self.product = product
        self.variants = variants
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case product
        case variants
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(product, forKey: .product)
        try container.encode(variants, forKey: .variants)
    }
}

