//
// GetMarketProductResponseVariants.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GetMarketProductResponseVariants: Codable, JSONEncodable, Hashable {

    public var id: String
    public var label: String
    public var sortKey: Double
    public var externalId: String?
    public var externalSource: String?
    public var externalSyncedAt: Date?
    public var lastSaleCents: Double?
    public var tradesCount: Double
    public var skuId: String
    public var lastSaleAt: Date?
    public var bestBidCents: Double?
    public var bestAskCents: Double?

    public init(id: String, label: String, sortKey: Double, externalId: String? = nil, externalSource: String? = nil, externalSyncedAt: Date? = nil, lastSaleCents: Double? = nil, tradesCount: Double, skuId: String, lastSaleAt: Date? = nil, bestBidCents: Double? = nil, bestAskCents: Double? = nil) {
        self.id = id
        self.label = label
        self.sortKey = sortKey
        self.externalId = externalId
        self.externalSource = externalSource
        self.externalSyncedAt = externalSyncedAt
        self.lastSaleCents = lastSaleCents
        self.tradesCount = tradesCount
        self.skuId = skuId
        self.lastSaleAt = lastSaleAt
        self.bestBidCents = bestBidCents
        self.bestAskCents = bestAskCents
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case label
        case sortKey
        case externalId
        case externalSource
        case externalSyncedAt
        case lastSaleCents
        case tradesCount
        case skuId
        case lastSaleAt
        case bestBidCents
        case bestAskCents
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(label, forKey: .label)
        try container.encode(sortKey, forKey: .sortKey)
        try container.encodeIfPresent(externalId, forKey: .externalId)
        try container.encodeIfPresent(externalSource, forKey: .externalSource)
        try container.encodeIfPresent(externalSyncedAt, forKey: .externalSyncedAt)
        try container.encodeIfPresent(lastSaleCents, forKey: .lastSaleCents)
        try container.encode(tradesCount, forKey: .tradesCount)
        try container.encode(skuId, forKey: .skuId)
        try container.encodeIfPresent(lastSaleAt, forKey: .lastSaleAt)
        try container.encodeIfPresent(bestBidCents, forKey: .bestBidCents)
        try container.encodeIfPresent(bestAskCents, forKey: .bestAskCents)
    }
}

