//
// GetMagicDraftResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GetMagicDraftResponse: Codable, JSONEncodable, Hashable {

    public var draft: GetMagicDraftResponseDraft

    public init(draft: GetMagicDraftResponseDraft) {
        self.draft = draft
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case draft
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(draft, forKey: .draft)
    }
}

