//
// GetMarketVariantBookResponseBids.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GetMarketVariantBookResponseBids: Codable, JSONEncodable, Hashable {

    public var priceCents: Double
    public var count: Double

    public init(priceCents: Double, count: Double) {
        self.priceCents = priceCents
        self.count = count
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case priceCents
        case count
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(priceCents, forKey: .priceCents)
        try container.encode(count, forKey: .count)
    }
}

