//
// GetNetworkPoolResponseMember.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GetNetworkPoolResponseMember: Codable, JSONEncodable, Hashable {

    public var id: String
    public var userId: String
    public var platforms: String
    public var joinedAt: Date
    public var shareEnabled: Bool
    public var followEnabled: Bool
    public var likeEnabled: Bool
    public var lastEngagementAt: Date?
    public var engagementsPerformed: Double
    public var engagementsReceived: Double
    public var flaggedUntil: Date?

    public init(id: String, userId: String, platforms: String, joinedAt: Date, shareEnabled: Bool, followEnabled: Bool, likeEnabled: Bool, lastEngagementAt: Date? = nil, engagementsPerformed: Double, engagementsReceived: Double, flaggedUntil: Date? = nil) {
        self.id = id
        self.userId = userId
        self.platforms = platforms
        self.joinedAt = joinedAt
        self.shareEnabled = shareEnabled
        self.followEnabled = followEnabled
        self.likeEnabled = likeEnabled
        self.lastEngagementAt = lastEngagementAt
        self.engagementsPerformed = engagementsPerformed
        self.engagementsReceived = engagementsReceived
        self.flaggedUntil = flaggedUntil
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case userId
        case platforms
        case joinedAt
        case shareEnabled
        case followEnabled
        case likeEnabled
        case lastEngagementAt
        case engagementsPerformed
        case engagementsReceived
        case flaggedUntil
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(userId, forKey: .userId)
        try container.encode(platforms, forKey: .platforms)
        try container.encode(joinedAt, forKey: .joinedAt)
        try container.encode(shareEnabled, forKey: .shareEnabled)
        try container.encode(followEnabled, forKey: .followEnabled)
        try container.encode(likeEnabled, forKey: .likeEnabled)
        try container.encodeIfPresent(lastEngagementAt, forKey: .lastEngagementAt)
        try container.encode(engagementsPerformed, forKey: .engagementsPerformed)
        try container.encode(engagementsReceived, forKey: .engagementsReceived)
        try container.encodeIfPresent(flaggedUntil, forKey: .flaggedUntil)
    }
}

