//
// GetTaxScheduleCResponseCounts.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GetTaxScheduleCResponseCounts: Codable, JSONEncodable, Hashable {

    public var sales: Double
    public var refunds: Double
    public var mileageEntries: Double

    public init(sales: Double, refunds: Double, mileageEntries: Double) {
        self.sales = sales
        self.refunds = refunds
        self.mileageEntries = mileageEntries
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case sales
        case refunds
        case mileageEntries
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(sales, forKey: .sales)
        try container.encode(refunds, forKey: .refunds)
        try container.encode(mileageEntries, forKey: .mileageEntries)
    }
}

