//
// GetTeamResponseMembers.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GetTeamResponseMembers: Codable, JSONEncodable, Hashable {

    public var id: String
    public var memberUserId: String
    public var memberEmail: String?
    public var memberDisplayName: String?
    public var role: String
    public var scopes: [String]
    public var revokedAt: Date?
    public var createdAt: Date

    public init(id: String, memberUserId: String, memberEmail: String? = nil, memberDisplayName: String? = nil, role: String, scopes: [String], revokedAt: Date? = nil, createdAt: Date) {
        self.id = id
        self.memberUserId = memberUserId
        self.memberEmail = memberEmail
        self.memberDisplayName = memberDisplayName
        self.role = role
        self.scopes = scopes
        self.revokedAt = revokedAt
        self.createdAt = createdAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case memberUserId
        case memberEmail
        case memberDisplayName
        case role
        case scopes
        case revokedAt
        case createdAt
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(memberUserId, forKey: .memberUserId)
        try container.encodeIfPresent(memberEmail, forKey: .memberEmail)
        try container.encodeIfPresent(memberDisplayName, forKey: .memberDisplayName)
        try container.encode(role, forKey: .role)
        try container.encode(scopes, forKey: .scopes)
        try container.encodeIfPresent(revokedAt, forKey: .revokedAt)
        try container.encode(createdAt, forKey: .createdAt)
    }
}

