//
// GetTeamResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GetTeamResponse: Codable, JSONEncodable, Hashable {

    public var invitations: [GetTeamResponseInvitations]
    public var members: [GetTeamResponseMembers]

    public init(invitations: [GetTeamResponseInvitations], members: [GetTeamResponseMembers]) {
        self.invitations = invitations
        self.members = members
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case invitations
        case members
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(invitations, forKey: .invitations)
        try container.encode(members, forKey: .members)
    }
}

