//
// GetWorkflowChainResponseChain.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GetWorkflowChainResponseChain: Codable, JSONEncodable, Hashable {

    public var id: String
    public var name: String
    public var createdAt: Date
    public var userId: String
    public var isActive: Bool
    public var triggerId: String

    public init(id: String, name: String, createdAt: Date, userId: String, isActive: Bool, triggerId: String) {
        self.id = id
        self.name = name
        self.createdAt = createdAt
        self.userId = userId
        self.isActive = isActive
        self.triggerId = triggerId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case name
        case createdAt
        case userId
        case isActive
        case triggerId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(name, forKey: .name)
        try container.encode(createdAt, forKey: .createdAt)
        try container.encode(userId, forKey: .userId)
        try container.encode(isActive, forKey: .isActive)
        try container.encode(triggerId, forKey: .triggerId)
    }
}

