//
// InlineObject.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct InlineObject: Codable, JSONEncodable, Hashable {

    public enum Tier: String, Codable, CaseIterable {
        case starter = "starter"
        case pro = "pro"
        case unlimited = "unlimited"
    }
    public enum Interval: String, Codable, CaseIterable {
        case monthly = "monthly"
        case yearly = "yearly"
    }
    public var tier: Tier
    public var interval: Interval? = .monthly

    public init(tier: Tier, interval: Interval? = .monthly) {
        self.tier = tier
        self.interval = interval
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case tier
        case interval
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(tier, forKey: .tier)
        try container.encodeIfPresent(interval, forKey: .interval)
    }
}

