//
// InlineObject1.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct InlineObject1: Codable, JSONEncodable, Hashable {

    /** null = All time (no limit); 0 = None; a positive integer = days. */
    public var days: AnyCodable?

    public init(days: AnyCodable?) {
        self.days = days
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case days
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(days, forKey: .days)
    }
}

