//
// ListSourcingDemandMineItem.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ListSourcingDemandMineItem: Codable, JSONEncodable, Hashable {

    public enum Relation: String, Codable, CaseIterable {
        case inStock = "in_stock"
        case soldBefore = "sold_before"
    }
    public var identifierValue: String
    /** How many distinct shoppers looked, in the window. */
    public var lookers: Double
    /** How many of those looks Crossly could not answer at all. */
    public var misses: Double
    /** What the retailers were charging, median of what Scout saw. */
    public var medianRetailCents: Double?
    /** 'in_stock' — it is in their inventory. 'sold_before' — they have sold one. */
    public var relation: Relation
    /** Their own row, for the link. */
    public var inventoryItemId: String?
    public var title: String?
    /** What they got for it last time, when they have sold one. */
    public var lastSoldCents: Double?
    public var lastSoldAt: Date?

    public init(identifierValue: String, lookers: Double, misses: Double, medianRetailCents: Double? = nil, relation: Relation, inventoryItemId: String? = nil, title: String? = nil, lastSoldCents: Double? = nil, lastSoldAt: Date? = nil) {
        self.identifierValue = identifierValue
        self.lookers = lookers
        self.misses = misses
        self.medianRetailCents = medianRetailCents
        self.relation = relation
        self.inventoryItemId = inventoryItemId
        self.title = title
        self.lastSoldCents = lastSoldCents
        self.lastSoldAt = lastSoldAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case identifierValue
        case lookers
        case misses
        case medianRetailCents
        case relation
        case inventoryItemId
        case title
        case lastSoldCents
        case lastSoldAt
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(identifierValue, forKey: .identifierValue)
        try container.encode(lookers, forKey: .lookers)
        try container.encode(misses, forKey: .misses)
        try container.encodeIfPresent(medianRetailCents, forKey: .medianRetailCents)
        try container.encode(relation, forKey: .relation)
        try container.encodeIfPresent(inventoryItemId, forKey: .inventoryItemId)
        try container.encodeIfPresent(title, forKey: .title)
        try container.encodeIfPresent(lastSoldCents, forKey: .lastSoldCents)
        try container.encodeIfPresent(lastSoldAt, forKey: .lastSoldAt)
    }
}

