//
// ListBuyerOrdersItem.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ListBuyerOrdersItem: Codable, JSONEncodable, Hashable {

    public var id: String
    public var status: String
    public var buyerPaidCents: Double
    public var createdAt: Date

    public init(id: String, status: String, buyerPaidCents: Double, createdAt: Date) {
        self.id = id
        self.status = status
        self.buyerPaidCents = buyerPaidCents
        self.createdAt = createdAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case status
        case buyerPaidCents
        case createdAt
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(status, forKey: .status)
        try container.encode(buyerPaidCents, forKey: .buyerPaidCents)
        try container.encode(createdAt, forKey: .createdAt)
    }
}

