//
// ListEmbedKeysItem.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ListEmbedKeysItem: Codable, JSONEncodable, Hashable {

    public var id: String
    public var key: String
    public var name: String
    public var allowedOrigins: [String]
    public var environment: String
    public var lastUsedAt: Date?
    public var createdAt: Date

    public init(id: String, key: String, name: String, allowedOrigins: [String], environment: String, lastUsedAt: Date? = nil, createdAt: Date) {
        self.id = id
        self.key = key
        self.name = name
        self.allowedOrigins = allowedOrigins
        self.environment = environment
        self.lastUsedAt = lastUsedAt
        self.createdAt = createdAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case key
        case name
        case allowedOrigins
        case environment
        case lastUsedAt
        case createdAt
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(key, forKey: .key)
        try container.encode(name, forKey: .name)
        try container.encode(allowedOrigins, forKey: .allowedOrigins)
        try container.encode(environment, forKey: .environment)
        try container.encodeIfPresent(lastUsedAt, forKey: .lastUsedAt)
        try container.encode(createdAt, forKey: .createdAt)
    }
}

