//
// ListImportsItem.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ListImportsItem: Codable, JSONEncodable, Hashable {

    public var id: String
    public var createdAt: Date
    public var userId: String
    public var status: String
    public var platform: String
    public var lastError: String?
    public var startedAt: Date?
    public var filters: ListImportsItemFilters?
    public var finishedAt: Date?
    public var batchId: String?
    public var importMode: String
    public var includeInactive: Bool
    public var mergeIntoExistingListing: Bool
    public var mergeIntoExistingInventory: Bool
    public var totalCount: Double
    public var importedCount: Double
    public var skippedCount: Double
    public var errorCount: Double

    public init(id: String, createdAt: Date, userId: String, status: String, platform: String, lastError: String? = nil, startedAt: Date? = nil, filters: ListImportsItemFilters? = nil, finishedAt: Date? = nil, batchId: String? = nil, importMode: String, includeInactive: Bool, mergeIntoExistingListing: Bool, mergeIntoExistingInventory: Bool, totalCount: Double, importedCount: Double, skippedCount: Double, errorCount: Double) {
        self.id = id
        self.createdAt = createdAt
        self.userId = userId
        self.status = status
        self.platform = platform
        self.lastError = lastError
        self.startedAt = startedAt
        self.filters = filters
        self.finishedAt = finishedAt
        self.batchId = batchId
        self.importMode = importMode
        self.includeInactive = includeInactive
        self.mergeIntoExistingListing = mergeIntoExistingListing
        self.mergeIntoExistingInventory = mergeIntoExistingInventory
        self.totalCount = totalCount
        self.importedCount = importedCount
        self.skippedCount = skippedCount
        self.errorCount = errorCount
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case createdAt
        case userId
        case status
        case platform
        case lastError
        case startedAt
        case filters
        case finishedAt
        case batchId
        case importMode
        case includeInactive
        case mergeIntoExistingListing
        case mergeIntoExistingInventory
        case totalCount
        case importedCount
        case skippedCount
        case errorCount
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(createdAt, forKey: .createdAt)
        try container.encode(userId, forKey: .userId)
        try container.encode(status, forKey: .status)
        try container.encode(platform, forKey: .platform)
        try container.encodeIfPresent(lastError, forKey: .lastError)
        try container.encodeIfPresent(startedAt, forKey: .startedAt)
        try container.encodeIfPresent(filters, forKey: .filters)
        try container.encodeIfPresent(finishedAt, forKey: .finishedAt)
        try container.encodeIfPresent(batchId, forKey: .batchId)
        try container.encode(importMode, forKey: .importMode)
        try container.encode(includeInactive, forKey: .includeInactive)
        try container.encode(mergeIntoExistingListing, forKey: .mergeIntoExistingListing)
        try container.encode(mergeIntoExistingInventory, forKey: .mergeIntoExistingInventory)
        try container.encode(totalCount, forKey: .totalCount)
        try container.encode(importedCount, forKey: .importedCount)
        try container.encode(skippedCount, forKey: .skippedCount)
        try container.encode(errorCount, forKey: .errorCount)
    }
}

