//
// ListCbxWalletPaymentReviewItem.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ListCbxWalletPaymentReviewItem: Codable, JSONEncodable, Hashable {

    public var id: String
    public var externalId: String
    public var payerAddress: String
    public var baseUnits: String
    public var valueCents: Double
    public var riskLevel: String?
    public var riskExposures: [String]
    public var screeningProvider: String?
    public var releaseReason: String?
    public var txSig: String
    public var confirmedAt: String

    public init(id: String, externalId: String, payerAddress: String, baseUnits: String, valueCents: Double, riskLevel: String? = nil, riskExposures: [String], screeningProvider: String? = nil, releaseReason: String? = nil, txSig: String, confirmedAt: String) {
        self.id = id
        self.externalId = externalId
        self.payerAddress = payerAddress
        self.baseUnits = baseUnits
        self.valueCents = valueCents
        self.riskLevel = riskLevel
        self.riskExposures = riskExposures
        self.screeningProvider = screeningProvider
        self.releaseReason = releaseReason
        self.txSig = txSig
        self.confirmedAt = confirmedAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case externalId
        case payerAddress
        case baseUnits
        case valueCents
        case riskLevel
        case riskExposures
        case screeningProvider
        case releaseReason
        case txSig
        case confirmedAt
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(externalId, forKey: .externalId)
        try container.encode(payerAddress, forKey: .payerAddress)
        try container.encode(baseUnits, forKey: .baseUnits)
        try container.encode(valueCents, forKey: .valueCents)
        try container.encodeIfPresent(riskLevel, forKey: .riskLevel)
        try container.encode(riskExposures, forKey: .riskExposures)
        try container.encodeIfPresent(screeningProvider, forKey: .screeningProvider)
        try container.encodeIfPresent(releaseReason, forKey: .releaseReason)
        try container.encode(txSig, forKey: .txSig)
        try container.encode(confirmedAt, forKey: .confirmedAt)
    }
}

