//
// ListCbxBoostsItem.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ListCbxBoostsItem: Codable, JSONEncodable, Hashable {

    public var id: String
    public var name: String
    public var targetKind: String
    public var targetValue: String?
    public var boostedRateBps: Double
    public var budgetCents: Double
    public var spentCents: Double
    public var remainingCents: Double
    public var startsAt: String
    public var endsAt: String
    public var status: String

    public init(id: String, name: String, targetKind: String, targetValue: String? = nil, boostedRateBps: Double, budgetCents: Double, spentCents: Double, remainingCents: Double, startsAt: String, endsAt: String, status: String) {
        self.id = id
        self.name = name
        self.targetKind = targetKind
        self.targetValue = targetValue
        self.boostedRateBps = boostedRateBps
        self.budgetCents = budgetCents
        self.spentCents = spentCents
        self.remainingCents = remainingCents
        self.startsAt = startsAt
        self.endsAt = endsAt
        self.status = status
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case name
        case targetKind
        case targetValue
        case boostedRateBps
        case budgetCents
        case spentCents
        case remainingCents
        case startsAt
        case endsAt
        case status
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(name, forKey: .name)
        try container.encode(targetKind, forKey: .targetKind)
        try container.encodeIfPresent(targetValue, forKey: .targetValue)
        try container.encode(boostedRateBps, forKey: .boostedRateBps)
        try container.encode(budgetCents, forKey: .budgetCents)
        try container.encode(spentCents, forKey: .spentCents)
        try container.encode(remainingCents, forKey: .remainingCents)
        try container.encode(startsAt, forKey: .startsAt)
        try container.encode(endsAt, forKey: .endsAt)
        try container.encode(status, forKey: .status)
    }
}

