//
// ListBuyerActivityItem.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ListBuyerActivityItem: Codable, JSONEncodable, Hashable {

    public var id: String
    public var namespace: String
    public var identifierValue: String
    public var retailHost: String?
    public var pagePriceCents: Double?
    public var matched: Bool
    public var bestPriceCents: Double?
    public var observedAt: Date

    public init(id: String, namespace: String, identifierValue: String, retailHost: String? = nil, pagePriceCents: Double? = nil, matched: Bool, bestPriceCents: Double? = nil, observedAt: Date) {
        self.id = id
        self.namespace = namespace
        self.identifierValue = identifierValue
        self.retailHost = retailHost
        self.pagePriceCents = pagePriceCents
        self.matched = matched
        self.bestPriceCents = bestPriceCents
        self.observedAt = observedAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case namespace
        case identifierValue
        case retailHost
        case pagePriceCents
        case matched
        case bestPriceCents
        case observedAt
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(namespace, forKey: .namespace)
        try container.encode(identifierValue, forKey: .identifierValue)
        try container.encodeIfPresent(retailHost, forKey: .retailHost)
        try container.encodeIfPresent(pagePriceCents, forKey: .pagePriceCents)
        try container.encode(matched, forKey: .matched)
        try container.encodeIfPresent(bestPriceCents, forKey: .bestPriceCents)
        try container.encode(observedAt, forKey: .observedAt)
    }
}

