//
// ListMarketProductsItem.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ListMarketProductsItem: Codable, JSONEncodable, Hashable {

    public var id: String
    public var name: String
    public var brand: String?
    public var model: String?
    public var categorySlug: String
    public var styleCode: String?
    public var imageUrl: String?
    public var lowestAskCentsFrom: Double?
    public var highestBidCents: Double?
    public var lastSaleCents: Double?
    public var tradesCount: Double
    public var gradedGradeKeys: [String]

    public init(id: String, name: String, brand: String? = nil, model: String? = nil, categorySlug: String, styleCode: String? = nil, imageUrl: String? = nil, lowestAskCentsFrom: Double? = nil, highestBidCents: Double? = nil, lastSaleCents: Double? = nil, tradesCount: Double, gradedGradeKeys: [String]) {
        self.id = id
        self.name = name
        self.brand = brand
        self.model = model
        self.categorySlug = categorySlug
        self.styleCode = styleCode
        self.imageUrl = imageUrl
        self.lowestAskCentsFrom = lowestAskCentsFrom
        self.highestBidCents = highestBidCents
        self.lastSaleCents = lastSaleCents
        self.tradesCount = tradesCount
        self.gradedGradeKeys = gradedGradeKeys
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case name
        case brand
        case model
        case categorySlug
        case styleCode
        case imageUrl
        case lowestAskCentsFrom
        case highestBidCents
        case lastSaleCents
        case tradesCount
        case gradedGradeKeys
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(name, forKey: .name)
        try container.encodeIfPresent(brand, forKey: .brand)
        try container.encodeIfPresent(model, forKey: .model)
        try container.encode(categorySlug, forKey: .categorySlug)
        try container.encodeIfPresent(styleCode, forKey: .styleCode)
        try container.encodeIfPresent(imageUrl, forKey: .imageUrl)
        try container.encodeIfPresent(lowestAskCentsFrom, forKey: .lowestAskCentsFrom)
        try container.encodeIfPresent(highestBidCents, forKey: .highestBidCents)
        try container.encodeIfPresent(lastSaleCents, forKey: .lastSaleCents)
        try container.encode(tradesCount, forKey: .tradesCount)
        try container.encode(gradedGradeKeys, forKey: .gradedGradeKeys)
    }
}

