//
// ListBuyerMonitorMatchesItem.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ListBuyerMonitorMatchesItem: Codable, JSONEncodable, Hashable {

    public var listingSlug: String
    public var triggerPriceCents: Double
    public var deliveredAt: String?
    public var createdAt: String

    public init(listingSlug: String, triggerPriceCents: Double, deliveredAt: String? = nil, createdAt: String) {
        self.listingSlug = listingSlug
        self.triggerPriceCents = triggerPriceCents
        self.deliveredAt = deliveredAt
        self.createdAt = createdAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case listingSlug
        case triggerPriceCents
        case deliveredAt
        case createdAt
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(listingSlug, forKey: .listingSlug)
        try container.encode(triggerPriceCents, forKey: .triggerPriceCents)
        try container.encodeIfPresent(deliveredAt, forKey: .deliveredAt)
        try container.encode(createdAt, forKey: .createdAt)
    }
}

