//
// ListAuthSessionsItem.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ListAuthSessionsItem: Codable, JSONEncodable, Hashable {

    public var isCurrent: Bool
    public var id: String
    public var userAgent: String?
    public var ipAddress: String?
    public var ipCountry: String?
    public var createdAt: Date
    public var lastUsedAt: Date
    public var expiresAt: Date

    public init(isCurrent: Bool, id: String, userAgent: String? = nil, ipAddress: String? = nil, ipCountry: String? = nil, createdAt: Date, lastUsedAt: Date, expiresAt: Date) {
        self.isCurrent = isCurrent
        self.id = id
        self.userAgent = userAgent
        self.ipAddress = ipAddress
        self.ipCountry = ipCountry
        self.createdAt = createdAt
        self.lastUsedAt = lastUsedAt
        self.expiresAt = expiresAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case isCurrent
        case id
        case userAgent
        case ipAddress
        case ipCountry
        case createdAt
        case lastUsedAt
        case expiresAt
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(isCurrent, forKey: .isCurrent)
        try container.encode(id, forKey: .id)
        try container.encodeIfPresent(userAgent, forKey: .userAgent)
        try container.encodeIfPresent(ipAddress, forKey: .ipAddress)
        try container.encodeIfPresent(ipCountry, forKey: .ipCountry)
        try container.encode(createdAt, forKey: .createdAt)
        try container.encode(lastUsedAt, forKey: .lastUsedAt)
        try container.encode(expiresAt, forKey: .expiresAt)
    }
}

