//
// ListOrderUnitsItem.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ListOrderUnitsItem: Codable, JSONEncodable, Hashable {

    public var unitId: String
    public var identifiers: [ListOrderUnitsItemIdentifiers]

    public init(unitId: String, identifiers: [ListOrderUnitsItemIdentifiers]) {
        self.unitId = unitId
        self.identifiers = identifiers
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case unitId
        case identifiers
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(unitId, forKey: .unitId)
        try container.encode(identifiers, forKey: .identifiers)
    }
}

