//
// ListCbxDisbursementProgressItem.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ListCbxDisbursementProgressItem: Codable, JSONEncodable, Hashable {

    public var ruleId: String
    public var name: String
    public var poolBaseUnits: String
    public var thresholdBaseUnits: String
    public var progressBps: Double
    public var nextEligibleAt: String?
    public var lastFiredAt: String?

    public init(ruleId: String, name: String, poolBaseUnits: String, thresholdBaseUnits: String, progressBps: Double, nextEligibleAt: String? = nil, lastFiredAt: String? = nil) {
        self.ruleId = ruleId
        self.name = name
        self.poolBaseUnits = poolBaseUnits
        self.thresholdBaseUnits = thresholdBaseUnits
        self.progressBps = progressBps
        self.nextEligibleAt = nextEligibleAt
        self.lastFiredAt = lastFiredAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case ruleId
        case name
        case poolBaseUnits
        case thresholdBaseUnits
        case progressBps
        case nextEligibleAt
        case lastFiredAt
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(ruleId, forKey: .ruleId)
        try container.encode(name, forKey: .name)
        try container.encode(poolBaseUnits, forKey: .poolBaseUnits)
        try container.encode(thresholdBaseUnits, forKey: .thresholdBaseUnits)
        try container.encode(progressBps, forKey: .progressBps)
        try container.encodeIfPresent(nextEligibleAt, forKey: .nextEligibleAt)
        try container.encodeIfPresent(lastFiredAt, forKey: .lastFiredAt)
    }
}

