//
// UpdatePlatformPreferenceResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct UpdatePlatformPreferenceResponse: Codable, JSONEncodable, Hashable {

    public var ok: Bool
    public var updated: Double

    public init(ok: Bool, updated: Double) {
        self.ok = ok
        self.updated = updated
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case ok
        case updated
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(ok, forKey: .ok)
        try container.encode(updated, forKey: .updated)
    }
}

