//
// ActivityAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class ActivityAPI {

    /**
     Get one action-log event by id (ownership-checked).
     
     - parameter id: (path)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func getActionLog(id: UUID, apiResponseQueue: DispatchQueue = CrosslyAPI.apiResponseQueue, completion: @escaping ((_ data: GetActionLogResponse?, _ error: Error?) -> Void)) -> RequestTask {
        return getActionLogWithRequestBuilder(id: id).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Get one action-log event by id (ownership-checked).
     - GET /v1/action-log/{id}
     - BASIC:
       - type: http
       - name: PersonalAccessToken
     - parameter id: (path)  
     - returns: RequestBuilder<GetActionLogResponse> 
     */
    open class func getActionLogWithRequestBuilder(id: UUID) -> RequestBuilder<GetActionLogResponse> {
        var localVariablePath = "/v1/action-log/{id}"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = CrosslyAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<GetActionLogResponse>.Type = CrosslyAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters)
    }

    /**
     Distinct platforms / actions / categories present in the caller's action log (last 90 days) — powers filter dropdowns before you query.
     
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func getActionLogFacet(apiResponseQueue: DispatchQueue = CrosslyAPI.apiResponseQueue, completion: @escaping ((_ data: GetActionLogFacetResponse?, _ error: Error?) -> Void)) -> RequestTask {
        return getActionLogFacetWithRequestBuilder().execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Distinct platforms / actions / categories present in the caller's action log (last 90 days) — powers filter dropdowns before you query.
     - GET /v1/action-log/facets
     - BASIC:
       - type: http
       - name: PersonalAccessToken
     - returns: RequestBuilder<GetActionLogFacetResponse> 
     */
    open class func getActionLogFacetWithRequestBuilder() -> RequestBuilder<GetActionLogFacetResponse> {
        let localVariablePath = "/v1/action-log/facets"
        let localVariableURLString = CrosslyAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<GetActionLogFacetResponse>.Type = CrosslyAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters)
    }

    /**
     List action-log events — the semantic \"what happened\" record of every user + platform action. Filter by platform / action / category / status / source / target, and a since/until created_at window.
     
     - parameter platform: (query)  (optional)
     - parameter action: (query)  (optional)
     - parameter category: (query)  (optional)
     - parameter status: (query)  (optional)
     - parameter source: (query)  (optional)
     - parameter targetType: (query)  (optional)
     - parameter targetId: (query)  (optional)
     - parameter since: (query) ISO lower bound (inclusive) on created_at. (optional)
     - parameter until: (query) ISO upper bound (exclusive) on created_at. (optional)
     - parameter limit: (query)  (optional, default to 50)
     - parameter offset: (query)  (optional, default to 0)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func listActionLog(platform: String? = nil, action: String? = nil, category: String? = nil, status: String? = nil, source: String? = nil, targetType: String? = nil, targetId: String? = nil, since: String? = nil, until: String? = nil, limit: Int? = nil, offset: Int? = nil, apiResponseQueue: DispatchQueue = CrosslyAPI.apiResponseQueue, completion: @escaping ((_ data: V1List?, _ error: Error?) -> Void)) -> RequestTask {
        return listActionLogWithRequestBuilder(platform: platform, action: action, category: category, status: status, source: source, targetType: targetType, targetId: targetId, since: since, until: until, limit: limit, offset: offset).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     List action-log events — the semantic \"what happened\" record of every user + platform action. Filter by platform / action / category / status / source / target, and a since/until created_at window.
     - GET /v1/action-log
     - BASIC:
       - type: http
       - name: PersonalAccessToken
     - parameter platform: (query)  (optional)
     - parameter action: (query)  (optional)
     - parameter category: (query)  (optional)
     - parameter status: (query)  (optional)
     - parameter source: (query)  (optional)
     - parameter targetType: (query)  (optional)
     - parameter targetId: (query)  (optional)
     - parameter since: (query) ISO lower bound (inclusive) on created_at. (optional)
     - parameter until: (query) ISO upper bound (exclusive) on created_at. (optional)
     - parameter limit: (query)  (optional, default to 50)
     - parameter offset: (query)  (optional, default to 0)
     - returns: RequestBuilder<V1List> 
     */
    open class func listActionLogWithRequestBuilder(platform: String? = nil, action: String? = nil, category: String? = nil, status: String? = nil, source: String? = nil, targetType: String? = nil, targetId: String? = nil, since: String? = nil, until: String? = nil, limit: Int? = nil, offset: Int? = nil) -> RequestBuilder<V1List> {
        let localVariablePath = "/v1/action-log"
        let localVariableURLString = CrosslyAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "platform": platform?.encodeToJSON(),
            "action": action?.encodeToJSON(),
            "category": category?.encodeToJSON(),
            "status": status?.encodeToJSON(),
            "source": source?.encodeToJSON(),
            "targetType": targetType?.encodeToJSON(),
            "targetId": targetId?.encodeToJSON(),
            "since": since?.encodeToJSON(),
            "until": until?.encodeToJSON(),
            "limit": limit?.encodeToJSON(),
            "offset": offset?.encodeToJSON(),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<V1List>.Type = CrosslyAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters)
    }

    /**
     The outbound platform HTTP calls under an event (oldest first) — url, method, status, latency, redacted request/response bodies, proxy + recipe/hash. Answers \"what was sent / what went wrong\".
     
     - parameter id: (path)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func listActionLogCalls(id: UUID, apiResponseQueue: DispatchQueue = CrosslyAPI.apiResponseQueue, completion: @escaping ((_ data: V1List?, _ error: Error?) -> Void)) -> RequestTask {
        return listActionLogCallsWithRequestBuilder(id: id).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     The outbound platform HTTP calls under an event (oldest first) — url, method, status, latency, redacted request/response bodies, proxy + recipe/hash. Answers \"what was sent / what went wrong\".
     - GET /v1/action-log/{id}/calls
     - BASIC:
       - type: http
       - name: PersonalAccessToken
     - parameter id: (path)  
     - returns: RequestBuilder<V1List> 
     */
    open class func listActionLogCallsWithRequestBuilder(id: UUID) -> RequestBuilder<V1List> {
        var localVariablePath = "/v1/action-log/{id}/calls"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = CrosslyAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<V1List>.Type = CrosslyAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters)
    }
}
