//
// CustomersAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class CustomersAPI {

    /**
     Bulk blocklist customer handles.
     
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func createCustomerBulkDelete(apiResponseQueue: DispatchQueue = CrosslyAPI.apiResponseQueue, completion: @escaping ((_ data: CreateCustomerBulkDeleteResponse?, _ error: Error?) -> Void)) -> RequestTask {
        return createCustomerBulkDeleteWithRequestBuilder().execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Bulk blocklist customer handles.
     - POST /v1/customers/bulk-delete
     - BASIC:
       - type: http
       - name: PersonalAccessToken
     - returns: RequestBuilder<CreateCustomerBulkDeleteResponse> 
     */
    open class func createCustomerBulkDeleteWithRequestBuilder() -> RequestBuilder<CreateCustomerBulkDeleteResponse> {
        let localVariablePath = "/v1/customers/bulk-delete"
        let localVariableURLString = CrosslyAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<CreateCustomerBulkDeleteResponse>.Type = CrosslyAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters)
    }

    /**
     Bulk export aggregated customers as CSV.
     
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func createCustomerBulkExport(apiResponseQueue: DispatchQueue = CrosslyAPI.apiResponseQueue, completion: @escaping ((_ data: String?, _ error: Error?) -> Void)) -> RequestTask {
        return createCustomerBulkExportWithRequestBuilder().execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Bulk export aggregated customers as CSV.
     - POST /v1/customers/bulk-export
     - BASIC:
       - type: http
       - name: PersonalAccessToken
     - returns: RequestBuilder<String> 
     */
    open class func createCustomerBulkExportWithRequestBuilder() -> RequestBuilder<String> {
        let localVariablePath = "/v1/customers/bulk-export"
        let localVariableURLString = CrosslyAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<String>.Type = CrosslyAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters)
    }

    /**
     Get one customer with their recent 50 orders.
     
     - parameter handle: (path)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func getCustomer(handle: String, apiResponseQueue: DispatchQueue = CrosslyAPI.apiResponseQueue, completion: @escaping ((_ data: GetCustomerResponse?, _ error: Error?) -> Void)) -> RequestTask {
        return getCustomerWithRequestBuilder(handle: handle).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Get one customer with their recent 50 orders.
     - GET /v1/customers/{handle}
     - BASIC:
       - type: http
       - name: PersonalAccessToken
     - parameter handle: (path)  
     - returns: RequestBuilder<GetCustomerResponse> 
     */
    open class func getCustomerWithRequestBuilder(handle: String) -> RequestBuilder<GetCustomerResponse> {
        var localVariablePath = "/v1/customers/{handle}"
        let handlePreEscape = "\(APIHelper.mapValueToPathItem(handle))"
        let handlePostEscape = handlePreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{handle}", with: handlePostEscape, options: .literal, range: nil)
        let localVariableURLString = CrosslyAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<GetCustomerResponse>.Type = CrosslyAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters)
    }

    /**
     List aggregated customers (group-by lower(buyer_username)).
     
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func listCustomers(apiResponseQueue: DispatchQueue = CrosslyAPI.apiResponseQueue, completion: @escaping ((_ data: V1List?, _ error: Error?) -> Void)) -> RequestTask {
        return listCustomersWithRequestBuilder().execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     List aggregated customers (group-by lower(buyer_username)).
     - GET /v1/customers
     - BASIC:
       - type: http
       - name: PersonalAccessToken
     - returns: RequestBuilder<V1List> 
     */
    open class func listCustomersWithRequestBuilder() -> RequestBuilder<V1List> {
        let localVariablePath = "/v1/customers"
        let localVariableURLString = CrosslyAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<V1List>.Type = CrosslyAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters)
    }
}
