//
// ListingsAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class ListingsAPI {

    /**
     Create a listing and fan out crosspost jobs across platforms.
     
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func createListing(apiResponseQueue: DispatchQueue = CrosslyAPI.apiResponseQueue, completion: @escaping ((_ data: CreateListingResponse?, _ error: Error?) -> Void)) -> RequestTask {
        return createListingWithRequestBuilder().execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Create a listing and fan out crosspost jobs across platforms.
     - POST /v1/listings
     - BASIC:
       - type: http
       - name: PersonalAccessToken
     - returns: RequestBuilder<CreateListingResponse> 
     */
    open class func createListingWithRequestBuilder() -> RequestBuilder<CreateListingResponse> {
        let localVariablePath = "/v1/listings"
        let localVariableURLString = CrosslyAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<CreateListingResponse>.Type = CrosslyAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters)
    }

    /**
     Check listing status on platforms
     
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func createListingBulkCheckStatus(apiResponseQueue: DispatchQueue = CrosslyAPI.apiResponseQueue, completion: @escaping ((_ data: CreateListingBulkCheckStatusResponse?, _ error: Error?) -> Void)) -> RequestTask {
        return createListingBulkCheckStatusWithRequestBuilder().execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Check listing status on platforms
     - POST /v1/listings/bulk-check-status
     - BASIC:
       - type: http
       - name: PersonalAccessToken
     - returns: RequestBuilder<CreateListingBulkCheckStatusResponse> 
     */
    open class func createListingBulkCheckStatusWithRequestBuilder() -> RequestBuilder<CreateListingBulkCheckStatusResponse> {
        let localVariablePath = "/v1/listings/bulk-check-status"
        let localVariableURLString = CrosslyAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<CreateListingBulkCheckStatusResponse>.Type = CrosslyAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters)
    }

    /**
     Bulk crosspost (no delist phase)
     
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func createListingBulkCrosspost(apiResponseQueue: DispatchQueue = CrosslyAPI.apiResponseQueue, completion: @escaping ((_ data: CreateListingBulkCrosspostResponse?, _ error: Error?) -> Void)) -> RequestTask {
        return createListingBulkCrosspostWithRequestBuilder().execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Bulk crosspost (no delist phase)
     - POST /v1/listings/bulk-crosspost
     - BASIC:
       - type: http
       - name: PersonalAccessToken
     - returns: RequestBuilder<CreateListingBulkCrosspostResponse> 
     */
    open class func createListingBulkCrosspostWithRequestBuilder() -> RequestBuilder<CreateListingBulkCrosspostResponse> {
        let localVariablePath = "/v1/listings/bulk-crosspost"
        let localVariableURLString = CrosslyAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<CreateListingBulkCrosspostResponse>.Type = CrosslyAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters)
    }

    /**
     Bulk archive + delist
     
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func createListingBulkDelete(apiResponseQueue: DispatchQueue = CrosslyAPI.apiResponseQueue, completion: @escaping ((_ data: CreateListingBulkDeleteResponse?, _ error: Error?) -> Void)) -> RequestTask {
        return createListingBulkDeleteWithRequestBuilder().execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Bulk archive + delist
     - POST /v1/listings/bulk-delete
     - BASIC:
       - type: http
       - name: PersonalAccessToken
     - returns: RequestBuilder<CreateListingBulkDeleteResponse> 
     */
    open class func createListingBulkDeleteWithRequestBuilder() -> RequestBuilder<CreateListingBulkDeleteResponse> {
        let localVariablePath = "/v1/listings/bulk-delete"
        let localVariableURLString = CrosslyAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<CreateListingBulkDeleteResponse>.Type = CrosslyAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters)
    }

    /**
     Bulk delist from platforms
     
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func createListingBulkDelist(apiResponseQueue: DispatchQueue = CrosslyAPI.apiResponseQueue, completion: @escaping ((_ data: CreateListingBulkDelistResponse?, _ error: Error?) -> Void)) -> RequestTask {
        return createListingBulkDelistWithRequestBuilder().execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Bulk delist from platforms
     - POST /v1/listings/bulk-delist
     - BASIC:
       - type: http
       - name: PersonalAccessToken
     - returns: RequestBuilder<CreateListingBulkDelistResponse> 
     */
    open class func createListingBulkDelistWithRequestBuilder() -> RequestBuilder<CreateListingBulkDelistResponse> {
        let localVariablePath = "/v1/listings/bulk-delist"
        let localVariableURLString = CrosslyAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<CreateListingBulkDelistResponse>.Type = CrosslyAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters)
    }

    /**
     Preview which marketplaces a delist would touch
     
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func createListingBulkDelistPreview(apiResponseQueue: DispatchQueue = CrosslyAPI.apiResponseQueue, completion: @escaping ((_ data: CreateListingBulkDelistPreviewResponse?, _ error: Error?) -> Void)) -> RequestTask {
        return createListingBulkDelistPreviewWithRequestBuilder().execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Preview which marketplaces a delist would touch
     - POST /v1/listings/bulk-delist-preview
     - BASIC:
       - type: http
       - name: PersonalAccessToken
     - returns: RequestBuilder<CreateListingBulkDelistPreviewResponse> 
     */
    open class func createListingBulkDelistPreviewWithRequestBuilder() -> RequestBuilder<CreateListingBulkDelistPreviewResponse> {
        let localVariablePath = "/v1/listings/bulk-delist-preview"
        let localVariableURLString = CrosslyAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<CreateListingBulkDelistPreviewResponse>.Type = CrosslyAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters)
    }

    /**
     Permanently delete archived listings
     
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func createListingBulkHardDelete(apiResponseQueue: DispatchQueue = CrosslyAPI.apiResponseQueue, completion: @escaping ((_ data: CreateListingBulkHardDeleteResponse?, _ error: Error?) -> Void)) -> RequestTask {
        return createListingBulkHardDeleteWithRequestBuilder().execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Permanently delete archived listings
     - POST /v1/listings/bulk-hard-delete
     - BASIC:
       - type: http
       - name: PersonalAccessToken
     - returns: RequestBuilder<CreateListingBulkHardDeleteResponse> 
     */
    open class func createListingBulkHardDeleteWithRequestBuilder() -> RequestBuilder<CreateListingBulkHardDeleteResponse> {
        let localVariablePath = "/v1/listings/bulk-hard-delete"
        let localVariableURLString = CrosslyAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<CreateListingBulkHardDeleteResponse>.Type = CrosslyAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters)
    }

    /**
     Bulk relist across platforms
     
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func createListingBulkRelist(apiResponseQueue: DispatchQueue = CrosslyAPI.apiResponseQueue, completion: @escaping ((_ data: CreateListingBulkRelistResponse?, _ error: Error?) -> Void)) -> RequestTask {
        return createListingBulkRelistWithRequestBuilder().execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Bulk relist across platforms
     - POST /v1/listings/bulk-relist
     - BASIC:
       - type: http
       - name: PersonalAccessToken
     - returns: RequestBuilder<CreateListingBulkRelistResponse> 
     */
    open class func createListingBulkRelistWithRequestBuilder() -> RequestBuilder<CreateListingBulkRelistResponse> {
        let localVariablePath = "/v1/listings/bulk-relist"
        let localVariableURLString = CrosslyAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<CreateListingBulkRelistResponse>.Type = CrosslyAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters)
    }

    /**
     Bulk update listing fields
     
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func createListingBulkUpdate(apiResponseQueue: DispatchQueue = CrosslyAPI.apiResponseQueue, completion: @escaping ((_ data: CreateListingBulkUpdateResponse?, _ error: Error?) -> Void)) -> RequestTask {
        return createListingBulkUpdateWithRequestBuilder().execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Bulk update listing fields
     - POST /v1/listings/bulk-update
     - BASIC:
       - type: http
       - name: PersonalAccessToken
     - returns: RequestBuilder<CreateListingBulkUpdateResponse> 
     */
    open class func createListingBulkUpdateWithRequestBuilder() -> RequestBuilder<CreateListingBulkUpdateResponse> {
        let localVariablePath = "/v1/listings/bulk-update"
        let localVariableURLString = CrosslyAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<CreateListingBulkUpdateResponse>.Type = CrosslyAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters)
    }

    /**
     Fetch hydrated listings by ID
     
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func createListingById(apiResponseQueue: DispatchQueue = CrosslyAPI.apiResponseQueue, completion: @escaping ((_ data: CreateListingByIdResponse?, _ error: Error?) -> Void)) -> RequestTask {
        return createListingByIdWithRequestBuilder().execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Fetch hydrated listings by ID
     - POST /v1/listings/by-ids
     - BASIC:
       - type: http
       - name: PersonalAccessToken
     - returns: RequestBuilder<CreateListingByIdResponse> 
     */
    open class func createListingByIdWithRequestBuilder() -> RequestBuilder<CreateListingByIdResponse> {
        let localVariablePath = "/v1/listings/by-ids"
        let localVariableURLString = CrosslyAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<CreateListingByIdResponse>.Type = CrosslyAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters)
    }

    /**
     Check whether the seller already owns something matching this title/photo, and what to do about it.
     
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func createListingCheckDuplicate(apiResponseQueue: DispatchQueue = CrosslyAPI.apiResponseQueue, completion: @escaping ((_ data: CreateListingCheckDuplicateResponse?, _ error: Error?) -> Void)) -> RequestTask {
        return createListingCheckDuplicateWithRequestBuilder().execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Check whether the seller already owns something matching this title/photo, and what to do about it.
     - POST /v1/listings/check-duplicates
     - BASIC:
       - type: http
       - name: PersonalAccessToken
     - returns: RequestBuilder<CreateListingCheckDuplicateResponse> 
     */
    open class func createListingCheckDuplicateWithRequestBuilder() -> RequestBuilder<CreateListingCheckDuplicateResponse> {
        let localVariablePath = "/v1/listings/check-duplicates"
        let localVariableURLString = CrosslyAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<CreateListingCheckDuplicateResponse>.Type = CrosslyAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters)
    }

    /**
     Combine duplicate listings into one: sums their stock, delists and archives the rest.
     
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func createListingCombine(apiResponseQueue: DispatchQueue = CrosslyAPI.apiResponseQueue, completion: @escaping ((_ data: CreateListingCombineResponse?, _ error: Error?) -> Void)) -> RequestTask {
        return createListingCombineWithRequestBuilder().execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Combine duplicate listings into one: sums their stock, delists and archives the rest.
     - POST /v1/listings/combine
     - BASIC:
       - type: http
       - name: PersonalAccessToken
     - returns: RequestBuilder<CreateListingCombineResponse> 
     */
    open class func createListingCombineWithRequestBuilder() -> RequestBuilder<CreateListingCombineResponse> {
        let localVariablePath = "/v1/listings/combine"
        let localVariableURLString = CrosslyAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<CreateListingCombineResponse>.Type = CrosslyAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters)
    }

    /**
     Resolve a detected marketplace-drift discrepancy: accept the platform value, push ours back, relist to apply it, or dismiss.
     
     - parameter id: (path)  
     - parameter discrepancyId: (path)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func createListingDiscrepancyResolve(id: UUID, discrepancyId: UUID, apiResponseQueue: DispatchQueue = CrosslyAPI.apiResponseQueue, completion: @escaping ((_ data: CreateListingDiscrepancyResolveResponse?, _ error: Error?) -> Void)) -> RequestTask {
        return createListingDiscrepancyResolveWithRequestBuilder(id: id, discrepancyId: discrepancyId).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Resolve a detected marketplace-drift discrepancy: accept the platform value, push ours back, relist to apply it, or dismiss.
     - POST /v1/listings/{id}/discrepancies/{discrepancyId}/resolve
     - BASIC:
       - type: http
       - name: PersonalAccessToken
     - parameter id: (path)  
     - parameter discrepancyId: (path)  
     - returns: RequestBuilder<CreateListingDiscrepancyResolveResponse> 
     */
    open class func createListingDiscrepancyResolveWithRequestBuilder(id: UUID, discrepancyId: UUID) -> RequestBuilder<CreateListingDiscrepancyResolveResponse> {
        var localVariablePath = "/v1/listings/{id}/discrepancies/{discrepancyId}/resolve"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let discrepancyIdPreEscape = "\(APIHelper.mapValueToPathItem(discrepancyId))"
        let discrepancyIdPostEscape = discrepancyIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{discrepancyId}", with: discrepancyIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = CrosslyAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<CreateListingDiscrepancyResolveResponse>.Type = CrosslyAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters)
    }

    /**
     Attach a real platform listing to this listing by pasting its live URL.
     
     - parameter id: (path)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func createListingImportByUrl(id: UUID, apiResponseQueue: DispatchQueue = CrosslyAPI.apiResponseQueue, completion: @escaping ((_ data: CreateListingImportByUrlResponse?, _ error: Error?) -> Void)) -> RequestTask {
        return createListingImportByUrlWithRequestBuilder(id: id).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Attach a real platform listing to this listing by pasting its live URL.
     - POST /v1/listings/{id}/import-by-url
     - BASIC:
       - type: http
       - name: PersonalAccessToken
     - parameter id: (path)  
     - returns: RequestBuilder<CreateListingImportByUrlResponse> 
     */
    open class func createListingImportByUrlWithRequestBuilder(id: UUID) -> RequestBuilder<CreateListingImportByUrlResponse> {
        var localVariablePath = "/v1/listings/{id}/import-by-url"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = CrosslyAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<CreateListingImportByUrlResponse>.Type = CrosslyAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters)
    }

    /**
     Auto-fill empty fields on one platform tab from the master listing + AI/deterministic taxonomy resolution.
     
     - parameter id: (path)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func createListingMagicFill(id: UUID, apiResponseQueue: DispatchQueue = CrosslyAPI.apiResponseQueue, completion: @escaping ((_ data: CreateListingMagicFillResponse?, _ error: Error?) -> Void)) -> RequestTask {
        return createListingMagicFillWithRequestBuilder(id: id).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Auto-fill empty fields on one platform tab from the master listing + AI/deterministic taxonomy resolution.
     - POST /v1/listings/{id}/magic-fill
     - BASIC:
       - type: http
       - name: PersonalAccessToken
     - parameter id: (path)  
     - returns: RequestBuilder<CreateListingMagicFillResponse> 
     */
    open class func createListingMagicFillWithRequestBuilder(id: UUID) -> RequestBuilder<CreateListingMagicFillResponse> {
        var localVariablePath = "/v1/listings/{id}/magic-fill"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = CrosslyAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<CreateListingMagicFillResponse>.Type = CrosslyAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters)
    }

    /**
     Delist a listing (optionally narrowed to specific platforms via ?platforms=).
     
     - parameter id: (path)  
     - parameter platforms: (query) Comma-separated platform slugs to limit the delist fan-out. (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func deleteListing(id: UUID, platforms: String? = nil, apiResponseQueue: DispatchQueue = CrosslyAPI.apiResponseQueue, completion: @escaping ((_ data: DeleteListingResponse?, _ error: Error?) -> Void)) -> RequestTask {
        return deleteListingWithRequestBuilder(id: id, platforms: platforms).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Delist a listing (optionally narrowed to specific platforms via ?platforms=).
     - DELETE /v1/listings/{id}
     - BASIC:
       - type: http
       - name: PersonalAccessToken
     - parameter id: (path)  
     - parameter platforms: (query) Comma-separated platform slugs to limit the delist fan-out. (optional)
     - returns: RequestBuilder<DeleteListingResponse> 
     */
    open class func deleteListingWithRequestBuilder(id: UUID, platforms: String? = nil) -> RequestBuilder<DeleteListingResponse> {
        var localVariablePath = "/v1/listings/{id}"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = CrosslyAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "platforms": platforms?.encodeToJSON(),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<DeleteListingResponse>.Type = CrosslyAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "DELETE", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters)
    }

    /**
     Get one listing with its platform rows.
     
     - parameter id: (path)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func getListing(id: UUID, apiResponseQueue: DispatchQueue = CrosslyAPI.apiResponseQueue, completion: @escaping ((_ data: GetListingResponse?, _ error: Error?) -> Void)) -> RequestTask {
        return getListingWithRequestBuilder(id: id).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Get one listing with its platform rows.
     - GET /v1/listings/{id}
     - BASIC:
       - type: http
       - name: PersonalAccessToken
     - parameter id: (path)  
     - returns: RequestBuilder<GetListingResponse> 
     */
    open class func getListingWithRequestBuilder(id: UUID) -> RequestBuilder<GetListingResponse> {
        var localVariablePath = "/v1/listings/{id}"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = CrosslyAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<GetListingResponse>.Type = CrosslyAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters)
    }

    /**
     Distinct brands + categories across listings + inventory.
     
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func getListingFacet(apiResponseQueue: DispatchQueue = CrosslyAPI.apiResponseQueue, completion: @escaping ((_ data: GetListingFacetResponse?, _ error: Error?) -> Void)) -> RequestTask {
        return getListingFacetWithRequestBuilder().execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Distinct brands + categories across listings + inventory.
     - GET /v1/listings/facets
     - BASIC:
       - type: http
       - name: PersonalAccessToken
     - returns: RequestBuilder<GetListingFacetResponse> 
     */
    open class func getListingFacetWithRequestBuilder() -> RequestBuilder<GetListingFacetResponse> {
        let localVariablePath = "/v1/listings/facets"
        let localVariableURLString = CrosslyAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<GetListingFacetResponse>.Type = CrosslyAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters)
    }

    /**
     Check whether a SKU is already used by one of this user's items.
     
     - parameter sku: (query)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func getListingSkuExist(sku: String, apiResponseQueue: DispatchQueue = CrosslyAPI.apiResponseQueue, completion: @escaping ((_ data: GetListingSkuExistResponse?, _ error: Error?) -> Void)) -> RequestTask {
        return getListingSkuExistWithRequestBuilder(sku: sku).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Check whether a SKU is already used by one of this user's items.
     - GET /v1/listings/sku-exists
     - BASIC:
       - type: http
       - name: PersonalAccessToken
     - parameter sku: (query)  
     - returns: RequestBuilder<GetListingSkuExistResponse> 
     */
    open class func getListingSkuExistWithRequestBuilder(sku: String) -> RequestBuilder<GetListingSkuExistResponse> {
        let localVariablePath = "/v1/listings/sku-exists"
        let localVariableURLString = CrosslyAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "sku": sku.encodeToJSON(),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<GetListingSkuExistResponse>.Type = CrosslyAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters)
    }

    /**
     List detected marketplace-drift discrepancies for a listing.
     
     - parameter id: (path)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func listListingDiscrepancies(id: UUID, apiResponseQueue: DispatchQueue = CrosslyAPI.apiResponseQueue, completion: @escaping ((_ data: V1List?, _ error: Error?) -> Void)) -> RequestTask {
        return listListingDiscrepanciesWithRequestBuilder(id: id).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     List detected marketplace-drift discrepancies for a listing.
     - GET /v1/listings/{id}/discrepancies
     - BASIC:
       - type: http
       - name: PersonalAccessToken
     - parameter id: (path)  
     - returns: RequestBuilder<V1List> 
     */
    open class func listListingDiscrepanciesWithRequestBuilder(id: UUID) -> RequestBuilder<V1List> {
        var localVariablePath = "/v1/listings/{id}/discrepancies"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = CrosslyAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<V1List>.Type = CrosslyAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters)
    }

    /**
     Filter listings → return matching id list (no pagination).
     
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func listListingIds(apiResponseQueue: DispatchQueue = CrosslyAPI.apiResponseQueue, completion: @escaping ((_ data: V1List?, _ error: Error?) -> Void)) -> RequestTask {
        return listListingIdsWithRequestBuilder().execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Filter listings → return matching id list (no pagination).
     - GET /v1/listings/ids
     - BASIC:
       - type: http
       - name: PersonalAccessToken
     - returns: RequestBuilder<V1List> 
     */
    open class func listListingIdsWithRequestBuilder() -> RequestBuilder<V1List> {
        let localVariablePath = "/v1/listings/ids"
        let localVariableURLString = CrosslyAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<V1List>.Type = CrosslyAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters)
    }

    /**
     List active platform listings.
     
     - parameter page: (query)  (optional, default to 1)
     - parameter limit: (query)  (optional, default to 25)
     - parameter platform: (query)  (optional)
     - parameter status: (query)  (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func listListings(page: Int? = nil, limit: Int? = nil, platform: String? = nil, status: String? = nil, apiResponseQueue: DispatchQueue = CrosslyAPI.apiResponseQueue, completion: @escaping ((_ data: V1List?, _ error: Error?) -> Void)) -> RequestTask {
        return listListingsWithRequestBuilder(page: page, limit: limit, platform: platform, status: status).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     List active platform listings.
     - GET /v1/listings
     - BASIC:
       - type: http
       - name: PersonalAccessToken
     - parameter page: (query)  (optional, default to 1)
     - parameter limit: (query)  (optional, default to 25)
     - parameter platform: (query)  (optional)
     - parameter status: (query)  (optional)
     - returns: RequestBuilder<V1List> 
     */
    open class func listListingsWithRequestBuilder(page: Int? = nil, limit: Int? = nil, platform: String? = nil, status: String? = nil) -> RequestBuilder<V1List> {
        let localVariablePath = "/v1/listings"
        let localVariableURLString = CrosslyAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "page": page?.encodeToJSON(),
            "limit": limit?.encodeToJSON(),
            "platform": platform?.encodeToJSON(),
            "status": status?.encodeToJSON(),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<V1List>.Type = CrosslyAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters)
    }

    /**
     Edit a listing and fan out update jobs to existing platform listings.
     
     - parameter id: (path)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func updateListing(id: UUID, apiResponseQueue: DispatchQueue = CrosslyAPI.apiResponseQueue, completion: @escaping ((_ data: UpdateListingResponse?, _ error: Error?) -> Void)) -> RequestTask {
        return updateListingWithRequestBuilder(id: id).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Edit a listing and fan out update jobs to existing platform listings.
     - PATCH /v1/listings/{id}
     - BASIC:
       - type: http
       - name: PersonalAccessToken
     - parameter id: (path)  
     - returns: RequestBuilder<UpdateListingResponse> 
     */
    open class func updateListingWithRequestBuilder(id: UUID) -> RequestBuilder<UpdateListingResponse> {
        var localVariablePath = "/v1/listings/{id}"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = CrosslyAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<UpdateListingResponse>.Type = CrosslyAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "PATCH", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters)
    }
}
