//
// OffersAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class OffersAPI {

    /**
     Accept, decline, or counter a buyer offer on a Crossly marketplace listing.
     
     - parameter id: (path) Offer UUID. 
     - parameter inlineObject2: (body)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func createOfferRespond(id: String, inlineObject2: InlineObject2, apiResponseQueue: DispatchQueue = CrosslyAPI.apiResponseQueue, completion: @escaping ((_ data: CreateOfferRespondResponse?, _ error: Error?) -> Void)) -> RequestTask {
        return createOfferRespondWithRequestBuilder(id: id, inlineObject2: inlineObject2).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Accept, decline, or counter a buyer offer on a Crossly marketplace listing.
     - POST /v1/offers/{id}/respond
     - BASIC:
       - type: http
       - name: PersonalAccessToken
     - parameter id: (path) Offer UUID. 
     - parameter inlineObject2: (body)  
     - returns: RequestBuilder<CreateOfferRespondResponse> 
     */
    open class func createOfferRespondWithRequestBuilder(id: String, inlineObject2: InlineObject2) -> RequestBuilder<CreateOfferRespondResponse> {
        var localVariablePath = "/v1/offers/{id}/respond"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = CrosslyAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: inlineObject2)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<CreateOfferRespondResponse>.Type = CrosslyAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters)
    }

    /**
     * enum for parameter status
     */
    public enum Status_getOffer: String, CaseIterable {
        case pending = "pending"
        case accepted = "accepted"
        case declined = "declined"
        case countered = "countered"
        case expired = "expired"
        case withdrawn = "withdrawn"
    }

    /**
     List buyer offers on your Crossly marketplace listings, including bundles.
     
     - parameter status: (query) Filter to one status. Omit for all. (optional)
     - parameter limit: (query)  (optional, default to 50)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func getOffer(status: Status_getOffer? = nil, limit: Int? = nil, apiResponseQueue: DispatchQueue = CrosslyAPI.apiResponseQueue, completion: @escaping ((_ data: GetOfferResponse?, _ error: Error?) -> Void)) -> RequestTask {
        return getOfferWithRequestBuilder(status: status, limit: limit).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     List buyer offers on your Crossly marketplace listings, including bundles.
     - GET /v1/offers
     - BASIC:
       - type: http
       - name: PersonalAccessToken
     - parameter status: (query) Filter to one status. Omit for all. (optional)
     - parameter limit: (query)  (optional, default to 50)
     - returns: RequestBuilder<GetOfferResponse> 
     */
    open class func getOfferWithRequestBuilder(status: Status_getOffer? = nil, limit: Int? = nil) -> RequestBuilder<GetOfferResponse> {
        let localVariablePath = "/v1/offers"
        let localVariableURLString = CrosslyAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "status": status?.encodeToJSON(),
            "limit": limit?.encodeToJSON(),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<GetOfferResponse>.Type = CrosslyAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters)
    }
}
