//
// PayoutAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class PayoutAPI {

    /**
     What one platform nets at a given price, after fees and shipping.
     
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func getPayoutEstimate(apiResponseQueue: DispatchQueue = CrosslyAPI.apiResponseQueue, completion: @escaping ((_ data: GetPayoutEstimateResponse?, _ error: Error?) -> Void)) -> RequestTask {
        return getPayoutEstimateWithRequestBuilder().execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     What one platform nets at a given price, after fees and shipping.
     - GET /v1/payout/estimate
     - BASIC:
       - type: http
       - name: PersonalAccessToken
     - returns: RequestBuilder<GetPayoutEstimateResponse> 
     */
    open class func getPayoutEstimateWithRequestBuilder() -> RequestBuilder<GetPayoutEstimateResponse> {
        let localVariablePath = "/v1/payout/estimate"
        let localVariableURLString = CrosslyAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<GetPayoutEstimateResponse>.Type = CrosslyAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters)
    }

    /**
     The gross price needed to clear a target net on one platform.
     
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func getPayoutGrossForNet(apiResponseQueue: DispatchQueue = CrosslyAPI.apiResponseQueue, completion: @escaping ((_ data: GetPayoutGrossForNetResponse?, _ error: Error?) -> Void)) -> RequestTask {
        return getPayoutGrossForNetWithRequestBuilder().execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     The gross price needed to clear a target net on one platform.
     - GET /v1/payout/gross-for-net
     - BASIC:
       - type: http
       - name: PersonalAccessToken
     - returns: RequestBuilder<GetPayoutGrossForNetResponse> 
     */
    open class func getPayoutGrossForNetWithRequestBuilder() -> RequestBuilder<GetPayoutGrossForNetResponse> {
        let localVariablePath = "/v1/payout/gross-for-net"
        let localVariableURLString = CrosslyAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<GetPayoutGrossForNetResponse>.Type = CrosslyAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters)
    }

    /**
     Rank platforms by what they net at a given price. Defaults to connected ones.
     
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func listPayoutCompare(apiResponseQueue: DispatchQueue = CrosslyAPI.apiResponseQueue, completion: @escaping ((_ data: V1List?, _ error: Error?) -> Void)) -> RequestTask {
        return listPayoutCompareWithRequestBuilder().execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Rank platforms by what they net at a given price. Defaults to connected ones.
     - GET /v1/payout/compare
     - BASIC:
       - type: http
       - name: PersonalAccessToken
     - returns: RequestBuilder<V1List> 
     */
    open class func listPayoutCompareWithRequestBuilder() -> RequestBuilder<V1List> {
        let localVariablePath = "/v1/payout/compare"
        let localVariableURLString = CrosslyAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<V1List>.Type = CrosslyAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters)
    }
}
