//
// TaxonomyAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class TaxonomyAPI {

    /**
     Categories for a platform. Default is top-level; pass `?parent=<categoryId>` to drill down one level (supported on cookie platforms whose recipe returns flat parent_id-linked rows).
     
     - parameter platform: (path)  
     - parameter parent: (query)  (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func getTaxonomyCategory(platform: String, parent: String? = nil, apiResponseQueue: DispatchQueue = CrosslyAPI.apiResponseQueue, completion: @escaping ((_ data: GetTaxonomyCategoryResponse?, _ error: Error?) -> Void)) -> RequestTask {
        return getTaxonomyCategoryWithRequestBuilder(platform: platform, parent: parent).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Categories for a platform. Default is top-level; pass `?parent=<categoryId>` to drill down one level (supported on cookie platforms whose recipe returns flat parent_id-linked rows).
     - GET /v1/taxonomy/{platform}/categories
     - BASIC:
       - type: http
       - name: PersonalAccessToken
     - parameter platform: (path)  
     - parameter parent: (query)  (optional)
     - returns: RequestBuilder<GetTaxonomyCategoryResponse> 
     */
    open class func getTaxonomyCategoryWithRequestBuilder(platform: String, parent: String? = nil) -> RequestBuilder<GetTaxonomyCategoryResponse> {
        var localVariablePath = "/v1/taxonomy/{platform}/categories"
        let platformPreEscape = "\(APIHelper.mapValueToPathItem(platform))"
        let platformPostEscape = platformPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{platform}", with: platformPostEscape, options: .literal, range: nil)
        let localVariableURLString = CrosslyAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "parent": parent?.encodeToJSON(),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<GetTaxonomyCategoryResponse>.Type = CrosslyAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters)
    }

    /**
     Item-specific aspects (eBay) / properties (Etsy) / hard-coded enums (cookie platforms) for a category.
     
     - parameter platform: (path)  
     - parameter id: (path)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func getTaxonomyCategoryAspect(platform: String, id: String, apiResponseQueue: DispatchQueue = CrosslyAPI.apiResponseQueue, completion: @escaping ((_ data: GetTaxonomyCategoryAspectResponse?, _ error: Error?) -> Void)) -> RequestTask {
        return getTaxonomyCategoryAspectWithRequestBuilder(platform: platform, id: id).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Item-specific aspects (eBay) / properties (Etsy) / hard-coded enums (cookie platforms) for a category.
     - GET /v1/taxonomy/{platform}/categories/{id}/aspects
     - BASIC:
       - type: http
       - name: PersonalAccessToken
     - parameter platform: (path)  
     - parameter id: (path)  
     - returns: RequestBuilder<GetTaxonomyCategoryAspectResponse> 
     */
    open class func getTaxonomyCategoryAspectWithRequestBuilder(platform: String, id: String) -> RequestBuilder<GetTaxonomyCategoryAspectResponse> {
        var localVariablePath = "/v1/taxonomy/{platform}/categories/{id}/aspects"
        let platformPreEscape = "\(APIHelper.mapValueToPathItem(platform))"
        let platformPostEscape = platformPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{platform}", with: platformPostEscape, options: .literal, range: nil)
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = CrosslyAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<GetTaxonomyCategoryAspectResponse>.Type = CrosslyAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters)
    }

    /**
     Direct children of a category node.
     
     - parameter platform: (path)  
     - parameter id: (path)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func getTaxonomyCategoryChildren(platform: String, id: String, apiResponseQueue: DispatchQueue = CrosslyAPI.apiResponseQueue, completion: @escaping ((_ data: GetTaxonomyCategoryChildrenResponse?, _ error: Error?) -> Void)) -> RequestTask {
        return getTaxonomyCategoryChildrenWithRequestBuilder(platform: platform, id: id).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Direct children of a category node.
     - GET /v1/taxonomy/{platform}/categories/{id}/children
     - BASIC:
       - type: http
       - name: PersonalAccessToken
     - parameter platform: (path)  
     - parameter id: (path)  
     - returns: RequestBuilder<GetTaxonomyCategoryChildrenResponse> 
     */
    open class func getTaxonomyCategoryChildrenWithRequestBuilder(platform: String, id: String) -> RequestBuilder<GetTaxonomyCategoryChildrenResponse> {
        var localVariablePath = "/v1/taxonomy/{platform}/categories/{id}/children"
        let platformPreEscape = "\(APIHelper.mapValueToPathItem(platform))"
        let platformPostEscape = platformPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{platform}", with: platformPostEscape, options: .literal, range: nil)
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = CrosslyAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<GetTaxonomyCategoryChildrenResponse>.Type = CrosslyAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters)
    }

    /**
     Normalized field schema the seller needs to fill before crossposting to this platform. Combines master fields (title/description/price/condition) with platform-specific overrides.
     
     - parameter platform: (path)  
     - parameter categoryId: (query) Optional — used to inline aspects when present. (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func getTaxonomyRequiredField(platform: String, categoryId: String? = nil, apiResponseQueue: DispatchQueue = CrosslyAPI.apiResponseQueue, completion: @escaping ((_ data: GetTaxonomyRequiredFieldResponse?, _ error: Error?) -> Void)) -> RequestTask {
        return getTaxonomyRequiredFieldWithRequestBuilder(platform: platform, categoryId: categoryId).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Normalized field schema the seller needs to fill before crossposting to this platform. Combines master fields (title/description/price/condition) with platform-specific overrides.
     - GET /v1/taxonomy/{platform}/required-fields
     - BASIC:
       - type: http
       - name: PersonalAccessToken
     - parameter platform: (path)  
     - parameter categoryId: (query) Optional — used to inline aspects when present. (optional)
     - returns: RequestBuilder<GetTaxonomyRequiredFieldResponse> 
     */
    open class func getTaxonomyRequiredFieldWithRequestBuilder(platform: String, categoryId: String? = nil) -> RequestBuilder<GetTaxonomyRequiredFieldResponse> {
        var localVariablePath = "/v1/taxonomy/{platform}/required-fields"
        let platformPreEscape = "\(APIHelper.mapValueToPathItem(platform))"
        let platformPostEscape = platformPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{platform}", with: platformPostEscape, options: .literal, range: nil)
        let localVariableURLString = CrosslyAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "categoryId": categoryId?.encodeToJSON(),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<GetTaxonomyRequiredFieldResponse>.Type = CrosslyAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters)
    }

    /**
     Reverse lookup — suggest categories matching a search phrase. eBay-only today.
     
     - parameter platform: (path)  
     - parameter q: (query)  (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func listTaxonomySuggest(platform: String, q: String? = nil, apiResponseQueue: DispatchQueue = CrosslyAPI.apiResponseQueue, completion: @escaping ((_ data: V1List?, _ error: Error?) -> Void)) -> RequestTask {
        return listTaxonomySuggestWithRequestBuilder(platform: platform, q: q).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Reverse lookup — suggest categories matching a search phrase. eBay-only today.
     - GET /v1/taxonomy/{platform}/suggest
     - BASIC:
       - type: http
       - name: PersonalAccessToken
     - parameter platform: (path)  
     - parameter q: (query)  (optional)
     - returns: RequestBuilder<V1List> 
     */
    open class func listTaxonomySuggestWithRequestBuilder(platform: String, q: String? = nil) -> RequestBuilder<V1List> {
        var localVariablePath = "/v1/taxonomy/{platform}/suggest"
        let platformPreEscape = "\(APIHelper.mapValueToPathItem(platform))"
        let platformPostEscape = platformPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{platform}", with: platformPostEscape, options: .literal, range: nil)
        let localVariableURLString = CrosslyAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "q": q?.encodeToJSON(),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<V1List>.Type = CrosslyAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters)
    }
}
