//
// TeamAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class TeamAPI {

    /**
     Accept a pending team invitation by raw token.
     
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func createTeamAccept(apiResponseQueue: DispatchQueue = CrosslyAPI.apiResponseQueue, completion: @escaping ((_ data: CreateTeamAcceptResponse?, _ error: Error?) -> Void)) -> RequestTask {
        return createTeamAcceptWithRequestBuilder().execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Accept a pending team invitation by raw token.
     - POST /v1/team/accept
     - BASIC:
       - type: http
       - name: PersonalAccessToken
     - returns: RequestBuilder<CreateTeamAcceptResponse> 
     */
    open class func createTeamAcceptWithRequestBuilder() -> RequestBuilder<CreateTeamAcceptResponse> {
        let localVariablePath = "/v1/team/accept"
        let localVariableURLString = CrosslyAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<CreateTeamAcceptResponse>.Type = CrosslyAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters)
    }

    /**
     Mint a team invitation; returns the one-time accept URL.
     
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func createTeamInvite(apiResponseQueue: DispatchQueue = CrosslyAPI.apiResponseQueue, completion: @escaping ((_ data: CreateTeamInviteResponse?, _ error: Error?) -> Void)) -> RequestTask {
        return createTeamInviteWithRequestBuilder().execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Mint a team invitation; returns the one-time accept URL.
     - POST /v1/team/invite
     - BASIC:
       - type: http
       - name: PersonalAccessToken
     - returns: RequestBuilder<CreateTeamInviteResponse> 
     */
    open class func createTeamInviteWithRequestBuilder() -> RequestBuilder<CreateTeamInviteResponse> {
        let localVariablePath = "/v1/team/invite"
        let localVariableURLString = CrosslyAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<CreateTeamInviteResponse>.Type = CrosslyAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters)
    }

    /**
     Leave every team this user is currently a member of.
     
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func createTeamLeave(apiResponseQueue: DispatchQueue = CrosslyAPI.apiResponseQueue, completion: @escaping ((_ data: CreateTeamLeaveResponse?, _ error: Error?) -> Void)) -> RequestTask {
        return createTeamLeaveWithRequestBuilder().execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Leave every team this user is currently a member of.
     - POST /v1/team/leave
     - BASIC:
       - type: http
       - name: PersonalAccessToken
     - returns: RequestBuilder<CreateTeamLeaveResponse> 
     */
    open class func createTeamLeaveWithRequestBuilder() -> RequestBuilder<CreateTeamLeaveResponse> {
        let localVariablePath = "/v1/team/leave"
        let localVariableURLString = CrosslyAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<CreateTeamLeaveResponse>.Type = CrosslyAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters)
    }

    /**
     Revoke a pending invite OR an active team member.
     
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func createTeamRevoke(apiResponseQueue: DispatchQueue = CrosslyAPI.apiResponseQueue, completion: @escaping ((_ data: CreateTeamRevokeResponse?, _ error: Error?) -> Void)) -> RequestTask {
        return createTeamRevokeWithRequestBuilder().execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Revoke a pending invite OR an active team member.
     - POST /v1/team/revoke
     - BASIC:
       - type: http
       - name: PersonalAccessToken
     - returns: RequestBuilder<CreateTeamRevokeResponse> 
     */
    open class func createTeamRevokeWithRequestBuilder() -> RequestBuilder<CreateTeamRevokeResponse> {
        let localVariablePath = "/v1/team/revoke"
        let localVariableURLString = CrosslyAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<CreateTeamRevokeResponse>.Type = CrosslyAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters)
    }

    /**
     List pending team invitations + active members.
     
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func getTeam(apiResponseQueue: DispatchQueue = CrosslyAPI.apiResponseQueue, completion: @escaping ((_ data: GetTeamResponse?, _ error: Error?) -> Void)) -> RequestTask {
        return getTeamWithRequestBuilder().execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     List pending team invitations + active members.
     - GET /v1/team
     - BASIC:
       - type: http
       - name: PersonalAccessToken
     - returns: RequestBuilder<GetTeamResponse> 
     */
    open class func getTeamWithRequestBuilder() -> RequestBuilder<GetTeamResponse> {
        let localVariablePath = "/v1/team"
        let localVariableURLString = CrosslyAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<GetTeamResponse>.Type = CrosslyAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters)
    }

    /**
     Update a team member's scopes (owner only).
     
     - parameter memberId: (path)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func updateTeam(memberId: UUID, apiResponseQueue: DispatchQueue = CrosslyAPI.apiResponseQueue, completion: @escaping ((_ data: UpdateTeamResponse?, _ error: Error?) -> Void)) -> RequestTask {
        return updateTeamWithRequestBuilder(memberId: memberId).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Update a team member's scopes (owner only).
     - PATCH /v1/team/{memberId}
     - BASIC:
       - type: http
       - name: PersonalAccessToken
     - parameter memberId: (path)  
     - returns: RequestBuilder<UpdateTeamResponse> 
     */
    open class func updateTeamWithRequestBuilder(memberId: UUID) -> RequestBuilder<UpdateTeamResponse> {
        var localVariablePath = "/v1/team/{memberId}"
        let memberIdPreEscape = "\(APIHelper.mapValueToPathItem(memberId))"
        let memberIdPostEscape = memberIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{memberId}", with: memberIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = CrosslyAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<UpdateTeamResponse>.Type = CrosslyAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "PATCH", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters)
    }
}
